/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransactionPaymentResponseAchTenderInfoCommissionType from './TransactionPaymentResponseAchTenderInfoCommissionType';

/**
 * The MerchantTransactionEntityResponseDataInner model module.
 * @module model/MerchantTransactionEntityResponseDataInner
 * @version 2.3
 */
class MerchantTransactionEntityResponseDataInner {
    /**
     * Constructs a new <code>MerchantTransactionEntityResponseDataInner</code>.
     * @alias module:model/MerchantTransactionEntityResponseDataInner
     */
    constructor() { 
        
        MerchantTransactionEntityResponseDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerchantTransactionEntityResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerchantTransactionEntityResponseDataInner} obj Optional instance to populate.
     * @return {module:model/MerchantTransactionEntityResponseDataInner} The populated <code>MerchantTransactionEntityResponseDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerchantTransactionEntityResponseDataInner();

            if (data.hasOwnProperty('transactionId')) {
                obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
            }
            if (data.hasOwnProperty('merchantId')) {
                obj['merchantId'] = ApiClient.convertToType(data['merchantId'], 'String');
            }
            if (data.hasOwnProperty('ipAddress')) {
                obj['ipAddress'] = ApiClient.convertToType(data['ipAddress'], 'String');
            }
            if (data.hasOwnProperty('transactionDate')) {
                obj['transactionDate'] = ApiClient.convertToType(data['transactionDate'], 'String');
            }
            if (data.hasOwnProperty('operationType')) {
                obj['operationType'] = ApiClient.convertToType(data['operationType'], 'String');
            }
            if (data.hasOwnProperty('channelType')) {
                obj['channelType'] = ApiClient.convertToType(data['channelType'], 'String');
            }
            if (data.hasOwnProperty('processMethod')) {
                obj['processMethod'] = ApiClient.convertToType(data['processMethod'], 'String');
            }
            if (data.hasOwnProperty('isDebit')) {
                obj['isDebit'] = ApiClient.convertToType(data['isDebit'], 'Boolean');
            }
            if (data.hasOwnProperty('referenceTransactionId')) {
                obj['referenceTransactionId'] = ApiClient.convertToType(data['referenceTransactionId'], 'String');
            }
            if (data.hasOwnProperty('referenceCustomerId')) {
                obj['referenceCustomerId'] = ApiClient.convertToType(data['referenceCustomerId'], 'String');
            }
            if (data.hasOwnProperty('recurringId')) {
                obj['recurringId'] = ApiClient.convertToType(data['recurringId'], 'String');
            }
            if (data.hasOwnProperty('batchId')) {
                obj['batchId'] = ApiClient.convertToType(data['batchId'], 'Number');
            }
            if (data.hasOwnProperty('transactionStatus')) {
                obj['transactionStatus'] = ApiClient.convertToType(data['transactionStatus'], 'String');
            }
            if (data.hasOwnProperty('settlementDate')) {
                obj['settlementDate'] = ApiClient.convertToType(data['settlementDate'], 'String');
            }
            if (data.hasOwnProperty('authCode')) {
                obj['authCode'] = ApiClient.convertToType(data['authCode'], 'String');
            }
            if (data.hasOwnProperty('cardNumber')) {
                obj['cardNumber'] = ApiClient.convertToType(data['cardNumber'], 'String');
            }
            if (data.hasOwnProperty('accountNumber')) {
                obj['accountNumber'] = ApiClient.convertToType(data['accountNumber'], 'String');
            }
            if (data.hasOwnProperty('binNumber')) {
                obj['binNumber'] = ApiClient.convertToType(data['binNumber'], 'String');
            }
            if (data.hasOwnProperty('chequeNumber')) {
                obj['chequeNumber'] = ApiClient.convertToType(data['chequeNumber'], 'String');
            }
            if (data.hasOwnProperty('routingNumber')) {
                obj['routingNumber'] = ApiClient.convertToType(data['routingNumber'], 'String');
            }
            if (data.hasOwnProperty('nameOnCheckOrCard')) {
                obj['nameOnCheckOrCard'] = ApiClient.convertToType(data['nameOnCheckOrCard'], 'String');
            }
            if (data.hasOwnProperty('accountHolderName')) {
                obj['accountHolderName'] = ApiClient.convertToType(data['accountHolderName'], 'String');
            }
            if (data.hasOwnProperty('accountCategory')) {
                obj['accountCategory'] = ApiClient.convertToType(data['accountCategory'], 'String');
            }
            if (data.hasOwnProperty('trainingMode')) {
                obj['trainingMode'] = ApiClient.convertToType(data['trainingMode'], 'Boolean');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('convenienceAmount')) {
                obj['convenienceAmount'] = ApiClient.convertToType(data['convenienceAmount'], 'Number');
            }
            if (data.hasOwnProperty('captureAmount')) {
                obj['captureAmount'] = ApiClient.convertToType(data['captureAmount'], 'Number');
            }
            if (data.hasOwnProperty('cardType')) {
                obj['cardType'] = ApiClient.convertToType(data['cardType'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'String');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('modifiedOn')) {
                obj['modifiedOn'] = ApiClient.convertToType(data['modifiedOn'], 'String');
            }
            if (data.hasOwnProperty('modifiedBy')) {
                obj['modifiedBy'] = ApiClient.convertToType(data['modifiedBy'], 'String');
            }
            if (data.hasOwnProperty('customerName')) {
                obj['customerName'] = ApiClient.convertToType(data['customerName'], 'String');
            }
            if (data.hasOwnProperty('partnerId')) {
                obj['partnerId'] = ApiClient.convertToType(data['partnerId'], 'String');
            }
            if (data.hasOwnProperty('partnerName')) {
                obj['partnerName'] = ApiClient.convertToType(data['partnerName'], 'String');
            }
            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
            }
            if (data.hasOwnProperty('invoiceId')) {
                obj['invoiceId'] = ApiClient.convertToType(data['invoiceId'], 'String');
            }
            if (data.hasOwnProperty('paymentLinkId')) {
                obj['paymentLinkId'] = ApiClient.convertToType(data['paymentLinkId'], 'String');
            }
            if (data.hasOwnProperty('referenceNo')) {
                obj['referenceNo'] = ApiClient.convertToType(data['referenceNo'], 'String');
            }
            if (data.hasOwnProperty('processorName')) {
                obj['processorName'] = ApiClient.convertToType(data['processorName'], 'String');
            }
            if (data.hasOwnProperty('processorDisplayName')) {
                obj['processorDisplayName'] = ApiClient.convertToType(data['processorDisplayName'], 'String');
            }
            if (data.hasOwnProperty('verification2Code')) {
                obj['verification2Code'] = ApiClient.convertToType(data['verification2Code'], 'String');
            }
            if (data.hasOwnProperty('transactionOrigin')) {
                obj['transactionOrigin'] = ApiClient.convertToType(data['transactionOrigin'], 'String');
            }
            if (data.hasOwnProperty('previousTransactionStatus')) {
                obj['previousTransactionStatus'] = ApiClient.convertToType(data['previousTransactionStatus'], 'String');
            }
            if (data.hasOwnProperty('traceNumber')) {
                obj['traceNumber'] = ApiClient.convertToType(data['traceNumber'], 'String');
            }
            if (data.hasOwnProperty('merchantReference')) {
                obj['merchantReference'] = ApiClient.convertToType(data['merchantReference'], 'String');
            }
            if (data.hasOwnProperty('additionaFields')) {
                obj['additionaFields'] = ApiClient.convertToType(data['additionaFields'], 'String');
            }
            if (data.hasOwnProperty('adjustmentValue')) {
                obj['adjustmentValue'] = ApiClient.convertToType(data['adjustmentValue'], 'Number');
            }
            if (data.hasOwnProperty('adjustmentFixedValue')) {
                obj['adjustmentFixedValue'] = ApiClient.convertToType(data['adjustmentFixedValue'], 'Number');
            }
            if (data.hasOwnProperty('adjustmentAmount')) {
                obj['adjustmentAmount'] = ApiClient.convertToType(data['adjustmentAmount'], 'Number');
            }
            if (data.hasOwnProperty('adjustmentDisplayName')) {
                obj['adjustmentDisplayName'] = ApiClient.convertToType(data['adjustmentDisplayName'], 'String');
            }
            if (data.hasOwnProperty('adjustmentDescriptorMessage')) {
                obj['adjustmentDescriptorMessage'] = ApiClient.convertToType(data['adjustmentDescriptorMessage'], 'String');
            }
            if (data.hasOwnProperty('paymentAdjustmentType')) {
                obj['paymentAdjustmentType'] = ApiClient.convertToType(data['paymentAdjustmentType'], 'String');
            }
            if (data.hasOwnProperty('commissionType')) {
                obj['commissionType'] = TransactionPaymentResponseAchTenderInfoCommissionType.constructFromObject(data['commissionType']);
            }
            if (data.hasOwnProperty('commissionValue')) {
                obj['commissionValue'] = ApiClient.convertToType(data['commissionValue'], 'Number');
            }
            if (data.hasOwnProperty('commissionFixedValue')) {
                obj['commissionFixedValue'] = ApiClient.convertToType(data['commissionFixedValue'], 'Number');
            }
            if (data.hasOwnProperty('accountToken')) {
                obj['accountToken'] = ApiClient.convertToType(data['accountToken'], 'String');
            }
            if (data.hasOwnProperty('paymentType')) {
                obj['paymentType'] = ApiClient.convertToType(data['paymentType'], 'String');
            }
            if (data.hasOwnProperty('paymentCategory')) {
                obj['paymentCategory'] = ApiClient.convertToType(data['paymentCategory'], 'String');
            }
            if (data.hasOwnProperty('refundReason')) {
                obj['refundReason'] = ApiClient.convertToType(data['refundReason'], 'String');
            }
            if (data.hasOwnProperty('refundDetail')) {
                obj['refundDetail'] = ApiClient.convertToType(data['refundDetail'], 'String');
            }
            if (data.hasOwnProperty('fullAccountNumber')) {
                obj['fullAccountNumber'] = ApiClient.convertToType(data['fullAccountNumber'], 'String');
            }
            if (data.hasOwnProperty('refundType')) {
                obj['refundType'] = ApiClient.convertToType(data['refundType'], 'String');
            }
            if (data.hasOwnProperty('suppressTechnologyFee')) {
                obj['suppressTechnologyFee'] = ApiClient.convertToType(data['suppressTechnologyFee'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MerchantTransactionEntityResponseDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MerchantTransactionEntityResponseDataInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['transactionId'] && !(typeof data['transactionId'] === 'string' || data['transactionId'] instanceof String)) {
            throw new Error("Expected the field `transactionId` to be a primitive type in the JSON string but got " + data['transactionId']);
        }
        // ensure the json data is a string
        if (data['merchantId'] && !(typeof data['merchantId'] === 'string' || data['merchantId'] instanceof String)) {
            throw new Error("Expected the field `merchantId` to be a primitive type in the JSON string but got " + data['merchantId']);
        }
        // ensure the json data is a string
        if (data['ipAddress'] && !(typeof data['ipAddress'] === 'string' || data['ipAddress'] instanceof String)) {
            throw new Error("Expected the field `ipAddress` to be a primitive type in the JSON string but got " + data['ipAddress']);
        }
        // ensure the json data is a string
        if (data['transactionDate'] && !(typeof data['transactionDate'] === 'string' || data['transactionDate'] instanceof String)) {
            throw new Error("Expected the field `transactionDate` to be a primitive type in the JSON string but got " + data['transactionDate']);
        }
        // ensure the json data is a string
        if (data['operationType'] && !(typeof data['operationType'] === 'string' || data['operationType'] instanceof String)) {
            throw new Error("Expected the field `operationType` to be a primitive type in the JSON string but got " + data['operationType']);
        }
        // ensure the json data is a string
        if (data['channelType'] && !(typeof data['channelType'] === 'string' || data['channelType'] instanceof String)) {
            throw new Error("Expected the field `channelType` to be a primitive type in the JSON string but got " + data['channelType']);
        }
        // ensure the json data is a string
        if (data['processMethod'] && !(typeof data['processMethod'] === 'string' || data['processMethod'] instanceof String)) {
            throw new Error("Expected the field `processMethod` to be a primitive type in the JSON string but got " + data['processMethod']);
        }
        // ensure the json data is a string
        if (data['referenceTransactionId'] && !(typeof data['referenceTransactionId'] === 'string' || data['referenceTransactionId'] instanceof String)) {
            throw new Error("Expected the field `referenceTransactionId` to be a primitive type in the JSON string but got " + data['referenceTransactionId']);
        }
        // ensure the json data is a string
        if (data['referenceCustomerId'] && !(typeof data['referenceCustomerId'] === 'string' || data['referenceCustomerId'] instanceof String)) {
            throw new Error("Expected the field `referenceCustomerId` to be a primitive type in the JSON string but got " + data['referenceCustomerId']);
        }
        // ensure the json data is a string
        if (data['recurringId'] && !(typeof data['recurringId'] === 'string' || data['recurringId'] instanceof String)) {
            throw new Error("Expected the field `recurringId` to be a primitive type in the JSON string but got " + data['recurringId']);
        }
        // ensure the json data is a string
        if (data['transactionStatus'] && !(typeof data['transactionStatus'] === 'string' || data['transactionStatus'] instanceof String)) {
            throw new Error("Expected the field `transactionStatus` to be a primitive type in the JSON string but got " + data['transactionStatus']);
        }
        // ensure the json data is a string
        if (data['settlementDate'] && !(typeof data['settlementDate'] === 'string' || data['settlementDate'] instanceof String)) {
            throw new Error("Expected the field `settlementDate` to be a primitive type in the JSON string but got " + data['settlementDate']);
        }
        // ensure the json data is a string
        if (data['authCode'] && !(typeof data['authCode'] === 'string' || data['authCode'] instanceof String)) {
            throw new Error("Expected the field `authCode` to be a primitive type in the JSON string but got " + data['authCode']);
        }
        // ensure the json data is a string
        if (data['cardNumber'] && !(typeof data['cardNumber'] === 'string' || data['cardNumber'] instanceof String)) {
            throw new Error("Expected the field `cardNumber` to be a primitive type in the JSON string but got " + data['cardNumber']);
        }
        // ensure the json data is a string
        if (data['accountNumber'] && !(typeof data['accountNumber'] === 'string' || data['accountNumber'] instanceof String)) {
            throw new Error("Expected the field `accountNumber` to be a primitive type in the JSON string but got " + data['accountNumber']);
        }
        // ensure the json data is a string
        if (data['binNumber'] && !(typeof data['binNumber'] === 'string' || data['binNumber'] instanceof String)) {
            throw new Error("Expected the field `binNumber` to be a primitive type in the JSON string but got " + data['binNumber']);
        }
        // ensure the json data is a string
        if (data['chequeNumber'] && !(typeof data['chequeNumber'] === 'string' || data['chequeNumber'] instanceof String)) {
            throw new Error("Expected the field `chequeNumber` to be a primitive type in the JSON string but got " + data['chequeNumber']);
        }
        // ensure the json data is a string
        if (data['routingNumber'] && !(typeof data['routingNumber'] === 'string' || data['routingNumber'] instanceof String)) {
            throw new Error("Expected the field `routingNumber` to be a primitive type in the JSON string but got " + data['routingNumber']);
        }
        // ensure the json data is a string
        if (data['nameOnCheckOrCard'] && !(typeof data['nameOnCheckOrCard'] === 'string' || data['nameOnCheckOrCard'] instanceof String)) {
            throw new Error("Expected the field `nameOnCheckOrCard` to be a primitive type in the JSON string but got " + data['nameOnCheckOrCard']);
        }
        // ensure the json data is a string
        if (data['accountHolderName'] && !(typeof data['accountHolderName'] === 'string' || data['accountHolderName'] instanceof String)) {
            throw new Error("Expected the field `accountHolderName` to be a primitive type in the JSON string but got " + data['accountHolderName']);
        }
        // ensure the json data is a string
        if (data['accountCategory'] && !(typeof data['accountCategory'] === 'string' || data['accountCategory'] instanceof String)) {
            throw new Error("Expected the field `accountCategory` to be a primitive type in the JSON string but got " + data['accountCategory']);
        }
        // ensure the json data is a string
        if (data['cardType'] && !(typeof data['cardType'] === 'string' || data['cardType'] instanceof String)) {
            throw new Error("Expected the field `cardType` to be a primitive type in the JSON string but got " + data['cardType']);
        }
        // ensure the json data is a string
        if (data['createdOn'] && !(typeof data['createdOn'] === 'string' || data['createdOn'] instanceof String)) {
            throw new Error("Expected the field `createdOn` to be a primitive type in the JSON string but got " + data['createdOn']);
        }
        // ensure the json data is a string
        if (data['createdBy'] && !(typeof data['createdBy'] === 'string' || data['createdBy'] instanceof String)) {
            throw new Error("Expected the field `createdBy` to be a primitive type in the JSON string but got " + data['createdBy']);
        }
        // ensure the json data is a string
        if (data['modifiedOn'] && !(typeof data['modifiedOn'] === 'string' || data['modifiedOn'] instanceof String)) {
            throw new Error("Expected the field `modifiedOn` to be a primitive type in the JSON string but got " + data['modifiedOn']);
        }
        // ensure the json data is a string
        if (data['modifiedBy'] && !(typeof data['modifiedBy'] === 'string' || data['modifiedBy'] instanceof String)) {
            throw new Error("Expected the field `modifiedBy` to be a primitive type in the JSON string but got " + data['modifiedBy']);
        }
        // ensure the json data is a string
        if (data['customerName'] && !(typeof data['customerName'] === 'string' || data['customerName'] instanceof String)) {
            throw new Error("Expected the field `customerName` to be a primitive type in the JSON string but got " + data['customerName']);
        }
        // ensure the json data is a string
        if (data['partnerId'] && !(typeof data['partnerId'] === 'string' || data['partnerId'] instanceof String)) {
            throw new Error("Expected the field `partnerId` to be a primitive type in the JSON string but got " + data['partnerId']);
        }
        // ensure the json data is a string
        if (data['partnerName'] && !(typeof data['partnerName'] === 'string' || data['partnerName'] instanceof String)) {
            throw new Error("Expected the field `partnerName` to be a primitive type in the JSON string but got " + data['partnerName']);
        }
        // ensure the json data is a string
        if (data['orderId'] && !(typeof data['orderId'] === 'string' || data['orderId'] instanceof String)) {
            throw new Error("Expected the field `orderId` to be a primitive type in the JSON string but got " + data['orderId']);
        }
        // ensure the json data is a string
        if (data['invoiceId'] && !(typeof data['invoiceId'] === 'string' || data['invoiceId'] instanceof String)) {
            throw new Error("Expected the field `invoiceId` to be a primitive type in the JSON string but got " + data['invoiceId']);
        }
        // ensure the json data is a string
        if (data['paymentLinkId'] && !(typeof data['paymentLinkId'] === 'string' || data['paymentLinkId'] instanceof String)) {
            throw new Error("Expected the field `paymentLinkId` to be a primitive type in the JSON string but got " + data['paymentLinkId']);
        }
        // ensure the json data is a string
        if (data['referenceNo'] && !(typeof data['referenceNo'] === 'string' || data['referenceNo'] instanceof String)) {
            throw new Error("Expected the field `referenceNo` to be a primitive type in the JSON string but got " + data['referenceNo']);
        }
        // ensure the json data is a string
        if (data['processorName'] && !(typeof data['processorName'] === 'string' || data['processorName'] instanceof String)) {
            throw new Error("Expected the field `processorName` to be a primitive type in the JSON string but got " + data['processorName']);
        }
        // ensure the json data is a string
        if (data['processorDisplayName'] && !(typeof data['processorDisplayName'] === 'string' || data['processorDisplayName'] instanceof String)) {
            throw new Error("Expected the field `processorDisplayName` to be a primitive type in the JSON string but got " + data['processorDisplayName']);
        }
        // ensure the json data is a string
        if (data['verification2Code'] && !(typeof data['verification2Code'] === 'string' || data['verification2Code'] instanceof String)) {
            throw new Error("Expected the field `verification2Code` to be a primitive type in the JSON string but got " + data['verification2Code']);
        }
        // ensure the json data is a string
        if (data['transactionOrigin'] && !(typeof data['transactionOrigin'] === 'string' || data['transactionOrigin'] instanceof String)) {
            throw new Error("Expected the field `transactionOrigin` to be a primitive type in the JSON string but got " + data['transactionOrigin']);
        }
        // ensure the json data is a string
        if (data['previousTransactionStatus'] && !(typeof data['previousTransactionStatus'] === 'string' || data['previousTransactionStatus'] instanceof String)) {
            throw new Error("Expected the field `previousTransactionStatus` to be a primitive type in the JSON string but got " + data['previousTransactionStatus']);
        }
        // ensure the json data is a string
        if (data['traceNumber'] && !(typeof data['traceNumber'] === 'string' || data['traceNumber'] instanceof String)) {
            throw new Error("Expected the field `traceNumber` to be a primitive type in the JSON string but got " + data['traceNumber']);
        }
        // ensure the json data is a string
        if (data['merchantReference'] && !(typeof data['merchantReference'] === 'string' || data['merchantReference'] instanceof String)) {
            throw new Error("Expected the field `merchantReference` to be a primitive type in the JSON string but got " + data['merchantReference']);
        }
        // ensure the json data is a string
        if (data['additionaFields'] && !(typeof data['additionaFields'] === 'string' || data['additionaFields'] instanceof String)) {
            throw new Error("Expected the field `additionaFields` to be a primitive type in the JSON string but got " + data['additionaFields']);
        }
        // ensure the json data is a string
        if (data['adjustmentDisplayName'] && !(typeof data['adjustmentDisplayName'] === 'string' || data['adjustmentDisplayName'] instanceof String)) {
            throw new Error("Expected the field `adjustmentDisplayName` to be a primitive type in the JSON string but got " + data['adjustmentDisplayName']);
        }
        // ensure the json data is a string
        if (data['adjustmentDescriptorMessage'] && !(typeof data['adjustmentDescriptorMessage'] === 'string' || data['adjustmentDescriptorMessage'] instanceof String)) {
            throw new Error("Expected the field `adjustmentDescriptorMessage` to be a primitive type in the JSON string but got " + data['adjustmentDescriptorMessage']);
        }
        // ensure the json data is a string
        if (data['paymentAdjustmentType'] && !(typeof data['paymentAdjustmentType'] === 'string' || data['paymentAdjustmentType'] instanceof String)) {
            throw new Error("Expected the field `paymentAdjustmentType` to be a primitive type in the JSON string but got " + data['paymentAdjustmentType']);
        }
        // validate the optional field `commissionType`
        if (data['commissionType']) { // data not null
          TransactionPaymentResponseAchTenderInfoCommissionType.validateJSON(data['commissionType']);
        }
        // ensure the json data is a string
        if (data['accountToken'] && !(typeof data['accountToken'] === 'string' || data['accountToken'] instanceof String)) {
            throw new Error("Expected the field `accountToken` to be a primitive type in the JSON string but got " + data['accountToken']);
        }
        // ensure the json data is a string
        if (data['paymentType'] && !(typeof data['paymentType'] === 'string' || data['paymentType'] instanceof String)) {
            throw new Error("Expected the field `paymentType` to be a primitive type in the JSON string but got " + data['paymentType']);
        }
        // ensure the json data is a string
        if (data['paymentCategory'] && !(typeof data['paymentCategory'] === 'string' || data['paymentCategory'] instanceof String)) {
            throw new Error("Expected the field `paymentCategory` to be a primitive type in the JSON string but got " + data['paymentCategory']);
        }
        // ensure the json data is a string
        if (data['refundReason'] && !(typeof data['refundReason'] === 'string' || data['refundReason'] instanceof String)) {
            throw new Error("Expected the field `refundReason` to be a primitive type in the JSON string but got " + data['refundReason']);
        }
        // ensure the json data is a string
        if (data['refundDetail'] && !(typeof data['refundDetail'] === 'string' || data['refundDetail'] instanceof String)) {
            throw new Error("Expected the field `refundDetail` to be a primitive type in the JSON string but got " + data['refundDetail']);
        }
        // ensure the json data is a string
        if (data['fullAccountNumber'] && !(typeof data['fullAccountNumber'] === 'string' || data['fullAccountNumber'] instanceof String)) {
            throw new Error("Expected the field `fullAccountNumber` to be a primitive type in the JSON string but got " + data['fullAccountNumber']);
        }
        // ensure the json data is a string
        if (data['refundType'] && !(typeof data['refundType'] === 'string' || data['refundType'] instanceof String)) {
            throw new Error("Expected the field `refundType` to be a primitive type in the JSON string but got " + data['refundType']);
        }

        return true;
    }


}



/**
 * @member {String} transactionId
 */
MerchantTransactionEntityResponseDataInner.prototype['transactionId'] = undefined;

/**
 * @member {String} merchantId
 */
MerchantTransactionEntityResponseDataInner.prototype['merchantId'] = undefined;

/**
 * @member {String} ipAddress
 */
MerchantTransactionEntityResponseDataInner.prototype['ipAddress'] = undefined;

/**
 * @member {String} transactionDate
 */
MerchantTransactionEntityResponseDataInner.prototype['transactionDate'] = undefined;

/**
 * @member {module:model/MerchantTransactionEntityResponseDataInner.OperationTypeEnum} operationType
 */
MerchantTransactionEntityResponseDataInner.prototype['operationType'] = undefined;

/**
 * @member {module:model/MerchantTransactionEntityResponseDataInner.ChannelTypeEnum} channelType
 */
MerchantTransactionEntityResponseDataInner.prototype['channelType'] = undefined;

/**
 * @member {module:model/MerchantTransactionEntityResponseDataInner.ProcessMethodEnum} processMethod
 */
MerchantTransactionEntityResponseDataInner.prototype['processMethod'] = undefined;

/**
 * @member {Boolean} isDebit
 */
MerchantTransactionEntityResponseDataInner.prototype['isDebit'] = undefined;

/**
 * @member {String} referenceTransactionId
 */
MerchantTransactionEntityResponseDataInner.prototype['referenceTransactionId'] = undefined;

/**
 * @member {String} referenceCustomerId
 */
MerchantTransactionEntityResponseDataInner.prototype['referenceCustomerId'] = undefined;

/**
 * @member {String} recurringId
 */
MerchantTransactionEntityResponseDataInner.prototype['recurringId'] = undefined;

/**
 * @member {Number} batchId
 */
MerchantTransactionEntityResponseDataInner.prototype['batchId'] = undefined;

/**
 * @member {module:model/MerchantTransactionEntityResponseDataInner.TransactionStatusEnum} transactionStatus
 */
MerchantTransactionEntityResponseDataInner.prototype['transactionStatus'] = undefined;

/**
 * @member {String} settlementDate
 */
MerchantTransactionEntityResponseDataInner.prototype['settlementDate'] = undefined;

/**
 * @member {String} authCode
 */
MerchantTransactionEntityResponseDataInner.prototype['authCode'] = undefined;

/**
 * @member {String} cardNumber
 */
MerchantTransactionEntityResponseDataInner.prototype['cardNumber'] = undefined;

/**
 * @member {String} accountNumber
 */
MerchantTransactionEntityResponseDataInner.prototype['accountNumber'] = undefined;

/**
 * @member {String} binNumber
 */
MerchantTransactionEntityResponseDataInner.prototype['binNumber'] = undefined;

/**
 * @member {String} chequeNumber
 */
MerchantTransactionEntityResponseDataInner.prototype['chequeNumber'] = undefined;

/**
 * @member {String} routingNumber
 */
MerchantTransactionEntityResponseDataInner.prototype['routingNumber'] = undefined;

/**
 * @member {String} nameOnCheckOrCard
 */
MerchantTransactionEntityResponseDataInner.prototype['nameOnCheckOrCard'] = undefined;

/**
 * @member {String} accountHolderName
 */
MerchantTransactionEntityResponseDataInner.prototype['accountHolderName'] = undefined;

/**
 * @member {module:model/MerchantTransactionEntityResponseDataInner.AccountCategoryEnum} accountCategory
 */
MerchantTransactionEntityResponseDataInner.prototype['accountCategory'] = undefined;

/**
 * @member {Boolean} trainingMode
 */
MerchantTransactionEntityResponseDataInner.prototype['trainingMode'] = undefined;

/**
 * @member {Number} amount
 */
MerchantTransactionEntityResponseDataInner.prototype['amount'] = undefined;

/**
 * @member {Number} convenienceAmount
 */
MerchantTransactionEntityResponseDataInner.prototype['convenienceAmount'] = undefined;

/**
 * @member {Number} captureAmount
 */
MerchantTransactionEntityResponseDataInner.prototype['captureAmount'] = undefined;

/**
 * @member {String} cardType
 */
MerchantTransactionEntityResponseDataInner.prototype['cardType'] = undefined;

/**
 * @member {String} createdOn
 */
MerchantTransactionEntityResponseDataInner.prototype['createdOn'] = undefined;

/**
 * @member {String} createdBy
 */
MerchantTransactionEntityResponseDataInner.prototype['createdBy'] = undefined;

/**
 * @member {String} modifiedOn
 */
MerchantTransactionEntityResponseDataInner.prototype['modifiedOn'] = undefined;

/**
 * @member {String} modifiedBy
 */
MerchantTransactionEntityResponseDataInner.prototype['modifiedBy'] = undefined;

/**
 * @member {String} customerName
 */
MerchantTransactionEntityResponseDataInner.prototype['customerName'] = undefined;

/**
 * @member {String} partnerId
 */
MerchantTransactionEntityResponseDataInner.prototype['partnerId'] = undefined;

/**
 * @member {String} partnerName
 */
MerchantTransactionEntityResponseDataInner.prototype['partnerName'] = undefined;

/**
 * @member {String} orderId
 */
MerchantTransactionEntityResponseDataInner.prototype['orderId'] = undefined;

/**
 * @member {String} invoiceId
 */
MerchantTransactionEntityResponseDataInner.prototype['invoiceId'] = undefined;

/**
 * @member {String} paymentLinkId
 */
MerchantTransactionEntityResponseDataInner.prototype['paymentLinkId'] = undefined;

/**
 * @member {String} referenceNo
 */
MerchantTransactionEntityResponseDataInner.prototype['referenceNo'] = undefined;

/**
 * @member {String} processorName
 */
MerchantTransactionEntityResponseDataInner.prototype['processorName'] = undefined;

/**
 * @member {String} processorDisplayName
 */
MerchantTransactionEntityResponseDataInner.prototype['processorDisplayName'] = undefined;

/**
 * @member {String} verification2Code
 */
MerchantTransactionEntityResponseDataInner.prototype['verification2Code'] = undefined;

/**
 * @member {module:model/MerchantTransactionEntityResponseDataInner.TransactionOriginEnum} transactionOrigin
 */
MerchantTransactionEntityResponseDataInner.prototype['transactionOrigin'] = undefined;

/**
 * @member {module:model/MerchantTransactionEntityResponseDataInner.PreviousTransactionStatusEnum} previousTransactionStatus
 */
MerchantTransactionEntityResponseDataInner.prototype['previousTransactionStatus'] = undefined;

/**
 * @member {String} traceNumber
 */
MerchantTransactionEntityResponseDataInner.prototype['traceNumber'] = undefined;

/**
 * @member {String} merchantReference
 */
MerchantTransactionEntityResponseDataInner.prototype['merchantReference'] = undefined;

/**
 * @member {String} additionaFields
 */
MerchantTransactionEntityResponseDataInner.prototype['additionaFields'] = undefined;

/**
 * @member {Number} adjustmentValue
 */
MerchantTransactionEntityResponseDataInner.prototype['adjustmentValue'] = undefined;

/**
 * @member {Number} adjustmentFixedValue
 */
MerchantTransactionEntityResponseDataInner.prototype['adjustmentFixedValue'] = undefined;

/**
 * @member {Number} adjustmentAmount
 */
MerchantTransactionEntityResponseDataInner.prototype['adjustmentAmount'] = undefined;

/**
 * @member {String} adjustmentDisplayName
 */
MerchantTransactionEntityResponseDataInner.prototype['adjustmentDisplayName'] = undefined;

/**
 * @member {String} adjustmentDescriptorMessage
 */
MerchantTransactionEntityResponseDataInner.prototype['adjustmentDescriptorMessage'] = undefined;

/**
 * @member {module:model/MerchantTransactionEntityResponseDataInner.PaymentAdjustmentTypeEnum} paymentAdjustmentType
 */
MerchantTransactionEntityResponseDataInner.prototype['paymentAdjustmentType'] = undefined;

/**
 * @member {module:model/TransactionPaymentResponseAchTenderInfoCommissionType} commissionType
 */
MerchantTransactionEntityResponseDataInner.prototype['commissionType'] = undefined;

/**
 * @member {Number} commissionValue
 */
MerchantTransactionEntityResponseDataInner.prototype['commissionValue'] = undefined;

/**
 * @member {Number} commissionFixedValue
 */
MerchantTransactionEntityResponseDataInner.prototype['commissionFixedValue'] = undefined;

/**
 * @member {String} accountToken
 */
MerchantTransactionEntityResponseDataInner.prototype['accountToken'] = undefined;

/**
 * @member {module:model/MerchantTransactionEntityResponseDataInner.PaymentTypeEnum} paymentType
 */
MerchantTransactionEntityResponseDataInner.prototype['paymentType'] = undefined;

/**
 * @member {module:model/MerchantTransactionEntityResponseDataInner.PaymentCategoryEnum} paymentCategory
 */
MerchantTransactionEntityResponseDataInner.prototype['paymentCategory'] = undefined;

/**
 * @member {String} refundReason
 */
MerchantTransactionEntityResponseDataInner.prototype['refundReason'] = undefined;

/**
 * @member {String} refundDetail
 */
MerchantTransactionEntityResponseDataInner.prototype['refundDetail'] = undefined;

/**
 * @member {String} fullAccountNumber
 */
MerchantTransactionEntityResponseDataInner.prototype['fullAccountNumber'] = undefined;

/**
 * @member {module:model/MerchantTransactionEntityResponseDataInner.RefundTypeEnum} refundType
 */
MerchantTransactionEntityResponseDataInner.prototype['refundType'] = undefined;

/**
 * @member {Boolean} suppressTechnologyFee
 */
MerchantTransactionEntityResponseDataInner.prototype['suppressTechnologyFee'] = undefined;





/**
 * Allowed values for the <code>operationType</code> property.
 * @enum {String}
 * @readonly
 */
MerchantTransactionEntityResponseDataInner['OperationTypeEnum'] = {

    /**
     * value: "Sale"
     * @const
     */
    "Sale": "Sale",

    /**
     * value: "VerifyOnly"
     * @const
     */
    "VerifyOnly": "VerifyOnly",

    /**
     * value: "ForceSale"
     * @const
     */
    "ForceSale": "ForceSale",

    /**
     * value: "Adjust"
     * @const
     */
    "Adjust": "Adjust",

    /**
     * value: "Activate"
     * @const
     */
    "Activate": "Activate",

    /**
     * value: "Deactivate"
     * @const
     */
    "Deactivate": "Deactivate",

    /**
     * value: "Reload"
     * @const
     */
    "Reload": "Reload",

    /**
     * value: "Refund"
     * @const
     */
    "Refund": "Refund",

    /**
     * value: "Inquire"
     * @const
     */
    "Inquire": "Inquire",

    /**
     * value: "ReverseAuth"
     * @const
     */
    "ReverseAuth": "ReverseAuth"
};


/**
 * Allowed values for the <code>channelType</code> property.
 * @enum {String}
 * @readonly
 */
MerchantTransactionEntityResponseDataInner['ChannelTypeEnum'] = {

    /**
     * value: "NotDefined"
     * @const
     */
    "NotDefined": "NotDefined",

    /**
     * value: "ACH"
     * @const
     */
    "ACH": "ACH",

    /**
     * value: "CreditCard"
     * @const
     */
    "CreditCard": "CreditCard",

    /**
     * value: "DebitCard"
     * @const
     */
    "DebitCard": "DebitCard"
};


/**
 * Allowed values for the <code>processMethod</code> property.
 * @enum {String}
 * @readonly
 */
MerchantTransactionEntityResponseDataInner['ProcessMethodEnum'] = {

    /**
     * value: "NotDefined"
     * @const
     */
    "NotDefined": "NotDefined",

    /**
     * value: "ACH"
     * @const
     */
    "ACH": "ACH",

    /**
     * value: "CardNotPresent"
     * @const
     */
    "CardNotPresent": "CardNotPresent"
};


/**
 * Allowed values for the <code>transactionStatus</code> property.
 * @enum {String}
 * @readonly
 */
MerchantTransactionEntityResponseDataInner['TransactionStatusEnum'] = {

    /**
     * value: "Created"
     * @const
     */
    "Created": "Created",

    /**
     * value: "PendingForAuthorized"
     * @const
     */
    "PendingForAuthorized": "PendingForAuthorized",

    /**
     * value: "Authorized"
     * @const
     */
    "Authorized": "Authorized",

    /**
     * value: "Posted"
     * @const
     */
    "Posted": "Posted",

    /**
     * value: "Captured"
     * @const
     */
    "Captured": "Captured",

    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed",

    /**
     * value: "Returned"
     * @const
     */
    "Returned": "Returned",

    /**
     * value: "Chargeback"
     * @const
     */
    "Chargeback": "Chargeback",

    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled",

    /**
     * value: "Refunded"
     * @const
     */
    "Refunded": "Refunded",

    /**
     * value: "Approved"
     * @const
     */
    "Approved": "Approved",

    /**
     * value: "CancelAttempt"
     * @const
     */
    "CancelAttempt": "CancelAttempt",

    /**
     * value: "RefundAttempt"
     * @const
     */
    "RefundAttempt": "RefundAttempt",

    /**
     * value: "Hold"
     * @const
     */
    "Hold": "Hold",

    /**
     * value: "Denied"
     * @const
     */
    "Denied": "Denied",

    /**
     * value: "SettlementHold"
     * @const
     */
    "SettlementHold": "SettlementHold",

    /**
     * value: "Success"
     * @const
     */
    "Success": "Success",

    /**
     * value: "Retried"
     * @const
     */
    "Retried": "Retried",

    /**
     * value: "ReprocessAttempt"
     * @const
     */
    "ReprocessAttempt": "ReprocessAttempt",

    /**
     * value: "Reprocessed"
     * @const
     */
    "Reprocessed": "Reprocessed",

    /**
     * value: "ChargebackReversed"
     * @const
     */
    "ChargebackReversed": "ChargebackReversed",

    /**
     * value: "RefundedReversed"
     * @const
     */
    "RefundedReversed": "RefundedReversed",

    /**
     * value: "Paid"
     * @const
     */
    "Paid": "Paid",

    /**
     * value: "PaidChargeback"
     * @const
     */
    "PaidChargeback": "PaidChargeback",

    /**
     * value: "PaidChargebackReversed"
     * @const
     */
    "PaidChargebackReversed": "PaidChargebackReversed",

    /**
     * value: "PaidRefunded"
     * @const
     */
    "PaidRefunded": "PaidRefunded",

    /**
     * value: "PaidRefundedReversed"
     * @const
     */
    "PaidRefundedReversed": "PaidRefundedReversed",

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "Unknown"
     * @const
     */
    "Unknown": "Unknown"
};


/**
 * Allowed values for the <code>accountCategory</code> property.
 * @enum {String}
 * @readonly
 */
MerchantTransactionEntityResponseDataInner['AccountCategoryEnum'] = {

    /**
     * value: "Unknown"
     * @const
     */
    "Unknown": "Unknown",

    /**
     * value: "Personal"
     * @const
     */
    "Personal": "Personal",

    /**
     * value: "Business"
     * @const
     */
    "Business": "Business"
};


/**
 * Allowed values for the <code>transactionOrigin</code> property.
 * @enum {String}
 * @readonly
 */
MerchantTransactionEntityResponseDataInner['TransactionOriginEnum'] = {

    /**
     * value: "Terminal"
     * @const
     */
    "Terminal": "Terminal",

    /**
     * value: "VirtualTerminal"
     * @const
     */
    "VirtualTerminal": "VirtualTerminal",

    /**
     * value: "WebForm"
     * @const
     */
    "WebForm": "WebForm",

    /**
     * value: "API"
     * @const
     */
    "API": "API",

    /**
     * value: "Schedule"
     * @const
     */
    "Schedule": "Schedule",

    /**
     * value: "Batch"
     * @const
     */
    "Batch": "Batch",

    /**
     * value: "PaymentIntent"
     * @const
     */
    "PaymentIntent": "PaymentIntent"
};


/**
 * Allowed values for the <code>previousTransactionStatus</code> property.
 * @enum {String}
 * @readonly
 */
MerchantTransactionEntityResponseDataInner['PreviousTransactionStatusEnum'] = {

    /**
     * value: "Created"
     * @const
     */
    "Created": "Created",

    /**
     * value: "PendingForAuthorized"
     * @const
     */
    "PendingForAuthorized": "PendingForAuthorized",

    /**
     * value: "Authorized"
     * @const
     */
    "Authorized": "Authorized",

    /**
     * value: "Posted"
     * @const
     */
    "Posted": "Posted",

    /**
     * value: "Captured"
     * @const
     */
    "Captured": "Captured",

    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed",

    /**
     * value: "Returned"
     * @const
     */
    "Returned": "Returned",

    /**
     * value: "Chargeback"
     * @const
     */
    "Chargeback": "Chargeback",

    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled",

    /**
     * value: "Refunded"
     * @const
     */
    "Refunded": "Refunded",

    /**
     * value: "Approved"
     * @const
     */
    "Approved": "Approved",

    /**
     * value: "CancelAttempt"
     * @const
     */
    "CancelAttempt": "CancelAttempt",

    /**
     * value: "RefundAttempt"
     * @const
     */
    "RefundAttempt": "RefundAttempt",

    /**
     * value: "Hold"
     * @const
     */
    "Hold": "Hold",

    /**
     * value: "Denied"
     * @const
     */
    "Denied": "Denied",

    /**
     * value: "SettlementHold"
     * @const
     */
    "SettlementHold": "SettlementHold",

    /**
     * value: "Success"
     * @const
     */
    "Success": "Success",

    /**
     * value: "Retried"
     * @const
     */
    "Retried": "Retried",

    /**
     * value: "ReprocessAttempt"
     * @const
     */
    "ReprocessAttempt": "ReprocessAttempt",

    /**
     * value: "Reprocessed"
     * @const
     */
    "Reprocessed": "Reprocessed",

    /**
     * value: "ChargebackReversed"
     * @const
     */
    "ChargebackReversed": "ChargebackReversed",

    /**
     * value: "RefundedReversed"
     * @const
     */
    "RefundedReversed": "RefundedReversed",

    /**
     * value: "Paid"
     * @const
     */
    "Paid": "Paid",

    /**
     * value: "PaidChargeback"
     * @const
     */
    "PaidChargeback": "PaidChargeback",

    /**
     * value: "PaidChargebackReversed"
     * @const
     */
    "PaidChargebackReversed": "PaidChargebackReversed",

    /**
     * value: "PaidRefunded"
     * @const
     */
    "PaidRefunded": "PaidRefunded",

    /**
     * value: "PaidRefundedReversed"
     * @const
     */
    "PaidRefundedReversed": "PaidRefundedReversed",

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "Unknown"
     * @const
     */
    "Unknown": "Unknown"
};


/**
 * Allowed values for the <code>paymentAdjustmentType</code> property.
 * @enum {String}
 * @readonly
 */
MerchantTransactionEntityResponseDataInner['PaymentAdjustmentTypeEnum'] = {

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "CashIncentive"
     * @const
     */
    "CashIncentive": "CashIncentive",

    /**
     * value: "Surcharge"
     * @const
     */
    "Surcharge": "Surcharge",

    /**
     * value: "ConvenienceFee"
     * @const
     */
    "ConvenienceFee": "ConvenienceFee",

    /**
     * value: "CashDiscount"
     * @const
     */
    "CashDiscount": "CashDiscount"
};


/**
 * Allowed values for the <code>paymentType</code> property.
 * @enum {String}
 * @readonly
 */
MerchantTransactionEntityResponseDataInner['PaymentTypeEnum'] = {

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "AnytimePayment"
     * @const
     */
    "AnytimePayment": "AnytimePayment",

    /**
     * value: "SubDomain"
     * @const
     */
    "SubDomain": "SubDomain",

    /**
     * value: "PaymentIntent"
     * @const
     */
    "PaymentIntent": "PaymentIntent",

    /**
     * value: "PaymentLink"
     * @const
     */
    "PaymentLink": "PaymentLink",

    /**
     * value: "OpenPayment"
     * @const
     */
    "OpenPayment": "OpenPayment",

    /**
     * value: "TokenLink"
     * @const
     */
    "TokenLink": "TokenLink"
};


/**
 * Allowed values for the <code>paymentCategory</code> property.
 * @enum {String}
 * @readonly
 */
MerchantTransactionEntityResponseDataInner['PaymentCategoryEnum'] = {

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "MerchantPayment"
     * @const
     */
    "MerchantPayment": "MerchantPayment",

    /**
     * value: "MPIPD"
     * @const
     */
    "MPIPD": "MPIPD",

    /**
     * value: "MPIPI"
     * @const
     */
    "MPIPI": "MPIPI",

    /**
     * value: "PFD"
     * @const
     */
    "PFD": "PFD",

    /**
     * value: "PFI"
     * @const
     */
    "PFI": "PFI"
};


/**
 * Allowed values for the <code>refundType</code> property.
 * @enum {String}
 * @readonly
 */
MerchantTransactionEntityResponseDataInner['RefundTypeEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Total"
     * @const
     */
    "Total": "Total",

    /**
     * value: "Subtotal"
     * @const
     */
    "Subtotal": "Subtotal",

    /**
     * value: "Remaining"
     * @const
     */
    "Remaining": "Remaining",

    /**
     * value: "Partial"
     * @const
     */
    "Partial": "Partial"
};



export default MerchantTransactionEntityResponseDataInner;

