/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OutboundPaymentTimelineResponseDTOInner model module.
 * @module model/OutboundPaymentTimelineResponseDTOInner
 * @version 2.3
 */
class OutboundPaymentTimelineResponseDTOInner {
    /**
     * Constructs a new <code>OutboundPaymentTimelineResponseDTOInner</code>.
     * @alias module:model/OutboundPaymentTimelineResponseDTOInner
     */
    constructor() { 
        
        OutboundPaymentTimelineResponseDTOInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OutboundPaymentTimelineResponseDTOInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OutboundPaymentTimelineResponseDTOInner} obj Optional instance to populate.
     * @return {module:model/OutboundPaymentTimelineResponseDTOInner} The populated <code>OutboundPaymentTimelineResponseDTOInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutboundPaymentTimelineResponseDTOInner();

            if (data.hasOwnProperty('paymentStatus')) {
                obj['paymentStatus'] = ApiClient.convertToType(data['paymentStatus'], 'String');
            }
            if (data.hasOwnProperty('paymentMethodStatus')) {
                obj['paymentMethodStatus'] = ApiClient.convertToType(data['paymentMethodStatus'], 'String');
            }
            if (data.hasOwnProperty('modifiedOn')) {
                obj['modifiedOn'] = ApiClient.convertToType(data['modifiedOn'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OutboundPaymentTimelineResponseDTOInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OutboundPaymentTimelineResponseDTOInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['paymentStatus'] && !(typeof data['paymentStatus'] === 'string' || data['paymentStatus'] instanceof String)) {
            throw new Error("Expected the field `paymentStatus` to be a primitive type in the JSON string but got " + data['paymentStatus']);
        }
        // ensure the json data is a string
        if (data['paymentMethodStatus'] && !(typeof data['paymentMethodStatus'] === 'string' || data['paymentMethodStatus'] instanceof String)) {
            throw new Error("Expected the field `paymentMethodStatus` to be a primitive type in the JSON string but got " + data['paymentMethodStatus']);
        }
        // ensure the json data is a string
        if (data['modifiedOn'] && !(typeof data['modifiedOn'] === 'string' || data['modifiedOn'] instanceof String)) {
            throw new Error("Expected the field `modifiedOn` to be a primitive type in the JSON string but got " + data['modifiedOn']);
        }

        return true;
    }


}



/**
 * @member {module:model/OutboundPaymentTimelineResponseDTOInner.PaymentStatusEnum} paymentStatus
 */
OutboundPaymentTimelineResponseDTOInner.prototype['paymentStatus'] = undefined;

/**
 * @member {module:model/OutboundPaymentTimelineResponseDTOInner.PaymentMethodStatusEnum} paymentMethodStatus
 */
OutboundPaymentTimelineResponseDTOInner.prototype['paymentMethodStatus'] = undefined;

/**
 * @member {String} modifiedOn
 */
OutboundPaymentTimelineResponseDTOInner.prototype['modifiedOn'] = undefined;





/**
 * Allowed values for the <code>paymentStatus</code> property.
 * @enum {String}
 * @readonly
 */
OutboundPaymentTimelineResponseDTOInner['PaymentStatusEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Created"
     * @const
     */
    "Created": "Created",

    /**
     * value: "InProcess"
     * @const
     */
    "InProcess": "InProcess",

    /**
     * value: "Success"
     * @const
     */
    "Success": "Success",

    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled",

    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed",

    /**
     * value: "CancelRequested"
     * @const
     */
    "CancelRequested": "CancelRequested"
};


/**
 * Allowed values for the <code>paymentMethodStatus</code> property.
 * @enum {String}
 * @readonly
 */
OutboundPaymentTimelineResponseDTOInner['PaymentMethodStatusEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Accepted"
     * @const
     */
    "Accepted": "Accepted",

    /**
     * value: "PrintQueued"
     * @const
     */
    "PrintQueued": "PrintQueued",

    /**
     * value: "Printed"
     * @const
     */
    "Printed": "Printed",

    /**
     * value: "Mailed"
     * @const
     */
    "Mailed": "Mailed",

    /**
     * value: "Delivered"
     * @const
     */
    "Delivered": "Delivered",

    /**
     * value: "Pdf"
     * @const
     */
    "Pdf": "Pdf",

    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled",

    /**
     * value: "Warning"
     * @const
     */
    "Warning": "Warning",

    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed",

    /**
     * value: "Returned"
     * @const
     */
    "Returned": "Returned",

    /**
     * value: "Transit"
     * @const
     */
    "Transit": "Transit"
};



export default OutboundPaymentTimelineResponseDTOInner;

