/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentLinkResponsePaymentsInner model module.
 * @module model/PaymentLinkResponsePaymentsInner
 * @version 2.3
 */
class PaymentLinkResponsePaymentsInner {
    /**
     * Constructs a new <code>PaymentLinkResponsePaymentsInner</code>.
     * @alias module:model/PaymentLinkResponsePaymentsInner
     */
    constructor() { 
        
        PaymentLinkResponsePaymentsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentLinkResponsePaymentsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentLinkResponsePaymentsInner} obj Optional instance to populate.
     * @return {module:model/PaymentLinkResponsePaymentsInner} The populated <code>PaymentLinkResponsePaymentsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentLinkResponsePaymentsInner();

            if (data.hasOwnProperty('transactionId')) {
                obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
            }
            if (data.hasOwnProperty('transactionStatus')) {
                obj['transactionStatus'] = ApiClient.convertToType(data['transactionStatus'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('authCode')) {
                obj['authCode'] = ApiClient.convertToType(data['authCode'], 'String');
            }
            if (data.hasOwnProperty('customerId')) {
                obj['customerId'] = ApiClient.convertToType(data['customerId'], 'String');
            }
            if (data.hasOwnProperty('accountToken')) {
                obj['accountToken'] = ApiClient.convertToType(data['accountToken'], 'String');
            }
            if (data.hasOwnProperty('channelType')) {
                obj['channelType'] = ApiClient.convertToType(data['channelType'], 'String');
            }
            if (data.hasOwnProperty('maskedAccount')) {
                obj['maskedAccount'] = ApiClient.convertToType(data['maskedAccount'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentLinkResponsePaymentsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentLinkResponsePaymentsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['transactionId'] && !(typeof data['transactionId'] === 'string' || data['transactionId'] instanceof String)) {
            throw new Error("Expected the field `transactionId` to be a primitive type in the JSON string but got " + data['transactionId']);
        }
        // ensure the json data is a string
        if (data['transactionStatus'] && !(typeof data['transactionStatus'] === 'string' || data['transactionStatus'] instanceof String)) {
            throw new Error("Expected the field `transactionStatus` to be a primitive type in the JSON string but got " + data['transactionStatus']);
        }
        // ensure the json data is a string
        if (data['authCode'] && !(typeof data['authCode'] === 'string' || data['authCode'] instanceof String)) {
            throw new Error("Expected the field `authCode` to be a primitive type in the JSON string but got " + data['authCode']);
        }
        // ensure the json data is a string
        if (data['customerId'] && !(typeof data['customerId'] === 'string' || data['customerId'] instanceof String)) {
            throw new Error("Expected the field `customerId` to be a primitive type in the JSON string but got " + data['customerId']);
        }
        // ensure the json data is a string
        if (data['accountToken'] && !(typeof data['accountToken'] === 'string' || data['accountToken'] instanceof String)) {
            throw new Error("Expected the field `accountToken` to be a primitive type in the JSON string but got " + data['accountToken']);
        }
        // ensure the json data is a string
        if (data['channelType'] && !(typeof data['channelType'] === 'string' || data['channelType'] instanceof String)) {
            throw new Error("Expected the field `channelType` to be a primitive type in the JSON string but got " + data['channelType']);
        }
        // ensure the json data is a string
        if (data['maskedAccount'] && !(typeof data['maskedAccount'] === 'string' || data['maskedAccount'] instanceof String)) {
            throw new Error("Expected the field `maskedAccount` to be a primitive type in the JSON string but got " + data['maskedAccount']);
        }
        // ensure the json data is a string
        if (data['createdOn'] && !(typeof data['createdOn'] === 'string' || data['createdOn'] instanceof String)) {
            throw new Error("Expected the field `createdOn` to be a primitive type in the JSON string but got " + data['createdOn']);
        }

        return true;
    }


}



/**
 * @member {String} transactionId
 */
PaymentLinkResponsePaymentsInner.prototype['transactionId'] = undefined;

/**
 * @member {module:model/PaymentLinkResponsePaymentsInner.TransactionStatusEnum} transactionStatus
 */
PaymentLinkResponsePaymentsInner.prototype['transactionStatus'] = undefined;

/**
 * @member {Number} amount
 */
PaymentLinkResponsePaymentsInner.prototype['amount'] = undefined;

/**
 * @member {String} authCode
 */
PaymentLinkResponsePaymentsInner.prototype['authCode'] = undefined;

/**
 * @member {String} customerId
 */
PaymentLinkResponsePaymentsInner.prototype['customerId'] = undefined;

/**
 * @member {String} accountToken
 */
PaymentLinkResponsePaymentsInner.prototype['accountToken'] = undefined;

/**
 * @member {module:model/PaymentLinkResponsePaymentsInner.ChannelTypeEnum} channelType
 */
PaymentLinkResponsePaymentsInner.prototype['channelType'] = undefined;

/**
 * @member {String} maskedAccount
 */
PaymentLinkResponsePaymentsInner.prototype['maskedAccount'] = undefined;

/**
 * @member {String} createdOn
 */
PaymentLinkResponsePaymentsInner.prototype['createdOn'] = undefined;





/**
 * Allowed values for the <code>transactionStatus</code> property.
 * @enum {String}
 * @readonly
 */
PaymentLinkResponsePaymentsInner['TransactionStatusEnum'] = {

    /**
     * value: "Created"
     * @const
     */
    "Created": "Created",

    /**
     * value: "PendingForAuthorized"
     * @const
     */
    "PendingForAuthorized": "PendingForAuthorized",

    /**
     * value: "Authorized"
     * @const
     */
    "Authorized": "Authorized",

    /**
     * value: "Posted"
     * @const
     */
    "Posted": "Posted",

    /**
     * value: "Captured"
     * @const
     */
    "Captured": "Captured",

    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed",

    /**
     * value: "Returned"
     * @const
     */
    "Returned": "Returned",

    /**
     * value: "Chargeback"
     * @const
     */
    "Chargeback": "Chargeback",

    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled",

    /**
     * value: "Refunded"
     * @const
     */
    "Refunded": "Refunded",

    /**
     * value: "Approved"
     * @const
     */
    "Approved": "Approved",

    /**
     * value: "CancelAttempt"
     * @const
     */
    "CancelAttempt": "CancelAttempt",

    /**
     * value: "RefundAttempt"
     * @const
     */
    "RefundAttempt": "RefundAttempt",

    /**
     * value: "Hold"
     * @const
     */
    "Hold": "Hold",

    /**
     * value: "Denied"
     * @const
     */
    "Denied": "Denied",

    /**
     * value: "SettlementHold"
     * @const
     */
    "SettlementHold": "SettlementHold",

    /**
     * value: "Success"
     * @const
     */
    "Success": "Success",

    /**
     * value: "Retried"
     * @const
     */
    "Retried": "Retried",

    /**
     * value: "ReprocessAttempt"
     * @const
     */
    "ReprocessAttempt": "ReprocessAttempt",

    /**
     * value: "Reprocessed"
     * @const
     */
    "Reprocessed": "Reprocessed",

    /**
     * value: "ChargebackReversed"
     * @const
     */
    "ChargebackReversed": "ChargebackReversed",

    /**
     * value: "RefundedReversed"
     * @const
     */
    "RefundedReversed": "RefundedReversed",

    /**
     * value: "Paid"
     * @const
     */
    "Paid": "Paid",

    /**
     * value: "PaidChargeback"
     * @const
     */
    "PaidChargeback": "PaidChargeback",

    /**
     * value: "PaidChargebackReversed"
     * @const
     */
    "PaidChargebackReversed": "PaidChargebackReversed",

    /**
     * value: "PaidRefunded"
     * @const
     */
    "PaidRefunded": "PaidRefunded",

    /**
     * value: "PaidRefundedReversed"
     * @const
     */
    "PaidRefundedReversed": "PaidRefundedReversed",

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "Unknown"
     * @const
     */
    "Unknown": "Unknown"
};


/**
 * Allowed values for the <code>channelType</code> property.
 * @enum {String}
 * @readonly
 */
PaymentLinkResponsePaymentsInner['ChannelTypeEnum'] = {

    /**
     * value: "ACH"
     * @const
     */
    "ACH": "ACH",

    /**
     * value: "CreditCard"
     * @const
     */
    "CreditCard": "CreditCard",

    /**
     * value: "DebitCard"
     * @const
     */
    "DebitCard": "DebitCard",

    /**
     * value: "RTP"
     * @const
     */
    "RTP": "RTP"
};



export default PaymentLinkResponsePaymentsInner;

