/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DataDto from './DataDto';

/**
 * The PaymentResponseDto model module.
 * @module model/PaymentResponseDto
 * @version 2.3
 */
class PaymentResponseDto {
    /**
     * Constructs a new <code>PaymentResponseDto</code>.
     * @alias module:model/PaymentResponseDto
     */
    constructor() { 
        
        PaymentResponseDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentResponseDto} obj Optional instance to populate.
     * @return {module:model/PaymentResponseDto} The populated <code>PaymentResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentResponseDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('paymentId')) {
                obj['paymentId'] = ApiClient.convertToType(data['paymentId'], 'String');
            }
            if (data.hasOwnProperty('merchantId')) {
                obj['merchantId'] = ApiClient.convertToType(data['merchantId'], 'String');
            }
            if (data.hasOwnProperty('vendorId')) {
                obj['vendorId'] = ApiClient.convertToType(data['vendorId'], 'String');
            }
            if (data.hasOwnProperty('paymentStatus')) {
                obj['paymentStatus'] = ApiClient.convertToType(data['paymentStatus'], 'String');
            }
            if (data.hasOwnProperty('paymentMethodStatus')) {
                obj['paymentMethodStatus'] = ApiClient.convertToType(data['paymentMethodStatus'], 'String');
            }
            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = ApiClient.convertToType(data['paymentMethod'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = DataDto.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('bankAccountDetails')) {
                obj['bankAccountDetails'] = ApiClient.convertToType(data['bankAccountDetails'], 'String');
            }
            if (data.hasOwnProperty('vendorAddress')) {
                obj['vendorAddress'] = ApiClient.convertToType(data['vendorAddress'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentResponseDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentResponseDto</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['paymentId'] && !(typeof data['paymentId'] === 'string' || data['paymentId'] instanceof String)) {
            throw new Error("Expected the field `paymentId` to be a primitive type in the JSON string but got " + data['paymentId']);
        }
        // ensure the json data is a string
        if (data['merchantId'] && !(typeof data['merchantId'] === 'string' || data['merchantId'] instanceof String)) {
            throw new Error("Expected the field `merchantId` to be a primitive type in the JSON string but got " + data['merchantId']);
        }
        // ensure the json data is a string
        if (data['vendorId'] && !(typeof data['vendorId'] === 'string' || data['vendorId'] instanceof String)) {
            throw new Error("Expected the field `vendorId` to be a primitive type in the JSON string but got " + data['vendorId']);
        }
        // ensure the json data is a string
        if (data['paymentStatus'] && !(typeof data['paymentStatus'] === 'string' || data['paymentStatus'] instanceof String)) {
            throw new Error("Expected the field `paymentStatus` to be a primitive type in the JSON string but got " + data['paymentStatus']);
        }
        // ensure the json data is a string
        if (data['paymentMethodStatus'] && !(typeof data['paymentMethodStatus'] === 'string' || data['paymentMethodStatus'] instanceof String)) {
            throw new Error("Expected the field `paymentMethodStatus` to be a primitive type in the JSON string but got " + data['paymentMethodStatus']);
        }
        // ensure the json data is a string
        if (data['paymentMethod'] && !(typeof data['paymentMethod'] === 'string' || data['paymentMethod'] instanceof String)) {
            throw new Error("Expected the field `paymentMethod` to be a primitive type in the JSON string but got " + data['paymentMethod']);
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          DataDto.validateJSON(data['data']);
        }
        // ensure the json data is a string
        if (data['bankAccountDetails'] && !(typeof data['bankAccountDetails'] === 'string' || data['bankAccountDetails'] instanceof String)) {
            throw new Error("Expected the field `bankAccountDetails` to be a primitive type in the JSON string but got " + data['bankAccountDetails']);
        }
        // ensure the json data is a string
        if (data['vendorAddress'] && !(typeof data['vendorAddress'] === 'string' || data['vendorAddress'] instanceof String)) {
            throw new Error("Expected the field `vendorAddress` to be a primitive type in the JSON string but got " + data['vendorAddress']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
PaymentResponseDto.prototype['id'] = undefined;

/**
 * @member {String} paymentId
 */
PaymentResponseDto.prototype['paymentId'] = undefined;

/**
 * @member {String} merchantId
 */
PaymentResponseDto.prototype['merchantId'] = undefined;

/**
 * @member {String} vendorId
 */
PaymentResponseDto.prototype['vendorId'] = undefined;

/**
 * @member {module:model/PaymentResponseDto.PaymentStatusEnum} paymentStatus
 */
PaymentResponseDto.prototype['paymentStatus'] = undefined;

/**
 * @member {module:model/PaymentResponseDto.PaymentMethodStatusEnum} paymentMethodStatus
 */
PaymentResponseDto.prototype['paymentMethodStatus'] = undefined;

/**
 * @member {module:model/PaymentResponseDto.PaymentMethodEnum} paymentMethod
 */
PaymentResponseDto.prototype['paymentMethod'] = undefined;

/**
 * @member {Number} amount
 */
PaymentResponseDto.prototype['amount'] = undefined;

/**
 * @member {module:model/DataDto} data
 */
PaymentResponseDto.prototype['data'] = undefined;

/**
 * JSON-encoded string containing bank account details
 * @member {String} bankAccountDetails
 */
PaymentResponseDto.prototype['bankAccountDetails'] = undefined;

/**
 * JSON-encoded string containing vendor address
 * @member {String} vendorAddress
 */
PaymentResponseDto.prototype['vendorAddress'] = undefined;





/**
 * Allowed values for the <code>paymentStatus</code> property.
 * @enum {String}
 * @readonly
 */
PaymentResponseDto['PaymentStatusEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Created"
     * @const
     */
    "Created": "Created",

    /**
     * value: "InProcess"
     * @const
     */
    "InProcess": "InProcess",

    /**
     * value: "Success"
     * @const
     */
    "Success": "Success",

    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled",

    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed",

    /**
     * value: "CancelRequested"
     * @const
     */
    "CancelRequested": "CancelRequested"
};


/**
 * Allowed values for the <code>paymentMethodStatus</code> property.
 * @enum {String}
 * @readonly
 */
PaymentResponseDto['PaymentMethodStatusEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Accepted"
     * @const
     */
    "Accepted": "Accepted",

    /**
     * value: "PrintQueued"
     * @const
     */
    "PrintQueued": "PrintQueued",

    /**
     * value: "Printed"
     * @const
     */
    "Printed": "Printed",

    /**
     * value: "Mailed"
     * @const
     */
    "Mailed": "Mailed",

    /**
     * value: "Delivered"
     * @const
     */
    "Delivered": "Delivered",

    /**
     * value: "Pdf"
     * @const
     */
    "Pdf": "Pdf",

    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled",

    /**
     * value: "Warning"
     * @const
     */
    "Warning": "Warning",

    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed",

    /**
     * value: "Returned"
     * @const
     */
    "Returned": "Returned",

    /**
     * value: "Transit"
     * @const
     */
    "Transit": "Transit"
};


/**
 * Allowed values for the <code>paymentMethod</code> property.
 * @enum {String}
 * @readonly
 */
PaymentResponseDto['PaymentMethodEnum'] = {

    /**
     * value: "Check"
     * @const
     */
    "Check": "Check"
};



export default PaymentResponseDto;

