/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentLinkResponseLineItemsInner model module.
 * @module model/PaymentLinkResponseLineItemsInner
 * @version 2.3
 */
class PaymentLinkResponseLineItemsInner {
    /**
     * Constructs a new <code>PaymentLinkResponseLineItemsInner</code>.
     * @alias module:model/PaymentLinkResponseLineItemsInner
     */
    constructor() { 
        
        PaymentLinkResponseLineItemsInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentLinkResponseLineItemsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentLinkResponseLineItemsInner} obj Optional instance to populate.
     * @return {module:model/PaymentLinkResponseLineItemsInner} The populated <code>PaymentLinkResponseLineItemsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentLinkResponseLineItemsInner();

            if (data.hasOwnProperty('lineItemType')) {
                obj['lineItemType'] = ApiClient.convertToType(data['lineItemType'], 'String');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('rate')) {
                obj['rate'] = ApiClient.convertToType(data['rate'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentLinkResponseLineItemsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentLinkResponseLineItemsInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['lineItemType'] && !(typeof data['lineItemType'] === 'string' || data['lineItemType'] instanceof String)) {
            throw new Error("Expected the field `lineItemType` to be a primitive type in the JSON string but got " + data['lineItemType']);
        }
        // ensure the json data is a string
        if (data['productId'] && !(typeof data['productId'] === 'string' || data['productId'] instanceof String)) {
            throw new Error("Expected the field `productId` to be a primitive type in the JSON string but got " + data['productId']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * @member {module:model/PaymentLinkResponseLineItemsInner.LineItemTypeEnum} lineItemType
 */
PaymentLinkResponseLineItemsInner.prototype['lineItemType'] = undefined;

/**
 * @member {String} productId
 */
PaymentLinkResponseLineItemsInner.prototype['productId'] = undefined;

/**
 * @member {String} description
 */
PaymentLinkResponseLineItemsInner.prototype['description'] = undefined;

/**
 * @member {Number} quantity
 */
PaymentLinkResponseLineItemsInner.prototype['quantity'] = undefined;

/**
 * @member {Number} rate
 */
PaymentLinkResponseLineItemsInner.prototype['rate'] = undefined;





/**
 * Allowed values for the <code>lineItemType</code> property.
 * @enum {String}
 * @readonly
 */
PaymentLinkResponseLineItemsInner['LineItemTypeEnum'] = {

    /**
     * value: "External"
     * @const
     */
    "External": "External",

    /**
     * value: "Product"
     * @const
     */
    "Product": "Product",

    /**
     * value: "Service"
     * @const
     */
    "Service": "Service"
};



export default PaymentLinkResponseLineItemsInner;

