/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentRequestDtoDataRemittanceData from './PaymentRequestDtoDataRemittanceData';

/**
 * The PaymentRequestDtoData model module.
 * @module model/PaymentRequestDtoData
 * @version 2.3
 */
class PaymentRequestDtoData {
    /**
     * Constructs a new <code>PaymentRequestDtoData</code>.
     * @alias module:model/PaymentRequestDtoData
     */
    constructor() { 
        
        PaymentRequestDtoData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentRequestDtoData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentRequestDtoData} obj Optional instance to populate.
     * @return {module:model/PaymentRequestDtoData} The populated <code>PaymentRequestDtoData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentRequestDtoData();

            if (data.hasOwnProperty('checkNumber')) {
                obj['checkNumber'] = ApiClient.convertToType(data['checkNumber'], 'Number');
            }
            if (data.hasOwnProperty('memo')) {
                obj['memo'] = ApiClient.convertToType(data['memo'], 'String');
            }
            if (data.hasOwnProperty('checkDate')) {
                obj['checkDate'] = ApiClient.convertToType(data['checkDate'], 'String');
            }
            if (data.hasOwnProperty('remittanceData')) {
                obj['remittanceData'] = PaymentRequestDtoDataRemittanceData.constructFromObject(data['remittanceData']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentRequestDtoData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentRequestDtoData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['memo'] && !(typeof data['memo'] === 'string' || data['memo'] instanceof String)) {
            throw new Error("Expected the field `memo` to be a primitive type in the JSON string but got " + data['memo']);
        }
        // ensure the json data is a string
        if (data['checkDate'] && !(typeof data['checkDate'] === 'string' || data['checkDate'] instanceof String)) {
            throw new Error("Expected the field `checkDate` to be a primitive type in the JSON string but got " + data['checkDate']);
        }
        // validate the optional field `remittanceData`
        if (data['remittanceData']) { // data not null
          PaymentRequestDtoDataRemittanceData.validateJSON(data['remittanceData']);
        }

        return true;
    }


}



/**
 * @member {Number} checkNumber
 */
PaymentRequestDtoData.prototype['checkNumber'] = undefined;

/**
 * @member {String} memo
 */
PaymentRequestDtoData.prototype['memo'] = undefined;

/**
 * @member {String} checkDate
 */
PaymentRequestDtoData.prototype['checkDate'] = undefined;

/**
 * @member {module:model/PaymentRequestDtoDataRemittanceData} remittanceData
 */
PaymentRequestDtoData.prototype['remittanceData'] = undefined;






export default PaymentRequestDtoData;

