/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentLinkResponseDisplaySettingsIntent model module.
 * @module model/PaymentLinkResponseDisplaySettingsIntent
 * @version 2.3
 */
class PaymentLinkResponseDisplaySettingsIntent {
    /**
     * Constructs a new <code>PaymentLinkResponseDisplaySettingsIntent</code>.
     * @alias module:model/PaymentLinkResponseDisplaySettingsIntent
     */
    constructor() { 
        
        PaymentLinkResponseDisplaySettingsIntent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentLinkResponseDisplaySettingsIntent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentLinkResponseDisplaySettingsIntent} obj Optional instance to populate.
     * @return {module:model/PaymentLinkResponseDisplaySettingsIntent} The populated <code>PaymentLinkResponseDisplaySettingsIntent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentLinkResponseDisplaySettingsIntent();

            if (data.hasOwnProperty('paymentTypes')) {
                obj['paymentTypes'] = ApiClient.convertToType(data['paymentTypes'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentLinkResponseDisplaySettingsIntent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentLinkResponseDisplaySettingsIntent</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['paymentTypes'])) {
            throw new Error("Expected the field `paymentTypes` to be an array in the JSON data but got " + data['paymentTypes']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/PaymentLinkResponseDisplaySettingsIntent.PaymentTypesEnum>} paymentTypes
 */
PaymentLinkResponseDisplaySettingsIntent.prototype['paymentTypes'] = undefined;





/**
 * Allowed values for the <code>paymentTypes</code> property.
 * @enum {String}
 * @readonly
 */
PaymentLinkResponseDisplaySettingsIntent['PaymentTypesEnum'] = {

    /**
     * value: "ACH"
     * @const
     */
    "ACH": "ACH",

    /**
     * value: "CreditCard"
     * @const
     */
    "CreditCard": "CreditCard",

    /**
     * value: "DebitCard"
     * @const
     */
    "DebitCard": "DebitCard",

    /**
     * value: "RTP"
     * @const
     */
    "RTP": "RTP"
};



export default PaymentLinkResponseDisplaySettingsIntent;

