/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BankDetailDto from './BankDetailDto';
import PaymentRequestDtoData from './PaymentRequestDtoData';

/**
 * The PaymentRequestDto model module.
 * @module model/PaymentRequestDto
 * @version 2.3
 */
class PaymentRequestDto {
    /**
     * Constructs a new <code>PaymentRequestDto</code>.
     * @alias module:model/PaymentRequestDto
     * @param vendorId {String} 
     * @param paymentMethod {module:model/PaymentRequestDto.PaymentMethodEnum} 
     * @param amount {Number} 
     * @param data {module:model/PaymentRequestDtoData} 
     */
    constructor(vendorId, paymentMethod, amount, data) { 
        
        PaymentRequestDto.initialize(this, vendorId, paymentMethod, amount, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, vendorId, paymentMethod, amount, data) { 
        obj['vendorId'] = vendorId;
        obj['paymentMethod'] = paymentMethod;
        obj['amount'] = amount;
        obj['data'] = data;
    }

    /**
     * Constructs a <code>PaymentRequestDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentRequestDto} obj Optional instance to populate.
     * @return {module:model/PaymentRequestDto} The populated <code>PaymentRequestDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentRequestDto();

            if (data.hasOwnProperty('vendorId')) {
                obj['vendorId'] = ApiClient.convertToType(data['vendorId'], 'String');
            }
            if (data.hasOwnProperty('paymentMethod')) {
                obj['paymentMethod'] = ApiClient.convertToType(data['paymentMethod'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('bankDetail')) {
                obj['bankDetail'] = BankDetailDto.constructFromObject(data['bankDetail']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = PaymentRequestDtoData.constructFromObject(data['data']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentRequestDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentRequestDto</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentRequestDto.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['vendorId'] && !(typeof data['vendorId'] === 'string' || data['vendorId'] instanceof String)) {
            throw new Error("Expected the field `vendorId` to be a primitive type in the JSON string but got " + data['vendorId']);
        }
        // ensure the json data is a string
        if (data['paymentMethod'] && !(typeof data['paymentMethod'] === 'string' || data['paymentMethod'] instanceof String)) {
            throw new Error("Expected the field `paymentMethod` to be a primitive type in the JSON string but got " + data['paymentMethod']);
        }
        // validate the optional field `bankDetail`
        if (data['bankDetail']) { // data not null
          BankDetailDto.validateJSON(data['bankDetail']);
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          PaymentRequestDtoData.validateJSON(data['data']);
        }

        return true;
    }


}

PaymentRequestDto.RequiredProperties = ["vendorId", "paymentMethod", "amount", "data"];

/**
 * @member {String} vendorId
 */
PaymentRequestDto.prototype['vendorId'] = undefined;

/**
 * @member {module:model/PaymentRequestDto.PaymentMethodEnum} paymentMethod
 */
PaymentRequestDto.prototype['paymentMethod'] = undefined;

/**
 * @member {Number} amount
 */
PaymentRequestDto.prototype['amount'] = undefined;

/**
 * @member {module:model/BankDetailDto} bankDetail
 */
PaymentRequestDto.prototype['bankDetail'] = undefined;

/**
 * @member {module:model/PaymentRequestDtoData} data
 */
PaymentRequestDto.prototype['data'] = undefined;





/**
 * Allowed values for the <code>paymentMethod</code> property.
 * @enum {String}
 * @readonly
 */
PaymentRequestDto['PaymentMethodEnum'] = {

    /**
     * value: "Check"
     * @const
     */
    "Check": "Check"
};



export default PaymentRequestDto;

