/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaymentLinkResponsePfr model module.
 * @module model/PaymentLinkResponsePfr
 * @version 2.3
 */
class PaymentLinkResponsePfr {
    /**
     * Constructs a new <code>PaymentLinkResponsePfr</code>.
     * @alias module:model/PaymentLinkResponsePfr
     */
    constructor() { 
        
        PaymentLinkResponsePfr.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentLinkResponsePfr</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentLinkResponsePfr} obj Optional instance to populate.
     * @return {module:model/PaymentLinkResponsePfr} The populated <code>PaymentLinkResponsePfr</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentLinkResponsePfr();

            if (data.hasOwnProperty('entity')) {
                obj['entity'] = ApiClient.convertToType(data['entity'], 'String');
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
            if (data.hasOwnProperty('quote')) {
                obj['quote'] = ApiClient.convertToType(data['quote'], 'String');
            }
            if (data.hasOwnProperty('accountNumber')) {
                obj['accountNumber'] = ApiClient.convertToType(data['accountNumber'], 'String');
            }
            if (data.hasOwnProperty('paymentType')) {
                obj['paymentType'] = ApiClient.convertToType(data['paymentType'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentLinkResponsePfr</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentLinkResponsePfr</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['entity'] && !(typeof data['entity'] === 'string' || data['entity'] instanceof String)) {
            throw new Error("Expected the field `entity` to be a primitive type in the JSON string but got " + data['entity']);
        }
        // ensure the json data is a string
        if (data['reference'] && !(typeof data['reference'] === 'string' || data['reference'] instanceof String)) {
            throw new Error("Expected the field `reference` to be a primitive type in the JSON string but got " + data['reference']);
        }
        // ensure the json data is a string
        if (data['quote'] && !(typeof data['quote'] === 'string' || data['quote'] instanceof String)) {
            throw new Error("Expected the field `quote` to be a primitive type in the JSON string but got " + data['quote']);
        }
        // ensure the json data is a string
        if (data['accountNumber'] && !(typeof data['accountNumber'] === 'string' || data['accountNumber'] instanceof String)) {
            throw new Error("Expected the field `accountNumber` to be a primitive type in the JSON string but got " + data['accountNumber']);
        }
        // ensure the json data is a string
        if (data['paymentType'] && !(typeof data['paymentType'] === 'string' || data['paymentType'] instanceof String)) {
            throw new Error("Expected the field `paymentType` to be a primitive type in the JSON string but got " + data['paymentType']);
        }

        return true;
    }


}



/**
 * @member {String} entity
 */
PaymentLinkResponsePfr.prototype['entity'] = undefined;

/**
 * @member {String} reference
 */
PaymentLinkResponsePfr.prototype['reference'] = undefined;

/**
 * @member {String} quote
 */
PaymentLinkResponsePfr.prototype['quote'] = undefined;

/**
 * @member {String} accountNumber
 */
PaymentLinkResponsePfr.prototype['accountNumber'] = undefined;

/**
 * @member {module:model/PaymentLinkResponsePfr.PaymentTypeEnum} paymentType
 */
PaymentLinkResponsePfr.prototype['paymentType'] = undefined;





/**
 * Allowed values for the <code>paymentType</code> property.
 * @enum {String}
 * @readonly
 */
PaymentLinkResponsePfr['PaymentTypeEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "DownPayment"
     * @const
     */
    "DownPayment": "DownPayment",

    /**
     * value: "InstallmentPayment"
     * @const
     */
    "InstallmentPayment": "InstallmentPayment",

    /**
     * value: "FeePayment"
     * @const
     */
    "FeePayment": "FeePayment",

    /**
     * value: "OtherPayment"
     * @const
     */
    "OtherPayment": "OtherPayment"
};



export default PaymentLinkResponsePfr;

