/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentIntentRequestPfr from './PaymentIntentRequestPfr';
import PaymentIntentRequestSplitsInner from './PaymentIntentRequestSplitsInner';
import PaymentLinkResponseCallbackParameters from './PaymentLinkResponseCallbackParameters';
import PaymentLinkResponseCustomersInner from './PaymentLinkResponseCustomersInner';
import PaymentLinkResponseDisplaySettings from './PaymentLinkResponseDisplaySettings';
import PaymentLinkResponseLineItemsInner from './PaymentLinkResponseLineItemsInner';
import PaymentLinkResponsePaymentsInner from './PaymentLinkResponsePaymentsInner';
import PaymentLinkResponseReferenceDataListInner from './PaymentLinkResponseReferenceDataListInner';

/**
 * The PaymentLinkResponse model module.
 * @module model/PaymentLinkResponse
 * @version 2.3
 */
class PaymentLinkResponse {
    /**
     * Constructs a new <code>PaymentLinkResponse</code>.
     * @alias module:model/PaymentLinkResponse
     */
    constructor() { 
        
        PaymentLinkResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaymentLinkResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentLinkResponse} obj Optional instance to populate.
     * @return {module:model/PaymentLinkResponse} The populated <code>PaymentLinkResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentLinkResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('merchantId')) {
                obj['merchantId'] = ApiClient.convertToType(data['merchantId'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('paymentLink')) {
                obj['paymentLink'] = ApiClient.convertToType(data['paymentLink'], 'String');
            }
            if (data.hasOwnProperty('shortLink')) {
                obj['shortLink'] = ApiClient.convertToType(data['shortLink'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('paymentDescription')) {
                obj['paymentDescription'] = ApiClient.convertToType(data['paymentDescription'], 'String');
            }
            if (data.hasOwnProperty('expireIn')) {
                obj['expireIn'] = ApiClient.convertToType(data['expireIn'], 'Number');
            }
            if (data.hasOwnProperty('expireInUnit')) {
                obj['expireInUnit'] = ApiClient.convertToType(data['expireInUnit'], 'String');
            }
            if (data.hasOwnProperty('expireOn')) {
                obj['expireOn'] = ApiClient.convertToType(data['expireOn'], 'String');
            }
            if (data.hasOwnProperty('payments')) {
                obj['payments'] = ApiClient.convertToType(data['payments'], [PaymentLinkResponsePaymentsInner]);
            }
            if (data.hasOwnProperty('noOfPaymentMade')) {
                obj['noOfPaymentMade'] = ApiClient.convertToType(data['noOfPaymentMade'], 'Number');
            }
            if (data.hasOwnProperty('totalPaidAmount')) {
                obj['totalPaidAmount'] = ApiClient.convertToType(data['totalPaidAmount'], 'Number');
            }
            if (data.hasOwnProperty('linkStatus')) {
                obj['linkStatus'] = ApiClient.convertToType(data['linkStatus'], 'String');
            }
            if (data.hasOwnProperty('invoiceNumber')) {
                obj['invoiceNumber'] = ApiClient.convertToType(data['invoiceNumber'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'String');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('modifiedOn')) {
                obj['modifiedOn'] = ApiClient.convertToType(data['modifiedOn'], 'String');
            }
            if (data.hasOwnProperty('modifiedBy')) {
                obj['modifiedBy'] = ApiClient.convertToType(data['modifiedBy'], 'String');
            }
            if (data.hasOwnProperty('shortDescription')) {
                obj['shortDescription'] = ApiClient.convertToType(data['shortDescription'], 'String');
            }
            if (data.hasOwnProperty('responseType')) {
                obj['responseType'] = ApiClient.convertToType(data['responseType'], 'String');
            }
            if (data.hasOwnProperty('callbackParameters')) {
                obj['callbackParameters'] = PaymentLinkResponseCallbackParameters.constructFromObject(data['callbackParameters']);
            }
            if (data.hasOwnProperty('customers')) {
                obj['customers'] = ApiClient.convertToType(data['customers'], [PaymentLinkResponseCustomersInner]);
            }
            if (data.hasOwnProperty('lineItems')) {
                obj['lineItems'] = ApiClient.convertToType(data['lineItems'], [PaymentLinkResponseLineItemsInner]);
            }
            if (data.hasOwnProperty('displaySettings')) {
                obj['displaySettings'] = PaymentLinkResponseDisplaySettings.constructFromObject(data['displaySettings']);
            }
            if (data.hasOwnProperty('splits')) {
                obj['splits'] = ApiClient.convertToType(data['splits'], [PaymentIntentRequestSplitsInner]);
            }
            if (data.hasOwnProperty('saveForFuture')) {
                obj['saveForFuture'] = ApiClient.convertToType(data['saveForFuture'], 'Boolean');
            }
            if (data.hasOwnProperty('quoteKey')) {
                obj['quoteKey'] = ApiClient.convertToType(data['quoteKey'], 'String');
            }
            if (data.hasOwnProperty('accountNumber')) {
                obj['accountNumber'] = ApiClient.convertToType(data['accountNumber'], 'String');
            }
            if (data.hasOwnProperty('referenceType')) {
                obj['referenceType'] = ApiClient.convertToType(data['referenceType'], 'String');
            }
            if (data.hasOwnProperty('referenceNumber')) {
                obj['referenceNumber'] = ApiClient.convertToType(data['referenceNumber'], 'String');
            }
            if (data.hasOwnProperty('referenceKey')) {
                obj['referenceKey'] = ApiClient.convertToType(data['referenceKey'], 'String');
            }
            if (data.hasOwnProperty('referenceDataList')) {
                obj['referenceDataList'] = ApiClient.convertToType(data['referenceDataList'], [PaymentLinkResponseReferenceDataListInner]);
            }
            if (data.hasOwnProperty('enablePremiumFinance')) {
                obj['enablePremiumFinance'] = ApiClient.convertToType(data['enablePremiumFinance'], 'Boolean');
            }
            if (data.hasOwnProperty('isPremiumFinancier')) {
                obj['isPremiumFinancier'] = ApiClient.convertToType(data['isPremiumFinancier'], 'Boolean');
            }
            if (data.hasOwnProperty('pfr')) {
                obj['pfr'] = PaymentIntentRequestPfr.constructFromObject(data['pfr']);
            }
            if (data.hasOwnProperty('paymentLinkType')) {
                obj['paymentLinkType'] = ApiClient.convertToType(data['paymentLinkType'], 'String');
            }
            if (data.hasOwnProperty('suppressTechnologyFee')) {
                obj['suppressTechnologyFee'] = ApiClient.convertToType(data['suppressTechnologyFee'], 'Boolean');
            }
            if (data.hasOwnProperty('overrideTechnologyFee')) {
                obj['overrideTechnologyFee'] = ApiClient.convertToType(data['overrideTechnologyFee'], 'Number');
            }
            if (data.hasOwnProperty('isPFLite')) {
                obj['isPFLite'] = ApiClient.convertToType(data['isPFLite'], 'Boolean');
            }
            if (data.hasOwnProperty('isPayInFull')) {
                obj['isPayInFull'] = ApiClient.convertToType(data['isPayInFull'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentLinkResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentLinkResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['merchantId'] && !(typeof data['merchantId'] === 'string' || data['merchantId'] instanceof String)) {
            throw new Error("Expected the field `merchantId` to be a primitive type in the JSON string but got " + data['merchantId']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['paymentLink'] && !(typeof data['paymentLink'] === 'string' || data['paymentLink'] instanceof String)) {
            throw new Error("Expected the field `paymentLink` to be a primitive type in the JSON string but got " + data['paymentLink']);
        }
        // ensure the json data is a string
        if (data['shortLink'] && !(typeof data['shortLink'] === 'string' || data['shortLink'] instanceof String)) {
            throw new Error("Expected the field `shortLink` to be a primitive type in the JSON string but got " + data['shortLink']);
        }
        // ensure the json data is a string
        if (data['paymentDescription'] && !(typeof data['paymentDescription'] === 'string' || data['paymentDescription'] instanceof String)) {
            throw new Error("Expected the field `paymentDescription` to be a primitive type in the JSON string but got " + data['paymentDescription']);
        }
        // ensure the json data is a string
        if (data['expireInUnit'] && !(typeof data['expireInUnit'] === 'string' || data['expireInUnit'] instanceof String)) {
            throw new Error("Expected the field `expireInUnit` to be a primitive type in the JSON string but got " + data['expireInUnit']);
        }
        // ensure the json data is a string
        if (data['expireOn'] && !(typeof data['expireOn'] === 'string' || data['expireOn'] instanceof String)) {
            throw new Error("Expected the field `expireOn` to be a primitive type in the JSON string but got " + data['expireOn']);
        }
        if (data['payments']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['payments'])) {
                throw new Error("Expected the field `payments` to be an array in the JSON data but got " + data['payments']);
            }
            // validate the optional field `payments` (array)
            for (const item of data['payments']) {
                PaymentLinkResponsePaymentsInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['linkStatus'] && !(typeof data['linkStatus'] === 'string' || data['linkStatus'] instanceof String)) {
            throw new Error("Expected the field `linkStatus` to be a primitive type in the JSON string but got " + data['linkStatus']);
        }
        // ensure the json data is a string
        if (data['invoiceNumber'] && !(typeof data['invoiceNumber'] === 'string' || data['invoiceNumber'] instanceof String)) {
            throw new Error("Expected the field `invoiceNumber` to be a primitive type in the JSON string but got " + data['invoiceNumber']);
        }
        // ensure the json data is a string
        if (data['createdOn'] && !(typeof data['createdOn'] === 'string' || data['createdOn'] instanceof String)) {
            throw new Error("Expected the field `createdOn` to be a primitive type in the JSON string but got " + data['createdOn']);
        }
        // ensure the json data is a string
        if (data['createdBy'] && !(typeof data['createdBy'] === 'string' || data['createdBy'] instanceof String)) {
            throw new Error("Expected the field `createdBy` to be a primitive type in the JSON string but got " + data['createdBy']);
        }
        // ensure the json data is a string
        if (data['modifiedOn'] && !(typeof data['modifiedOn'] === 'string' || data['modifiedOn'] instanceof String)) {
            throw new Error("Expected the field `modifiedOn` to be a primitive type in the JSON string but got " + data['modifiedOn']);
        }
        // ensure the json data is a string
        if (data['modifiedBy'] && !(typeof data['modifiedBy'] === 'string' || data['modifiedBy'] instanceof String)) {
            throw new Error("Expected the field `modifiedBy` to be a primitive type in the JSON string but got " + data['modifiedBy']);
        }
        // ensure the json data is a string
        if (data['shortDescription'] && !(typeof data['shortDescription'] === 'string' || data['shortDescription'] instanceof String)) {
            throw new Error("Expected the field `shortDescription` to be a primitive type in the JSON string but got " + data['shortDescription']);
        }
        // ensure the json data is a string
        if (data['responseType'] && !(typeof data['responseType'] === 'string' || data['responseType'] instanceof String)) {
            throw new Error("Expected the field `responseType` to be a primitive type in the JSON string but got " + data['responseType']);
        }
        // validate the optional field `callbackParameters`
        if (data['callbackParameters']) { // data not null
          PaymentLinkResponseCallbackParameters.validateJSON(data['callbackParameters']);
        }
        if (data['customers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['customers'])) {
                throw new Error("Expected the field `customers` to be an array in the JSON data but got " + data['customers']);
            }
            // validate the optional field `customers` (array)
            for (const item of data['customers']) {
                PaymentLinkResponseCustomersInner.validateJSON(item);
            };
        }
        if (data['lineItems']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['lineItems'])) {
                throw new Error("Expected the field `lineItems` to be an array in the JSON data but got " + data['lineItems']);
            }
            // validate the optional field `lineItems` (array)
            for (const item of data['lineItems']) {
                PaymentLinkResponseLineItemsInner.validateJSON(item);
            };
        }
        // validate the optional field `displaySettings`
        if (data['displaySettings']) { // data not null
          PaymentLinkResponseDisplaySettings.validateJSON(data['displaySettings']);
        }
        if (data['splits']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['splits'])) {
                throw new Error("Expected the field `splits` to be an array in the JSON data but got " + data['splits']);
            }
            // validate the optional field `splits` (array)
            for (const item of data['splits']) {
                PaymentIntentRequestSplitsInner.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['quoteKey'] && !(typeof data['quoteKey'] === 'string' || data['quoteKey'] instanceof String)) {
            throw new Error("Expected the field `quoteKey` to be a primitive type in the JSON string but got " + data['quoteKey']);
        }
        // ensure the json data is a string
        if (data['accountNumber'] && !(typeof data['accountNumber'] === 'string' || data['accountNumber'] instanceof String)) {
            throw new Error("Expected the field `accountNumber` to be a primitive type in the JSON string but got " + data['accountNumber']);
        }
        // ensure the json data is a string
        if (data['referenceType'] && !(typeof data['referenceType'] === 'string' || data['referenceType'] instanceof String)) {
            throw new Error("Expected the field `referenceType` to be a primitive type in the JSON string but got " + data['referenceType']);
        }
        // ensure the json data is a string
        if (data['referenceNumber'] && !(typeof data['referenceNumber'] === 'string' || data['referenceNumber'] instanceof String)) {
            throw new Error("Expected the field `referenceNumber` to be a primitive type in the JSON string but got " + data['referenceNumber']);
        }
        // ensure the json data is a string
        if (data['referenceKey'] && !(typeof data['referenceKey'] === 'string' || data['referenceKey'] instanceof String)) {
            throw new Error("Expected the field `referenceKey` to be a primitive type in the JSON string but got " + data['referenceKey']);
        }
        if (data['referenceDataList']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['referenceDataList'])) {
                throw new Error("Expected the field `referenceDataList` to be an array in the JSON data but got " + data['referenceDataList']);
            }
            // validate the optional field `referenceDataList` (array)
            for (const item of data['referenceDataList']) {
                PaymentLinkResponseReferenceDataListInner.validateJSON(item);
            };
        }
        // validate the optional field `pfr`
        if (data['pfr']) { // data not null
          PaymentIntentRequestPfr.validateJSON(data['pfr']);
        }
        // ensure the json data is a string
        if (data['paymentLinkType'] && !(typeof data['paymentLinkType'] === 'string' || data['paymentLinkType'] instanceof String)) {
            throw new Error("Expected the field `paymentLinkType` to be a primitive type in the JSON string but got " + data['paymentLinkType']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
PaymentLinkResponse.prototype['id'] = undefined;

/**
 * @member {String} merchantId
 */
PaymentLinkResponse.prototype['merchantId'] = undefined;

/**
 * @member {String} title
 */
PaymentLinkResponse.prototype['title'] = undefined;

/**
 * @member {String} paymentLink
 */
PaymentLinkResponse.prototype['paymentLink'] = undefined;

/**
 * @member {String} shortLink
 */
PaymentLinkResponse.prototype['shortLink'] = undefined;

/**
 * @member {Number} amount
 */
PaymentLinkResponse.prototype['amount'] = undefined;

/**
 * @member {String} paymentDescription
 */
PaymentLinkResponse.prototype['paymentDescription'] = undefined;

/**
 * @member {Number} expireIn
 */
PaymentLinkResponse.prototype['expireIn'] = undefined;

/**
 * @member {module:model/PaymentLinkResponse.ExpireInUnitEnum} expireInUnit
 */
PaymentLinkResponse.prototype['expireInUnit'] = undefined;

/**
 * @member {String} expireOn
 */
PaymentLinkResponse.prototype['expireOn'] = undefined;

/**
 * @member {Array.<module:model/PaymentLinkResponsePaymentsInner>} payments
 */
PaymentLinkResponse.prototype['payments'] = undefined;

/**
 * @member {Number} noOfPaymentMade
 */
PaymentLinkResponse.prototype['noOfPaymentMade'] = undefined;

/**
 * @member {Number} totalPaidAmount
 */
PaymentLinkResponse.prototype['totalPaidAmount'] = undefined;

/**
 * @member {module:model/PaymentLinkResponse.LinkStatusEnum} linkStatus
 */
PaymentLinkResponse.prototype['linkStatus'] = undefined;

/**
 * @member {String} invoiceNumber
 */
PaymentLinkResponse.prototype['invoiceNumber'] = undefined;

/**
 * @member {String} createdOn
 */
PaymentLinkResponse.prototype['createdOn'] = undefined;

/**
 * @member {String} createdBy
 */
PaymentLinkResponse.prototype['createdBy'] = undefined;

/**
 * @member {String} modifiedOn
 */
PaymentLinkResponse.prototype['modifiedOn'] = undefined;

/**
 * @member {String} modifiedBy
 */
PaymentLinkResponse.prototype['modifiedBy'] = undefined;

/**
 * @member {String} shortDescription
 */
PaymentLinkResponse.prototype['shortDescription'] = undefined;

/**
 * @member {module:model/PaymentLinkResponse.ResponseTypeEnum} responseType
 */
PaymentLinkResponse.prototype['responseType'] = undefined;

/**
 * @member {module:model/PaymentLinkResponseCallbackParameters} callbackParameters
 */
PaymentLinkResponse.prototype['callbackParameters'] = undefined;

/**
 * @member {Array.<module:model/PaymentLinkResponseCustomersInner>} customers
 */
PaymentLinkResponse.prototype['customers'] = undefined;

/**
 * @member {Array.<module:model/PaymentLinkResponseLineItemsInner>} lineItems
 */
PaymentLinkResponse.prototype['lineItems'] = undefined;

/**
 * @member {module:model/PaymentLinkResponseDisplaySettings} displaySettings
 */
PaymentLinkResponse.prototype['displaySettings'] = undefined;

/**
 * @member {Array.<module:model/PaymentIntentRequestSplitsInner>} splits
 */
PaymentLinkResponse.prototype['splits'] = undefined;

/**
 * @member {Boolean} saveForFuture
 */
PaymentLinkResponse.prototype['saveForFuture'] = undefined;

/**
 * @member {String} quoteKey
 */
PaymentLinkResponse.prototype['quoteKey'] = undefined;

/**
 * @member {String} accountNumber
 */
PaymentLinkResponse.prototype['accountNumber'] = undefined;

/**
 * @member {module:model/PaymentLinkResponse.ReferenceTypeEnum} referenceType
 */
PaymentLinkResponse.prototype['referenceType'] = undefined;

/**
 * @member {String} referenceNumber
 */
PaymentLinkResponse.prototype['referenceNumber'] = undefined;

/**
 * @member {String} referenceKey
 */
PaymentLinkResponse.prototype['referenceKey'] = undefined;

/**
 * @member {Array.<module:model/PaymentLinkResponseReferenceDataListInner>} referenceDataList
 */
PaymentLinkResponse.prototype['referenceDataList'] = undefined;

/**
 * @member {Boolean} enablePremiumFinance
 */
PaymentLinkResponse.prototype['enablePremiumFinance'] = undefined;

/**
 * @member {Boolean} isPremiumFinancier
 */
PaymentLinkResponse.prototype['isPremiumFinancier'] = undefined;

/**
 * @member {module:model/PaymentIntentRequestPfr} pfr
 */
PaymentLinkResponse.prototype['pfr'] = undefined;

/**
 * @member {module:model/PaymentLinkResponse.PaymentLinkTypeEnum} paymentLinkType
 */
PaymentLinkResponse.prototype['paymentLinkType'] = undefined;

/**
 * @member {Boolean} suppressTechnologyFee
 */
PaymentLinkResponse.prototype['suppressTechnologyFee'] = undefined;

/**
 * @member {Number} overrideTechnologyFee
 */
PaymentLinkResponse.prototype['overrideTechnologyFee'] = undefined;

/**
 * @member {Boolean} isPFLite
 */
PaymentLinkResponse.prototype['isPFLite'] = undefined;

/**
 * @member {Boolean} isPayInFull
 */
PaymentLinkResponse.prototype['isPayInFull'] = undefined;





/**
 * Allowed values for the <code>expireInUnit</code> property.
 * @enum {String}
 * @readonly
 */
PaymentLinkResponse['ExpireInUnitEnum'] = {

    /**
     * value: "Seconds"
     * @const
     */
    "Seconds": "Seconds",

    /**
     * value: "Minutes"
     * @const
     */
    "Minutes": "Minutes",

    /**
     * value: "Hours"
     * @const
     */
    "Hours": "Hours",

    /**
     * value: "Days"
     * @const
     */
    "Days": "Days",

    /**
     * value: "Weeks"
     * @const
     */
    "Weeks": "Weeks"
};


/**
 * Allowed values for the <code>linkStatus</code> property.
 * @enum {String}
 * @readonly
 */
PaymentLinkResponse['LinkStatusEnum'] = {

    /**
     * value: "Created"
     * @const
     */
    "Created": "Created",

    /**
     * value: "Enabled"
     * @const
     */
    "Enabled": "Enabled",

    /**
     * value: "Disabled"
     * @const
     */
    "Disabled": "Disabled",

    /**
     * value: "Expired"
     * @const
     */
    "Expired": "Expired",

    /**
     * value: "Paid"
     * @const
     */
    "Paid": "Paid",

    /**
     * value: "PaymentInitiated"
     * @const
     */
    "PaymentInitiated": "PaymentInitiated",

    /**
     * value: "None"
     * @const
     */
    "None": "None"
};


/**
 * Allowed values for the <code>responseType</code> property.
 * @enum {String}
 * @readonly
 */
PaymentLinkResponse['ResponseTypeEnum'] = {

    /**
     * value: "OnScreen"
     * @const
     */
    "OnScreen": "OnScreen",

    /**
     * value: "CallBack"
     * @const
     */
    "CallBack": "CallBack"
};


/**
 * Allowed values for the <code>referenceType</code> property.
 * @enum {String}
 * @readonly
 */
PaymentLinkResponse['ReferenceTypeEnum'] = {

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "QuoteId"
     * @const
     */
    "QuoteId": "QuoteId",

    /**
     * value: "AccountNumber"
     * @const
     */
    "AccountNumber": "AccountNumber",

    /**
     * value: "PolicyNumber"
     * @const
     */
    "PolicyNumber": "PolicyNumber",

    /**
     * value: "InvoiceNumber"
     * @const
     */
    "InvoiceNumber": "InvoiceNumber",

    /**
     * value: "Other"
     * @const
     */
    "Other": "Other"
};


/**
 * Allowed values for the <code>paymentLinkType</code> property.
 * @enum {String}
 * @readonly
 */
PaymentLinkResponse['PaymentLinkTypeEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "PaymentLink"
     * @const
     */
    "PaymentLink": "PaymentLink",

    /**
     * value: "PaymentIntent"
     * @const
     */
    "PaymentIntent": "PaymentIntent",

    /**
     * value: "TokenLink"
     * @const
     */
    "TokenLink": "TokenLink",

    /**
     * value: "Invoice"
     * @const
     */
    "Invoice": "Invoice"
};



export default PaymentLinkResponse;

