/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PFEndorsementRequestQuoteCommunication model module.
 * @module model/PFEndorsementRequestQuoteCommunication
 * @version 2.3
 */
class PFEndorsementRequestQuoteCommunication {
    /**
     * Constructs a new <code>PFEndorsementRequestQuoteCommunication</code>.
     * @alias module:model/PFEndorsementRequestQuoteCommunication
     */
    constructor() { 
        
        PFEndorsementRequestQuoteCommunication.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PFEndorsementRequestQuoteCommunication</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFEndorsementRequestQuoteCommunication} obj Optional instance to populate.
     * @return {module:model/PFEndorsementRequestQuoteCommunication} The populated <code>PFEndorsementRequestQuoteCommunication</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFEndorsementRequestQuoteCommunication();

            if (data.hasOwnProperty('insuredESignCompletionURL')) {
                obj['insuredESignCompletionURL'] = ApiClient.convertToType(data['insuredESignCompletionURL'], 'String');
            }
            if (data.hasOwnProperty('paymentPortalCancelRedirectURL')) {
                obj['paymentPortalCancelRedirectURL'] = ApiClient.convertToType(data['paymentPortalCancelRedirectURL'], 'String');
            }
            if (data.hasOwnProperty('paymentPortalDeclineOfferRedirectURL')) {
                obj['paymentPortalDeclineOfferRedirectURL'] = ApiClient.convertToType(data['paymentPortalDeclineOfferRedirectURL'], 'Boolean');
            }
            if (data.hasOwnProperty('returnInsuredESignURL')) {
                obj['returnInsuredESignURL'] = ApiClient.convertToType(data['returnInsuredESignURL'], 'Boolean');
            }
            if (data.hasOwnProperty('eSignAutoStart')) {
                obj['eSignAutoStart'] = ApiClient.convertToType(data['eSignAutoStart'], 'Boolean');
            }
            if (data.hasOwnProperty('eSignStartPickOptions')) {
                obj['eSignStartPickOptions'] = ApiClient.convertToType(data['eSignStartPickOptions'], 'Boolean');
            }
            if (data.hasOwnProperty('suppressInsuredESignEmail')) {
                obj['suppressInsuredESignEmail'] = ApiClient.convertToType(data['suppressInsuredESignEmail'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDocumentsToUpload')) {
                obj['hasDocumentsToUpload'] = ApiClient.convertToType(data['hasDocumentsToUpload'], 'Boolean');
            }
            if (data.hasOwnProperty('sendEmailToRetailAgent')) {
                obj['sendEmailToRetailAgent'] = ApiClient.convertToType(data['sendEmailToRetailAgent'], 'Boolean');
            }
            if (data.hasOwnProperty('sendWelcomeLetterEmailToInsured')) {
                obj['sendWelcomeLetterEmailToInsured'] = ApiClient.convertToType(data['sendWelcomeLetterEmailToInsured'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFEndorsementRequestQuoteCommunication</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFEndorsementRequestQuoteCommunication</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['insuredESignCompletionURL'] && !(typeof data['insuredESignCompletionURL'] === 'string' || data['insuredESignCompletionURL'] instanceof String)) {
            throw new Error("Expected the field `insuredESignCompletionURL` to be a primitive type in the JSON string but got " + data['insuredESignCompletionURL']);
        }
        // ensure the json data is a string
        if (data['paymentPortalCancelRedirectURL'] && !(typeof data['paymentPortalCancelRedirectURL'] === 'string' || data['paymentPortalCancelRedirectURL'] instanceof String)) {
            throw new Error("Expected the field `paymentPortalCancelRedirectURL` to be a primitive type in the JSON string but got " + data['paymentPortalCancelRedirectURL']);
        }

        return true;
    }


}



/**
 * @member {String} insuredESignCompletionURL
 */
PFEndorsementRequestQuoteCommunication.prototype['insuredESignCompletionURL'] = undefined;

/**
 * @member {String} paymentPortalCancelRedirectURL
 */
PFEndorsementRequestQuoteCommunication.prototype['paymentPortalCancelRedirectURL'] = undefined;

/**
 * @member {Boolean} paymentPortalDeclineOfferRedirectURL
 */
PFEndorsementRequestQuoteCommunication.prototype['paymentPortalDeclineOfferRedirectURL'] = undefined;

/**
 * @member {Boolean} returnInsuredESignURL
 */
PFEndorsementRequestQuoteCommunication.prototype['returnInsuredESignURL'] = undefined;

/**
 * @member {Boolean} eSignAutoStart
 */
PFEndorsementRequestQuoteCommunication.prototype['eSignAutoStart'] = undefined;

/**
 * @member {Boolean} eSignStartPickOptions
 */
PFEndorsementRequestQuoteCommunication.prototype['eSignStartPickOptions'] = undefined;

/**
 * @member {Boolean} suppressInsuredESignEmail
 */
PFEndorsementRequestQuoteCommunication.prototype['suppressInsuredESignEmail'] = undefined;

/**
 * @member {Boolean} hasDocumentsToUpload
 */
PFEndorsementRequestQuoteCommunication.prototype['hasDocumentsToUpload'] = undefined;

/**
 * @member {Boolean} sendEmailToRetailAgent
 */
PFEndorsementRequestQuoteCommunication.prototype['sendEmailToRetailAgent'] = undefined;

/**
 * @member {Boolean} sendWelcomeLetterEmailToInsured
 */
PFEndorsementRequestQuoteCommunication.prototype['sendWelcomeLetterEmailToInsured'] = undefined;






export default PFEndorsementRequestQuoteCommunication;

