/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PFEndorsementResponseItem from './PFEndorsementResponseItem';

/**
 * The PFEndorsementResponse model module.
 * @module model/PFEndorsementResponse
 * @version 2.3
 */
class PFEndorsementResponse {
    /**
     * Constructs a new <code>PFEndorsementResponse</code>.
     * @alias module:model/PFEndorsementResponse
     */
    constructor() { 
        
        PFEndorsementResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PFEndorsementResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFEndorsementResponse} obj Optional instance to populate.
     * @return {module:model/PFEndorsementResponse} The populated <code>PFEndorsementResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFEndorsementResponse();

            if (data.hasOwnProperty('integrationID')) {
                obj['integrationID'] = ApiClient.convertToType(data['integrationID'], 'String');
            }
            if (data.hasOwnProperty('isSuccess')) {
                obj['isSuccess'] = ApiClient.convertToType(data['isSuccess'], 'Boolean');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('item')) {
                obj['item'] = PFEndorsementResponseItem.constructFromObject(data['item']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFEndorsementResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFEndorsementResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['integrationID'] && !(typeof data['integrationID'] === 'string' || data['integrationID'] instanceof String)) {
            throw new Error("Expected the field `integrationID` to be a primitive type in the JSON string but got " + data['integrationID']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // validate the optional field `item`
        if (data['item']) { // data not null
          PFEndorsementResponseItem.validateJSON(data['item']);
        }

        return true;
    }


}



/**
 * @member {String} integrationID
 */
PFEndorsementResponse.prototype['integrationID'] = undefined;

/**
 * @member {Boolean} isSuccess
 */
PFEndorsementResponse.prototype['isSuccess'] = undefined;

/**
 * @member {String} message
 */
PFEndorsementResponse.prototype['message'] = undefined;

/**
 * @member {module:model/PFEndorsementResponseItem} item
 */
PFEndorsementResponse.prototype['item'] = undefined;






export default PFEndorsementResponse;

