/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PFEndorsementRequestQuoteInsuredAddress from './PFEndorsementRequestQuoteInsuredAddress';

/**
 * The PFEndorsementRequestQuoteInsured model module.
 * @module model/PFEndorsementRequestQuoteInsured
 * @version 2.3
 */
class PFEndorsementRequestQuoteInsured {
    /**
     * Constructs a new <code>PFEndorsementRequestQuoteInsured</code>.
     * @alias module:model/PFEndorsementRequestQuoteInsured
     */
    constructor() { 
        
        PFEndorsementRequestQuoteInsured.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PFEndorsementRequestQuoteInsured</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFEndorsementRequestQuoteInsured} obj Optional instance to populate.
     * @return {module:model/PFEndorsementRequestQuoteInsured} The populated <code>PFEndorsementRequestQuoteInsured</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFEndorsementRequestQuoteInsured();

            if (data.hasOwnProperty('agentCustomerNumber')) {
                obj['agentCustomerNumber'] = ApiClient.convertToType(data['agentCustomerNumber'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('careOf')) {
                obj['careOf'] = ApiClient.convertToType(data['careOf'], 'String');
            }
            if (data.hasOwnProperty('uniqueID')) {
                obj['uniqueID'] = ApiClient.convertToType(data['uniqueID'], 'String');
            }
            if (data.hasOwnProperty('mobilePhoneNumber')) {
                obj['mobilePhoneNumber'] = ApiClient.convertToType(data['mobilePhoneNumber'], 'String');
            }
            if (data.hasOwnProperty('isCancellationWarningEnabled')) {
                obj['isCancellationWarningEnabled'] = ApiClient.convertToType(data['isCancellationWarningEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('faxNumber')) {
                obj['faxNumber'] = ApiClient.convertToType(data['faxNumber'], 'String');
            }
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('pfType')) {
                obj['pfType'] = ApiClient.convertToType(data['pfType'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = PFEndorsementRequestQuoteInsuredAddress.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('hasDataChangeAgentCustomerNumber')) {
                obj['hasDataChangeAgentCustomerNumber'] = ApiClient.convertToType(data['hasDataChangeAgentCustomerNumber'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeName')) {
                obj['hasDataChangeName'] = ApiClient.convertToType(data['hasDataChangeName'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeAddress1')) {
                obj['hasDataChangeAddress1'] = ApiClient.convertToType(data['hasDataChangeAddress1'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeAddress2')) {
                obj['hasDataChangeAddress2'] = ApiClient.convertToType(data['hasDataChangeAddress2'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeCity')) {
                obj['hasDataChangeCity'] = ApiClient.convertToType(data['hasDataChangeCity'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeState')) {
                obj['hasDataChangeState'] = ApiClient.convertToType(data['hasDataChangeState'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeZip')) {
                obj['hasDataChangeZip'] = ApiClient.convertToType(data['hasDataChangeZip'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangePhone')) {
                obj['hasDataChangePhone'] = ApiClient.convertToType(data['hasDataChangePhone'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeEmail')) {
                obj['hasDataChangeEmail'] = ApiClient.convertToType(data['hasDataChangeEmail'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeCareOf')) {
                obj['hasDataChangeCareOf'] = ApiClient.convertToType(data['hasDataChangeCareOf'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeInsured')) {
                obj['hasDataChangeInsured'] = ApiClient.convertToType(data['hasDataChangeInsured'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFEndorsementRequestQuoteInsured</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFEndorsementRequestQuoteInsured</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['agentCustomerNumber'] && !(typeof data['agentCustomerNumber'] === 'string' || data['agentCustomerNumber'] instanceof String)) {
            throw new Error("Expected the field `agentCustomerNumber` to be a primitive type in the JSON string but got " + data['agentCustomerNumber']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['careOf'] && !(typeof data['careOf'] === 'string' || data['careOf'] instanceof String)) {
            throw new Error("Expected the field `careOf` to be a primitive type in the JSON string but got " + data['careOf']);
        }
        // ensure the json data is a string
        if (data['uniqueID'] && !(typeof data['uniqueID'] === 'string' || data['uniqueID'] instanceof String)) {
            throw new Error("Expected the field `uniqueID` to be a primitive type in the JSON string but got " + data['uniqueID']);
        }
        // ensure the json data is a string
        if (data['mobilePhoneNumber'] && !(typeof data['mobilePhoneNumber'] === 'string' || data['mobilePhoneNumber'] instanceof String)) {
            throw new Error("Expected the field `mobilePhoneNumber` to be a primitive type in the JSON string but got " + data['mobilePhoneNumber']);
        }
        // ensure the json data is a string
        if (data['faxNumber'] && !(typeof data['faxNumber'] === 'string' || data['faxNumber'] instanceof String)) {
            throw new Error("Expected the field `faxNumber` to be a primitive type in the JSON string but got " + data['faxNumber']);
        }
        // ensure the json data is a string
        if (data['emailAddress'] && !(typeof data['emailAddress'] === 'string' || data['emailAddress'] instanceof String)) {
            throw new Error("Expected the field `emailAddress` to be a primitive type in the JSON string but got " + data['emailAddress']);
        }
        // ensure the json data is a string
        if (data['pfType'] && !(typeof data['pfType'] === 'string' || data['pfType'] instanceof String)) {
            throw new Error("Expected the field `pfType` to be a primitive type in the JSON string but got " + data['pfType']);
        }
        // validate the optional field `address`
        if (data['address']) { // data not null
          PFEndorsementRequestQuoteInsuredAddress.validateJSON(data['address']);
        }

        return true;
    }


}



/**
 * This denotes the Agent Customer Number.
 * @member {String} agentCustomerNumber
 */
PFEndorsementRequestQuoteInsured.prototype['agentCustomerNumber'] = undefined;

/**
 * This denotes the email.
 * @member {String} email
 */
PFEndorsementRequestQuoteInsured.prototype['email'] = undefined;

/**
 * This denotes the care of.
 * @member {String} careOf
 */
PFEndorsementRequestQuoteInsured.prototype['careOf'] = undefined;

/**
 * This denotes a unique identifier for the insured.
 * @member {String} uniqueID
 */
PFEndorsementRequestQuoteInsured.prototype['uniqueID'] = undefined;

/**
 * This denotes the mobile phone number.
 * @member {String} mobilePhoneNumber
 */
PFEndorsementRequestQuoteInsured.prototype['mobilePhoneNumber'] = undefined;

/**
 * Indicates if cancellation warnings are enabled.
 * @member {Boolean} isCancellationWarningEnabled
 */
PFEndorsementRequestQuoteInsured.prototype['isCancellationWarningEnabled'] = undefined;

/**
 * This denotes the fax number.
 * @member {String} faxNumber
 */
PFEndorsementRequestQuoteInsured.prototype['faxNumber'] = undefined;

/**
 * This denotes an alternate email address.
 * @member {String} emailAddress
 */
PFEndorsementRequestQuoteInsured.prototype['emailAddress'] = undefined;

/**
 * This denotes the PFType (enum or string depending on your definition).
 * @member {module:model/PFEndorsementRequestQuoteInsured.PfTypeEnum} pfType
 */
PFEndorsementRequestQuoteInsured.prototype['pfType'] = undefined;

/**
 * @member {module:model/PFEndorsementRequestQuoteInsuredAddress} address
 */
PFEndorsementRequestQuoteInsured.prototype['address'] = undefined;

/**
 * @member {Boolean} hasDataChangeAgentCustomerNumber
 */
PFEndorsementRequestQuoteInsured.prototype['hasDataChangeAgentCustomerNumber'] = undefined;

/**
 * @member {Boolean} hasDataChangeName
 */
PFEndorsementRequestQuoteInsured.prototype['hasDataChangeName'] = undefined;

/**
 * @member {Boolean} hasDataChangeAddress1
 */
PFEndorsementRequestQuoteInsured.prototype['hasDataChangeAddress1'] = undefined;

/**
 * @member {Boolean} hasDataChangeAddress2
 */
PFEndorsementRequestQuoteInsured.prototype['hasDataChangeAddress2'] = undefined;

/**
 * @member {Boolean} hasDataChangeCity
 */
PFEndorsementRequestQuoteInsured.prototype['hasDataChangeCity'] = undefined;

/**
 * @member {Boolean} hasDataChangeState
 */
PFEndorsementRequestQuoteInsured.prototype['hasDataChangeState'] = undefined;

/**
 * @member {Boolean} hasDataChangeZip
 */
PFEndorsementRequestQuoteInsured.prototype['hasDataChangeZip'] = undefined;

/**
 * @member {Boolean} hasDataChangePhone
 */
PFEndorsementRequestQuoteInsured.prototype['hasDataChangePhone'] = undefined;

/**
 * @member {Boolean} hasDataChangeEmail
 */
PFEndorsementRequestQuoteInsured.prototype['hasDataChangeEmail'] = undefined;

/**
 * @member {Boolean} hasDataChangeCareOf
 */
PFEndorsementRequestQuoteInsured.prototype['hasDataChangeCareOf'] = undefined;

/**
 * @member {Boolean} hasDataChangeInsured
 */
PFEndorsementRequestQuoteInsured.prototype['hasDataChangeInsured'] = undefined;





/**
 * Allowed values for the <code>pfType</code> property.
 * @enum {String}
 * @readonly
 */
PFEndorsementRequestQuoteInsured['PfTypeEnum'] = {

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "EPF"
     * @const
     */
    "EPF": "EPF",

    /**
     * value: "PFLite"
     * @const
     */
    "PFLite": "PFLite"
};



export default PFEndorsementRequestQuoteInsured;

