/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PFEndorsementRequestQuote from './PFEndorsementRequestQuote';

/**
 * The PFEndorsementRequest model module.
 * @module model/PFEndorsementRequest
 * @version 2.3
 */
class PFEndorsementRequest {
    /**
     * Constructs a new <code>PFEndorsementRequest</code>.
     * @alias module:model/PFEndorsementRequest
     * @param quote {module:model/PFEndorsementRequestQuote} 
     */
    constructor(quote) { 
        
        PFEndorsementRequest.initialize(this, quote);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, quote) { 
        obj['quote'] = quote;
    }

    /**
     * Constructs a <code>PFEndorsementRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFEndorsementRequest} obj Optional instance to populate.
     * @return {module:model/PFEndorsementRequest} The populated <code>PFEndorsementRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFEndorsementRequest();

            if (data.hasOwnProperty('quote')) {
                obj['quote'] = PFEndorsementRequestQuote.constructFromObject(data['quote']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFEndorsementRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFEndorsementRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PFEndorsementRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `quote`
        if (data['quote']) { // data not null
          PFEndorsementRequestQuote.validateJSON(data['quote']);
        }

        return true;
    }


}

PFEndorsementRequest.RequiredProperties = ["quote"];

/**
 * @member {module:model/PFEndorsementRequestQuote} quote
 */
PFEndorsementRequest.prototype['quote'] = undefined;






export default PFEndorsementRequest;

