/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PFEndorsementRequestQuoteDetailsRecurringACH model module.
 * @module model/PFEndorsementRequestQuoteDetailsRecurringACH
 * @version 2.3
 */
class PFEndorsementRequestQuoteDetailsRecurringACH {
    /**
     * Constructs a new <code>PFEndorsementRequestQuoteDetailsRecurringACH</code>.
     * @alias module:model/PFEndorsementRequestQuoteDetailsRecurringACH
     */
    constructor() { 
        
        PFEndorsementRequestQuoteDetailsRecurringACH.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PFEndorsementRequestQuoteDetailsRecurringACH</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFEndorsementRequestQuoteDetailsRecurringACH} obj Optional instance to populate.
     * @return {module:model/PFEndorsementRequestQuoteDetailsRecurringACH} The populated <code>PFEndorsementRequestQuoteDetailsRecurringACH</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFEndorsementRequestQuoteDetailsRecurringACH();

            if (data.hasOwnProperty('EnrollRecurringAch')) {
                obj['EnrollRecurringAch'] = ApiClient.convertToType(data['EnrollRecurringAch'], 'Boolean');
            }
            if (data.hasOwnProperty('BankRoutingNumber')) {
                obj['BankRoutingNumber'] = ApiClient.convertToType(data['BankRoutingNumber'], 'String');
            }
            if (data.hasOwnProperty('BankAcctNumber')) {
                obj['BankAcctNumber'] = ApiClient.convertToType(data['BankAcctNumber'], 'String');
            }
            if (data.hasOwnProperty('IsCheckingAccount')) {
                obj['IsCheckingAccount'] = ApiClient.convertToType(data['IsCheckingAccount'], 'Boolean');
            }
            if (data.hasOwnProperty('AchDisclosure')) {
                obj['AchDisclosure'] = ApiClient.convertToType(data['AchDisclosure'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFEndorsementRequestQuoteDetailsRecurringACH</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFEndorsementRequestQuoteDetailsRecurringACH</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['BankRoutingNumber'] && !(typeof data['BankRoutingNumber'] === 'string' || data['BankRoutingNumber'] instanceof String)) {
            throw new Error("Expected the field `BankRoutingNumber` to be a primitive type in the JSON string but got " + data['BankRoutingNumber']);
        }
        // ensure the json data is a string
        if (data['BankAcctNumber'] && !(typeof data['BankAcctNumber'] === 'string' || data['BankAcctNumber'] instanceof String)) {
            throw new Error("Expected the field `BankAcctNumber` to be a primitive type in the JSON string but got " + data['BankAcctNumber']);
        }
        // ensure the json data is a string
        if (data['AchDisclosure'] && !(typeof data['AchDisclosure'] === 'string' || data['AchDisclosure'] instanceof String)) {
            throw new Error("Expected the field `AchDisclosure` to be a primitive type in the JSON string but got " + data['AchDisclosure']);
        }

        return true;
    }


}



/**
 * @member {Boolean} EnrollRecurringAch
 */
PFEndorsementRequestQuoteDetailsRecurringACH.prototype['EnrollRecurringAch'] = undefined;

/**
 * @member {String} BankRoutingNumber
 */
PFEndorsementRequestQuoteDetailsRecurringACH.prototype['BankRoutingNumber'] = undefined;

/**
 * @member {String} BankAcctNumber
 */
PFEndorsementRequestQuoteDetailsRecurringACH.prototype['BankAcctNumber'] = undefined;

/**
 * @member {Boolean} IsCheckingAccount
 */
PFEndorsementRequestQuoteDetailsRecurringACH.prototype['IsCheckingAccount'] = undefined;

/**
 * @member {String} AchDisclosure
 */
PFEndorsementRequestQuoteDetailsRecurringACH.prototype['AchDisclosure'] = undefined;






export default PFEndorsementRequestQuoteDetailsRecurringACH;

