/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PFEndorsementResponseItemQuoteESignResult model module.
 * @module model/PFEndorsementResponseItemQuoteESignResult
 * @version 2.3
 */
class PFEndorsementResponseItemQuoteESignResult {
    /**
     * Constructs a new <code>PFEndorsementResponseItemQuoteESignResult</code>.
     * @alias module:model/PFEndorsementResponseItemQuoteESignResult
     */
    constructor() { 
        
        PFEndorsementResponseItemQuoteESignResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PFEndorsementResponseItemQuoteESignResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFEndorsementResponseItemQuoteESignResult} obj Optional instance to populate.
     * @return {module:model/PFEndorsementResponseItemQuoteESignResult} The populated <code>PFEndorsementResponseItemQuoteESignResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFEndorsementResponseItemQuoteESignResult();

            if (data.hasOwnProperty('processed')) {
                obj['processed'] = ApiClient.convertToType(data['processed'], 'Boolean');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('batchID')) {
                obj['batchID'] = ApiClient.convertToType(data['batchID'], 'String');
            }
            if (data.hasOwnProperty('agentURL')) {
                obj['agentURL'] = ApiClient.convertToType(data['agentURL'], 'String');
            }
            if (data.hasOwnProperty('insuredURL')) {
                obj['insuredURL'] = ApiClient.convertToType(data['insuredURL'], 'String');
            }
            if (data.hasOwnProperty('eSignOption')) {
                obj['eSignOption'] = ApiClient.convertToType(data['eSignOption'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFEndorsementResponseItemQuoteESignResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFEndorsementResponseItemQuoteESignResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['batchID'] && !(typeof data['batchID'] === 'string' || data['batchID'] instanceof String)) {
            throw new Error("Expected the field `batchID` to be a primitive type in the JSON string but got " + data['batchID']);
        }
        // ensure the json data is a string
        if (data['agentURL'] && !(typeof data['agentURL'] === 'string' || data['agentURL'] instanceof String)) {
            throw new Error("Expected the field `agentURL` to be a primitive type in the JSON string but got " + data['agentURL']);
        }
        // ensure the json data is a string
        if (data['insuredURL'] && !(typeof data['insuredURL'] === 'string' || data['insuredURL'] instanceof String)) {
            throw new Error("Expected the field `insuredURL` to be a primitive type in the JSON string but got " + data['insuredURL']);
        }

        return true;
    }


}



/**
 * @member {Boolean} processed
 */
PFEndorsementResponseItemQuoteESignResult.prototype['processed'] = undefined;

/**
 * @member {String} message
 */
PFEndorsementResponseItemQuoteESignResult.prototype['message'] = undefined;

/**
 * @member {String} batchID
 */
PFEndorsementResponseItemQuoteESignResult.prototype['batchID'] = undefined;

/**
 * @member {String} agentURL
 */
PFEndorsementResponseItemQuoteESignResult.prototype['agentURL'] = undefined;

/**
 * @member {String} insuredURL
 */
PFEndorsementResponseItemQuoteESignResult.prototype['insuredURL'] = undefined;

/**
 * @member {Number} eSignOption
 */
PFEndorsementResponseItemQuoteESignResult.prototype['eSignOption'] = undefined;






export default PFEndorsementResponseItemQuoteESignResult;

