/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PFEndorsementResponseItemPaymentIntentIntent from './PFEndorsementResponseItemPaymentIntentIntent';

/**
 * The PFEndorsementResponseItemPaymentIntent model module.
 * @module model/PFEndorsementResponseItemPaymentIntent
 * @version 2.3
 */
class PFEndorsementResponseItemPaymentIntent {
    /**
     * Constructs a new <code>PFEndorsementResponseItemPaymentIntent</code>.
     * @alias module:model/PFEndorsementResponseItemPaymentIntent
     */
    constructor() { 
        
        PFEndorsementResponseItemPaymentIntent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PFEndorsementResponseItemPaymentIntent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFEndorsementResponseItemPaymentIntent} obj Optional instance to populate.
     * @return {module:model/PFEndorsementResponseItemPaymentIntent} The populated <code>PFEndorsementResponseItemPaymentIntent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFEndorsementResponseItemPaymentIntent();

            if (data.hasOwnProperty('paymentToken')) {
                obj['paymentToken'] = ApiClient.convertToType(data['paymentToken'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('invoiceNumber')) {
                obj['invoiceNumber'] = ApiClient.convertToType(data['invoiceNumber'], 'String');
            }
            if (data.hasOwnProperty('expireOn')) {
                obj['expireOn'] = ApiClient.convertToType(data['expireOn'], 'String');
            }
            if (data.hasOwnProperty('shortDescription')) {
                obj['shortDescription'] = ApiClient.convertToType(data['shortDescription'], 'String');
            }
            if (data.hasOwnProperty('paymentDescription')) {
                obj['paymentDescription'] = ApiClient.convertToType(data['paymentDescription'], 'String');
            }
            if (data.hasOwnProperty('intent')) {
                obj['intent'] = PFEndorsementResponseItemPaymentIntentIntent.constructFromObject(data['intent']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFEndorsementResponseItemPaymentIntent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFEndorsementResponseItemPaymentIntent</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['paymentToken'] && !(typeof data['paymentToken'] === 'string' || data['paymentToken'] instanceof String)) {
            throw new Error("Expected the field `paymentToken` to be a primitive type in the JSON string but got " + data['paymentToken']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['invoiceNumber'] && !(typeof data['invoiceNumber'] === 'string' || data['invoiceNumber'] instanceof String)) {
            throw new Error("Expected the field `invoiceNumber` to be a primitive type in the JSON string but got " + data['invoiceNumber']);
        }
        // ensure the json data is a string
        if (data['expireOn'] && !(typeof data['expireOn'] === 'string' || data['expireOn'] instanceof String)) {
            throw new Error("Expected the field `expireOn` to be a primitive type in the JSON string but got " + data['expireOn']);
        }
        // ensure the json data is a string
        if (data['shortDescription'] && !(typeof data['shortDescription'] === 'string' || data['shortDescription'] instanceof String)) {
            throw new Error("Expected the field `shortDescription` to be a primitive type in the JSON string but got " + data['shortDescription']);
        }
        // ensure the json data is a string
        if (data['paymentDescription'] && !(typeof data['paymentDescription'] === 'string' || data['paymentDescription'] instanceof String)) {
            throw new Error("Expected the field `paymentDescription` to be a primitive type in the JSON string but got " + data['paymentDescription']);
        }
        // validate the optional field `intent`
        if (data['intent']) { // data not null
          PFEndorsementResponseItemPaymentIntentIntent.validateJSON(data['intent']);
        }

        return true;
    }


}



/**
 * @member {String} paymentToken
 */
PFEndorsementResponseItemPaymentIntent.prototype['paymentToken'] = undefined;

/**
 * @member {String} title
 */
PFEndorsementResponseItemPaymentIntent.prototype['title'] = undefined;

/**
 * @member {Number} amount
 */
PFEndorsementResponseItemPaymentIntent.prototype['amount'] = undefined;

/**
 * @member {String} invoiceNumber
 */
PFEndorsementResponseItemPaymentIntent.prototype['invoiceNumber'] = undefined;

/**
 * @member {String} expireOn
 */
PFEndorsementResponseItemPaymentIntent.prototype['expireOn'] = undefined;

/**
 * @member {String} shortDescription
 */
PFEndorsementResponseItemPaymentIntent.prototype['shortDescription'] = undefined;

/**
 * @member {String} paymentDescription
 */
PFEndorsementResponseItemPaymentIntent.prototype['paymentDescription'] = undefined;

/**
 * @member {module:model/PFEndorsementResponseItemPaymentIntentIntent} intent
 */
PFEndorsementResponseItemPaymentIntent.prototype['intent'] = undefined;






export default PFEndorsementResponseItemPaymentIntent;

