/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PFEndorsementRequestQuoteCommunication from './PFEndorsementRequestQuoteCommunication';
import PFEndorsementRequestQuoteDetails from './PFEndorsementRequestQuoteDetails';
import PFEndorsementRequestQuoteInsured from './PFEndorsementRequestQuoteInsured';
import PFEndorsementRequestQuotePoliciesInner from './PFEndorsementRequestQuotePoliciesInner';
import PFLiteSecureQuoteRequestAgent from './PFLiteSecureQuoteRequestAgent';

/**
 * The PFEndorsementRequestQuote model module.
 * @module model/PFEndorsementRequestQuote
 * @version 2.3
 */
class PFEndorsementRequestQuote {
    /**
     * Constructs a new <code>PFEndorsementRequestQuote</code>.
     * @alias module:model/PFEndorsementRequestQuote
     * @param agreementId {Number} This denotes the agreementId received in check endorsement API.
     * @param merchantReference {String} 
     * @param policies {Array.<module:model/PFEndorsementRequestQuotePoliciesInner>} 
     */
    constructor(agreementId, merchantReference, policies) { 
        
        PFEndorsementRequestQuote.initialize(this, agreementId, merchantReference, policies);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, agreementId, merchantReference, policies) { 
        obj['agreementId'] = agreementId;
        obj['merchantReference'] = merchantReference;
        obj['policies'] = policies;
    }

    /**
     * Constructs a <code>PFEndorsementRequestQuote</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFEndorsementRequestQuote} obj Optional instance to populate.
     * @return {module:model/PFEndorsementRequestQuote} The populated <code>PFEndorsementRequestQuote</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFEndorsementRequestQuote();

            if (data.hasOwnProperty('accountNumber')) {
                obj['accountNumber'] = ApiClient.convertToType(data['accountNumber'], 'String');
            }
            if (data.hasOwnProperty('agreementId')) {
                obj['agreementId'] = ApiClient.convertToType(data['agreementId'], 'Number');
            }
            if (data.hasOwnProperty('merchantReference')) {
                obj['merchantReference'] = ApiClient.convertToType(data['merchantReference'], 'String');
            }
            if (data.hasOwnProperty('policies')) {
                obj['policies'] = ApiClient.convertToType(data['policies'], [PFEndorsementRequestQuotePoliciesInner]);
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = PFEndorsementRequestQuoteDetails.constructFromObject(data['details']);
            }
            if (data.hasOwnProperty('insured')) {
                obj['insured'] = PFEndorsementRequestQuoteInsured.constructFromObject(data['insured']);
            }
            if (data.hasOwnProperty('agent')) {
                obj['agent'] = PFLiteSecureQuoteRequestAgent.constructFromObject(data['agent']);
            }
            if (data.hasOwnProperty('communication')) {
                obj['communication'] = PFEndorsementRequestQuoteCommunication.constructFromObject(data['communication']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFEndorsementRequestQuote</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFEndorsementRequestQuote</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PFEndorsementRequestQuote.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['accountNumber'] && !(typeof data['accountNumber'] === 'string' || data['accountNumber'] instanceof String)) {
            throw new Error("Expected the field `accountNumber` to be a primitive type in the JSON string but got " + data['accountNumber']);
        }
        // ensure the json data is a string
        if (data['merchantReference'] && !(typeof data['merchantReference'] === 'string' || data['merchantReference'] instanceof String)) {
            throw new Error("Expected the field `merchantReference` to be a primitive type in the JSON string but got " + data['merchantReference']);
        }
        if (data['policies']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['policies'])) {
                throw new Error("Expected the field `policies` to be an array in the JSON data but got " + data['policies']);
            }
            // validate the optional field `policies` (array)
            for (const item of data['policies']) {
                PFEndorsementRequestQuotePoliciesInner.validateJSON(item);
            };
        }
        // validate the optional field `details`
        if (data['details']) { // data not null
          PFEndorsementRequestQuoteDetails.validateJSON(data['details']);
        }
        // validate the optional field `insured`
        if (data['insured']) { // data not null
          PFEndorsementRequestQuoteInsured.validateJSON(data['insured']);
        }
        // validate the optional field `agent`
        if (data['agent']) { // data not null
          PFLiteSecureQuoteRequestAgent.validateJSON(data['agent']);
        }
        // validate the optional field `communication`
        if (data['communication']) { // data not null
          PFEndorsementRequestQuoteCommunication.validateJSON(data['communication']);
        }

        return true;
    }


}

PFEndorsementRequestQuote.RequiredProperties = ["agreementId", "merchantReference", "policies"];

/**
 * @member {String} accountNumber
 */
PFEndorsementRequestQuote.prototype['accountNumber'] = undefined;

/**
 * This denotes the agreementId received in check endorsement API.
 * @member {Number} agreementId
 */
PFEndorsementRequestQuote.prototype['agreementId'] = undefined;

/**
 * @member {String} merchantReference
 */
PFEndorsementRequestQuote.prototype['merchantReference'] = undefined;

/**
 * @member {Array.<module:model/PFEndorsementRequestQuotePoliciesInner>} policies
 */
PFEndorsementRequestQuote.prototype['policies'] = undefined;

/**
 * @member {module:model/PFEndorsementRequestQuoteDetails} details
 */
PFEndorsementRequestQuote.prototype['details'] = undefined;

/**
 * @member {module:model/PFEndorsementRequestQuoteInsured} insured
 */
PFEndorsementRequestQuote.prototype['insured'] = undefined;

/**
 * @member {module:model/PFLiteSecureQuoteRequestAgent} agent
 */
PFEndorsementRequestQuote.prototype['agent'] = undefined;

/**
 * @member {module:model/PFEndorsementRequestQuoteCommunication} communication
 */
PFEndorsementRequestQuote.prototype['communication'] = undefined;






export default PFEndorsementRequestQuote;

