/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentLinkRequestSettingsIntent from './PaymentLinkRequestSettingsIntent';

/**
 * The PFLitePaymentLinkRequestSettings model module.
 * @module model/PFLitePaymentLinkRequestSettings
 * @version 2.3
 */
class PFLitePaymentLinkRequestSettings {
    /**
     * Constructs a new <code>PFLitePaymentLinkRequestSettings</code>.
     * @alias module:model/PFLitePaymentLinkRequestSettings
     * @param selectedCustomerFields {String} 
     * @param additionalDetailsPreference {module:model/PFLitePaymentLinkRequestSettings.AdditionalDetailsPreferenceEnum} 
     * @param intent {module:model/PaymentLinkRequestSettingsIntent} 
     */
    constructor(selectedCustomerFields, additionalDetailsPreference, intent) { 
        
        PFLitePaymentLinkRequestSettings.initialize(this, selectedCustomerFields, additionalDetailsPreference, intent);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, selectedCustomerFields, additionalDetailsPreference, intent) { 
        obj['selectedCustomerFields'] = selectedCustomerFields;
        obj['additionalDetailsPreference'] = additionalDetailsPreference;
        obj['intent'] = intent;
    }

    /**
     * Constructs a <code>PFLitePaymentLinkRequestSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFLitePaymentLinkRequestSettings} obj Optional instance to populate.
     * @return {module:model/PFLitePaymentLinkRequestSettings} The populated <code>PFLitePaymentLinkRequestSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFLitePaymentLinkRequestSettings();

            if (data.hasOwnProperty('selectedCustomerFields')) {
                obj['selectedCustomerFields'] = ApiClient.convertToType(data['selectedCustomerFields'], 'String');
            }
            if (data.hasOwnProperty('additionalDetailsPreference')) {
                obj['additionalDetailsPreference'] = ApiClient.convertToType(data['additionalDetailsPreference'], 'String');
            }
            if (data.hasOwnProperty('displaySummary')) {
                obj['displaySummary'] = ApiClient.convertToType(data['displaySummary'], 'Boolean');
            }
            if (data.hasOwnProperty('acceptCustomerInfo')) {
                obj['acceptCustomerInfo'] = ApiClient.convertToType(data['acceptCustomerInfo'], 'Boolean');
            }
            if (data.hasOwnProperty('removeHeader')) {
                obj['removeHeader'] = ApiClient.convertToType(data['removeHeader'], 'Boolean');
            }
            if (data.hasOwnProperty('acceptCard')) {
                obj['acceptCard'] = ApiClient.convertToType(data['acceptCard'], 'Boolean');
            }
            if (data.hasOwnProperty('acceptBankAccount')) {
                obj['acceptBankAccount'] = ApiClient.convertToType(data['acceptBankAccount'], 'Boolean');
            }
            if (data.hasOwnProperty('saveCustomer')) {
                obj['saveCustomer'] = ApiClient.convertToType(data['saveCustomer'], 'Boolean');
            }
            if (data.hasOwnProperty('saveCustomerAccount')) {
                obj['saveCustomerAccount'] = ApiClient.convertToType(data['saveCustomerAccount'], 'Boolean');
            }
            if (data.hasOwnProperty('intent')) {
                obj['intent'] = PaymentLinkRequestSettingsIntent.constructFromObject(data['intent']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFLitePaymentLinkRequestSettings</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFLitePaymentLinkRequestSettings</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PFLitePaymentLinkRequestSettings.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['selectedCustomerFields'] && !(typeof data['selectedCustomerFields'] === 'string' || data['selectedCustomerFields'] instanceof String)) {
            throw new Error("Expected the field `selectedCustomerFields` to be a primitive type in the JSON string but got " + data['selectedCustomerFields']);
        }
        // ensure the json data is a string
        if (data['additionalDetailsPreference'] && !(typeof data['additionalDetailsPreference'] === 'string' || data['additionalDetailsPreference'] instanceof String)) {
            throw new Error("Expected the field `additionalDetailsPreference` to be a primitive type in the JSON string but got " + data['additionalDetailsPreference']);
        }
        // validate the optional field `intent`
        if (data['intent']) { // data not null
          PaymentLinkRequestSettingsIntent.validateJSON(data['intent']);
        }

        return true;
    }


}

PFLitePaymentLinkRequestSettings.RequiredProperties = ["selectedCustomerFields", "additionalDetailsPreference", "intent"];

/**
 * @member {String} selectedCustomerFields
 */
PFLitePaymentLinkRequestSettings.prototype['selectedCustomerFields'] = undefined;

/**
 * @member {module:model/PFLitePaymentLinkRequestSettings.AdditionalDetailsPreferenceEnum} additionalDetailsPreference
 */
PFLitePaymentLinkRequestSettings.prototype['additionalDetailsPreference'] = undefined;

/**
 * @member {Boolean} displaySummary
 */
PFLitePaymentLinkRequestSettings.prototype['displaySummary'] = undefined;

/**
 * @member {Boolean} acceptCustomerInfo
 */
PFLitePaymentLinkRequestSettings.prototype['acceptCustomerInfo'] = undefined;

/**
 * @member {Boolean} removeHeader
 */
PFLitePaymentLinkRequestSettings.prototype['removeHeader'] = undefined;

/**
 * @member {Boolean} acceptCard
 */
PFLitePaymentLinkRequestSettings.prototype['acceptCard'] = undefined;

/**
 * @member {Boolean} acceptBankAccount
 */
PFLitePaymentLinkRequestSettings.prototype['acceptBankAccount'] = undefined;

/**
 * @member {Boolean} saveCustomer
 */
PFLitePaymentLinkRequestSettings.prototype['saveCustomer'] = undefined;

/**
 * @member {Boolean} saveCustomerAccount
 */
PFLitePaymentLinkRequestSettings.prototype['saveCustomerAccount'] = undefined;

/**
 * @member {module:model/PaymentLinkRequestSettingsIntent} intent
 */
PFLitePaymentLinkRequestSettings.prototype['intent'] = undefined;





/**
 * Allowed values for the <code>additionalDetailsPreference</code> property.
 * @enum {String}
 * @readonly
 */
PFLitePaymentLinkRequestSettings['AdditionalDetailsPreferenceEnum'] = {

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "AskShopper"
     * @const
     */
    "AskShopper": "AskShopper",

    /**
     * value: "ManualEnter"
     * @const
     */
    "ManualEnter": "ManualEnter",

    /**
     * value: "NoAdditionalDetails"
     * @const
     */
    "NoAdditionalDetails": "NoAdditionalDetails",

    /**
     * value: "ManualEnterEditNotAllowed"
     * @const
     */
    "ManualEnterEditNotAllowed": "ManualEnterEditNotAllowed"
};



export default PFLitePaymentLinkRequestSettings;

