/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PFLiteSecureQuoteRequestMerchant model module.
 * @module model/PFLiteSecureQuoteRequestMerchant
 * @version 2.3
 */
class PFLiteSecureQuoteRequestMerchant {
    /**
     * Constructs a new <code>PFLiteSecureQuoteRequestMerchant</code>.
     * @alias module:model/PFLiteSecureQuoteRequestMerchant
     */
    constructor() { 
        
        PFLiteSecureQuoteRequestMerchant.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PFLiteSecureQuoteRequestMerchant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFLiteSecureQuoteRequestMerchant} obj Optional instance to populate.
     * @return {module:model/PFLiteSecureQuoteRequestMerchant} The populated <code>PFLiteSecureQuoteRequestMerchant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFLiteSecureQuoteRequestMerchant();

            if (data.hasOwnProperty('contactName')) {
                obj['contactName'] = ApiClient.convertToType(data['contactName'], 'String');
            }
            if (data.hasOwnProperty('contactPhone')) {
                obj['contactPhone'] = ApiClient.convertToType(data['contactPhone'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFLiteSecureQuoteRequestMerchant</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFLiteSecureQuoteRequestMerchant</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['contactName'] && !(typeof data['contactName'] === 'string' || data['contactName'] instanceof String)) {
            throw new Error("Expected the field `contactName` to be a primitive type in the JSON string but got " + data['contactName']);
        }
        // ensure the json data is a string
        if (data['contactPhone'] && !(typeof data['contactPhone'] === 'string' || data['contactPhone'] instanceof String)) {
            throw new Error("Expected the field `contactPhone` to be a primitive type in the JSON string but got " + data['contactPhone']);
        }

        return true;
    }


}



/**
 * @member {String} contactName
 */
PFLiteSecureQuoteRequestMerchant.prototype['contactName'] = undefined;

/**
 * @member {String} contactPhone
 */
PFLiteSecureQuoteRequestMerchant.prototype['contactPhone'] = undefined;






export default PFLiteSecureQuoteRequestMerchant;

