/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PFLitePaymentLinkRequestCustomersInnerAddress from './PFLitePaymentLinkRequestCustomersInnerAddress';

/**
 * The PFLitePaymentLinkRequestCustomersInner model module.
 * @module model/PFLitePaymentLinkRequestCustomersInner
 * @version 2.3
 */
class PFLitePaymentLinkRequestCustomersInner {
    /**
     * Constructs a new <code>PFLitePaymentLinkRequestCustomersInner</code>.
     * @alias module:model/PFLitePaymentLinkRequestCustomersInner
     * @param firstName {String} 
     * @param lastName {String} 
     * @param email {String} 
     * @param phone {String} 
     */
    constructor(firstName, lastName, email, phone) { 
        
        PFLitePaymentLinkRequestCustomersInner.initialize(this, firstName, lastName, email, phone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, firstName, lastName, email, phone) { 
        obj['firstName'] = firstName;
        obj['lastName'] = lastName;
        obj['email'] = email;
        obj['phone'] = phone;
    }

    /**
     * Constructs a <code>PFLitePaymentLinkRequestCustomersInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFLitePaymentLinkRequestCustomersInner} obj Optional instance to populate.
     * @return {module:model/PFLitePaymentLinkRequestCustomersInner} The populated <code>PFLitePaymentLinkRequestCustomersInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFLitePaymentLinkRequestCustomersInner();

            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('phoneCountryCode')) {
                obj['phoneCountryCode'] = ApiClient.convertToType(data['phoneCountryCode'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = PFLitePaymentLinkRequestCustomersInnerAddress.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('notifyViaSMS')) {
                obj['notifyViaSMS'] = ApiClient.convertToType(data['notifyViaSMS'], 'Boolean');
            }
            if (data.hasOwnProperty('notifyViaEmail')) {
                obj['notifyViaEmail'] = ApiClient.convertToType(data['notifyViaEmail'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFLitePaymentLinkRequestCustomersInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFLitePaymentLinkRequestCustomersInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PFLitePaymentLinkRequestCustomersInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['phoneCountryCode'] && !(typeof data['phoneCountryCode'] === 'string' || data['phoneCountryCode'] instanceof String)) {
            throw new Error("Expected the field `phoneCountryCode` to be a primitive type in the JSON string but got " + data['phoneCountryCode']);
        }
        // validate the optional field `address`
        if (data['address']) { // data not null
          PFLitePaymentLinkRequestCustomersInnerAddress.validateJSON(data['address']);
        }

        return true;
    }


}

PFLitePaymentLinkRequestCustomersInner.RequiredProperties = ["firstName", "lastName", "email", "phone"];

/**
 * @member {String} firstName
 */
PFLitePaymentLinkRequestCustomersInner.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
PFLitePaymentLinkRequestCustomersInner.prototype['lastName'] = undefined;

/**
 * @member {String} email
 */
PFLitePaymentLinkRequestCustomersInner.prototype['email'] = undefined;

/**
 * @member {String} phone
 */
PFLitePaymentLinkRequestCustomersInner.prototype['phone'] = undefined;

/**
 * @member {String} phoneCountryCode
 */
PFLitePaymentLinkRequestCustomersInner.prototype['phoneCountryCode'] = undefined;

/**
 * @member {module:model/PFLitePaymentLinkRequestCustomersInnerAddress} address
 */
PFLitePaymentLinkRequestCustomersInner.prototype['address'] = undefined;

/**
 * @member {Boolean} notifyViaSMS
 */
PFLitePaymentLinkRequestCustomersInner.prototype['notifyViaSMS'] = undefined;

/**
 * @member {Boolean} notifyViaEmail
 */
PFLitePaymentLinkRequestCustomersInner.prototype['notifyViaEmail'] = undefined;






export default PFLitePaymentLinkRequestCustomersInner;

