/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PFLitePaymentLinkRequestCallbackParameters model module.
 * @module model/PFLitePaymentLinkRequestCallbackParameters
 * @version 2.3
 */
class PFLitePaymentLinkRequestCallbackParameters {
    /**
     * Constructs a new <code>PFLitePaymentLinkRequestCallbackParameters</code>.
     * @alias module:model/PFLitePaymentLinkRequestCallbackParameters
     */
    constructor() { 
        
        PFLitePaymentLinkRequestCallbackParameters.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PFLitePaymentLinkRequestCallbackParameters</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFLitePaymentLinkRequestCallbackParameters} obj Optional instance to populate.
     * @return {module:model/PFLitePaymentLinkRequestCallbackParameters} The populated <code>PFLitePaymentLinkRequestCallbackParameters</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFLitePaymentLinkRequestCallbackParameters();

            if (data.hasOwnProperty('callbackApiUrl')) {
                obj['callbackApiUrl'] = ApiClient.convertToType(data['callbackApiUrl'], 'String');
            }
            if (data.hasOwnProperty('callbackMessage')) {
                obj['callbackMessage'] = ApiClient.convertToType(data['callbackMessage'], 'String');
            }
            if (data.hasOwnProperty('accessKey')) {
                obj['accessKey'] = ApiClient.convertToType(data['accessKey'], 'String');
            }
            if (data.hasOwnProperty('secretKey')) {
                obj['secretKey'] = ApiClient.convertToType(data['secretKey'], 'String');
            }
            if (data.hasOwnProperty('referenceNo')) {
                obj['referenceNo'] = ApiClient.convertToType(data['referenceNo'], 'String');
            }
            if (data.hasOwnProperty('referenceType')) {
                obj['referenceType'] = ApiClient.convertToType(data['referenceType'], 'String');
            }
            if (data.hasOwnProperty('transactionId')) {
                obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
            }
            if (data.hasOwnProperty('redirectionTime')) {
                obj['redirectionTime'] = ApiClient.convertToType(data['redirectionTime'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFLitePaymentLinkRequestCallbackParameters</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFLitePaymentLinkRequestCallbackParameters</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['callbackApiUrl'] && !(typeof data['callbackApiUrl'] === 'string' || data['callbackApiUrl'] instanceof String)) {
            throw new Error("Expected the field `callbackApiUrl` to be a primitive type in the JSON string but got " + data['callbackApiUrl']);
        }
        // ensure the json data is a string
        if (data['callbackMessage'] && !(typeof data['callbackMessage'] === 'string' || data['callbackMessage'] instanceof String)) {
            throw new Error("Expected the field `callbackMessage` to be a primitive type in the JSON string but got " + data['callbackMessage']);
        }
        // ensure the json data is a string
        if (data['accessKey'] && !(typeof data['accessKey'] === 'string' || data['accessKey'] instanceof String)) {
            throw new Error("Expected the field `accessKey` to be a primitive type in the JSON string but got " + data['accessKey']);
        }
        // ensure the json data is a string
        if (data['secretKey'] && !(typeof data['secretKey'] === 'string' || data['secretKey'] instanceof String)) {
            throw new Error("Expected the field `secretKey` to be a primitive type in the JSON string but got " + data['secretKey']);
        }
        // ensure the json data is a string
        if (data['referenceNo'] && !(typeof data['referenceNo'] === 'string' || data['referenceNo'] instanceof String)) {
            throw new Error("Expected the field `referenceNo` to be a primitive type in the JSON string but got " + data['referenceNo']);
        }
        // ensure the json data is a string
        if (data['referenceType'] && !(typeof data['referenceType'] === 'string' || data['referenceType'] instanceof String)) {
            throw new Error("Expected the field `referenceType` to be a primitive type in the JSON string but got " + data['referenceType']);
        }
        // ensure the json data is a string
        if (data['transactionId'] && !(typeof data['transactionId'] === 'string' || data['transactionId'] instanceof String)) {
            throw new Error("Expected the field `transactionId` to be a primitive type in the JSON string but got " + data['transactionId']);
        }

        return true;
    }


}



/**
 * @member {String} callbackApiUrl
 */
PFLitePaymentLinkRequestCallbackParameters.prototype['callbackApiUrl'] = undefined;

/**
 * @member {String} callbackMessage
 */
PFLitePaymentLinkRequestCallbackParameters.prototype['callbackMessage'] = undefined;

/**
 * @member {String} accessKey
 */
PFLitePaymentLinkRequestCallbackParameters.prototype['accessKey'] = undefined;

/**
 * @member {String} secretKey
 */
PFLitePaymentLinkRequestCallbackParameters.prototype['secretKey'] = undefined;

/**
 * @member {String} referenceNo
 */
PFLitePaymentLinkRequestCallbackParameters.prototype['referenceNo'] = undefined;

/**
 * @member {String} referenceType
 */
PFLitePaymentLinkRequestCallbackParameters.prototype['referenceType'] = undefined;

/**
 * @member {String} transactionId
 */
PFLitePaymentLinkRequestCallbackParameters.prototype['transactionId'] = undefined;

/**
 * @member {Number} redirectionTime
 */
PFLitePaymentLinkRequestCallbackParameters.prototype['redirectionTime'] = undefined;






export default PFLitePaymentLinkRequestCallbackParameters;

