/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PFQuoteEsignRequest model module.
 * @module model/PFQuoteEsignRequest
 * @version 2.3
 */
class PFQuoteEsignRequest {
    /**
     * Constructs a new <code>PFQuoteEsignRequest</code>.
     * @alias module:model/PFQuoteEsignRequest
     * @param quoteKey {String} This denotes the quoteKey.
     * @param insuredName {String} This denotes the name of the insured.
     */
    constructor(quoteKey, insuredName) { 
        
        PFQuoteEsignRequest.initialize(this, quoteKey, insuredName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, quoteKey, insuredName) { 
        obj['quoteKey'] = quoteKey;
        obj['insuredName'] = insuredName;
    }

    /**
     * Constructs a <code>PFQuoteEsignRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PFQuoteEsignRequest} obj Optional instance to populate.
     * @return {module:model/PFQuoteEsignRequest} The populated <code>PFQuoteEsignRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PFQuoteEsignRequest();

            if (data.hasOwnProperty('merchantToken')) {
                obj['merchantToken'] = ApiClient.convertToType(data['merchantToken'], 'String');
            }
            if (data.hasOwnProperty('quoteKey')) {
                obj['quoteKey'] = ApiClient.convertToType(data['quoteKey'], 'String');
            }
            if (data.hasOwnProperty('insuredName')) {
                obj['insuredName'] = ApiClient.convertToType(data['insuredName'], 'String');
            }
            if (data.hasOwnProperty('ipAddress')) {
                obj['ipAddress'] = ApiClient.convertToType(data['ipAddress'], 'String');
            }
            if (data.hasOwnProperty('macAddress')) {
                obj['macAddress'] = ApiClient.convertToType(data['macAddress'], 'String');
            }
            if (data.hasOwnProperty('captchaToken')) {
                obj['captchaToken'] = ApiClient.convertToType(data['captchaToken'], 'String');
            }
            if (data.hasOwnProperty('actionName')) {
                obj['actionName'] = ApiClient.convertToType(data['actionName'], 'String');
            }
            if (data.hasOwnProperty('isSignAPA')) {
                obj['isSignAPA'] = ApiClient.convertToType(data['isSignAPA'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PFQuoteEsignRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PFQuoteEsignRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PFQuoteEsignRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['merchantToken'] && !(typeof data['merchantToken'] === 'string' || data['merchantToken'] instanceof String)) {
            throw new Error("Expected the field `merchantToken` to be a primitive type in the JSON string but got " + data['merchantToken']);
        }
        // ensure the json data is a string
        if (data['quoteKey'] && !(typeof data['quoteKey'] === 'string' || data['quoteKey'] instanceof String)) {
            throw new Error("Expected the field `quoteKey` to be a primitive type in the JSON string but got " + data['quoteKey']);
        }
        // ensure the json data is a string
        if (data['insuredName'] && !(typeof data['insuredName'] === 'string' || data['insuredName'] instanceof String)) {
            throw new Error("Expected the field `insuredName` to be a primitive type in the JSON string but got " + data['insuredName']);
        }
        // ensure the json data is a string
        if (data['ipAddress'] && !(typeof data['ipAddress'] === 'string' || data['ipAddress'] instanceof String)) {
            throw new Error("Expected the field `ipAddress` to be a primitive type in the JSON string but got " + data['ipAddress']);
        }
        // ensure the json data is a string
        if (data['macAddress'] && !(typeof data['macAddress'] === 'string' || data['macAddress'] instanceof String)) {
            throw new Error("Expected the field `macAddress` to be a primitive type in the JSON string but got " + data['macAddress']);
        }
        // ensure the json data is a string
        if (data['captchaToken'] && !(typeof data['captchaToken'] === 'string' || data['captchaToken'] instanceof String)) {
            throw new Error("Expected the field `captchaToken` to be a primitive type in the JSON string but got " + data['captchaToken']);
        }
        // ensure the json data is a string
        if (data['actionName'] && !(typeof data['actionName'] === 'string' || data['actionName'] instanceof String)) {
            throw new Error("Expected the field `actionName` to be a primitive type in the JSON string but got " + data['actionName']);
        }

        return true;
    }


}

PFQuoteEsignRequest.RequiredProperties = ["quoteKey", "insuredName"];

/**
 * This denotes the merchant token.
 * @member {String} merchantToken
 */
PFQuoteEsignRequest.prototype['merchantToken'] = undefined;

/**
 * This denotes the quoteKey.
 * @member {String} quoteKey
 */
PFQuoteEsignRequest.prototype['quoteKey'] = undefined;

/**
 * This denotes the name of the insured.
 * @member {String} insuredName
 */
PFQuoteEsignRequest.prototype['insuredName'] = undefined;

/**
 * This denotes the IP address of the client.
 * @member {String} ipAddress
 */
PFQuoteEsignRequest.prototype['ipAddress'] = undefined;

/**
 * This denotes the MAC address of the client.
 * @member {String} macAddress
 */
PFQuoteEsignRequest.prototype['macAddress'] = undefined;

/**
 * This denotes the captchaToken.
 * @member {String} captchaToken
 */
PFQuoteEsignRequest.prototype['captchaToken'] = undefined;

/**
 * This denotes the action name.
 * @member {String} actionName
 */
PFQuoteEsignRequest.prototype['actionName'] = undefined;

/**
 * This denotes isSignAPA status.
 * @member {Boolean} isSignAPA
 */
PFQuoteEsignRequest.prototype['isSignAPA'] = undefined;






export default PFQuoteEsignRequest;

