/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QuoteRequestInsuredAddress from './QuoteRequestInsuredAddress';

/**
 * The QuoteRequestInsured model module.
 * @module model/QuoteRequestInsured
 * @version 2.3
 */
class QuoteRequestInsured {
    /**
     * Constructs a new <code>QuoteRequestInsured</code>.
     * @alias module:model/QuoteRequestInsured
     * @param email {String} 
     * @param address {module:model/QuoteRequestInsuredAddress} 
     */
    constructor(email, address) { 
        
        QuoteRequestInsured.initialize(this, email, address);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, address) { 
        obj['email'] = email;
        obj['address'] = address;
    }

    /**
     * Constructs a <code>QuoteRequestInsured</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuoteRequestInsured} obj Optional instance to populate.
     * @return {module:model/QuoteRequestInsured} The populated <code>QuoteRequestInsured</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuoteRequestInsured();

            if (data.hasOwnProperty('agentCustomerNumber')) {
                obj['agentCustomerNumber'] = ApiClient.convertToType(data['agentCustomerNumber'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('careOf')) {
                obj['careOf'] = ApiClient.convertToType(data['careOf'], 'String');
            }
            if (data.hasOwnProperty('uniqueId')) {
                obj['uniqueId'] = ApiClient.convertToType(data['uniqueId'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = QuoteRequestInsuredAddress.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('hasDataChangeAgentCustomerNumber')) {
                obj['hasDataChangeAgentCustomerNumber'] = ApiClient.convertToType(data['hasDataChangeAgentCustomerNumber'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeName')) {
                obj['hasDataChangeName'] = ApiClient.convertToType(data['hasDataChangeName'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeAddress1')) {
                obj['hasDataChangeAddress1'] = ApiClient.convertToType(data['hasDataChangeAddress1'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeAddress2')) {
                obj['hasDataChangeAddress2'] = ApiClient.convertToType(data['hasDataChangeAddress2'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeCity')) {
                obj['hasDataChangeCity'] = ApiClient.convertToType(data['hasDataChangeCity'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeState')) {
                obj['hasDataChangeState'] = ApiClient.convertToType(data['hasDataChangeState'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeZip')) {
                obj['hasDataChangeZip'] = ApiClient.convertToType(data['hasDataChangeZip'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangePhone')) {
                obj['hasDataChangePhone'] = ApiClient.convertToType(data['hasDataChangePhone'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeEmail')) {
                obj['hasDataChangeEmail'] = ApiClient.convertToType(data['hasDataChangeEmail'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeCareOf')) {
                obj['hasDataChangeCareOf'] = ApiClient.convertToType(data['hasDataChangeCareOf'], 'Boolean');
            }
            if (data.hasOwnProperty('hasDataChangeInsured')) {
                obj['hasDataChangeInsured'] = ApiClient.convertToType(data['hasDataChangeInsured'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuoteRequestInsured</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuoteRequestInsured</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QuoteRequestInsured.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['agentCustomerNumber'] && !(typeof data['agentCustomerNumber'] === 'string' || data['agentCustomerNumber'] instanceof String)) {
            throw new Error("Expected the field `agentCustomerNumber` to be a primitive type in the JSON string but got " + data['agentCustomerNumber']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['careOf'] && !(typeof data['careOf'] === 'string' || data['careOf'] instanceof String)) {
            throw new Error("Expected the field `careOf` to be a primitive type in the JSON string but got " + data['careOf']);
        }
        // ensure the json data is a string
        if (data['uniqueId'] && !(typeof data['uniqueId'] === 'string' || data['uniqueId'] instanceof String)) {
            throw new Error("Expected the field `uniqueId` to be a primitive type in the JSON string but got " + data['uniqueId']);
        }
        // validate the optional field `address`
        if (data['address']) { // data not null
          QuoteRequestInsuredAddress.validateJSON(data['address']);
        }

        return true;
    }


}

QuoteRequestInsured.RequiredProperties = ["email", "address"];

/**
 * @member {String} agentCustomerNumber
 */
QuoteRequestInsured.prototype['agentCustomerNumber'] = undefined;

/**
 * @member {String} email
 */
QuoteRequestInsured.prototype['email'] = undefined;

/**
 * @member {String} careOf
 */
QuoteRequestInsured.prototype['careOf'] = undefined;

/**
 * @member {String} uniqueId
 */
QuoteRequestInsured.prototype['uniqueId'] = undefined;

/**
 * @member {module:model/QuoteRequestInsuredAddress} address
 */
QuoteRequestInsured.prototype['address'] = undefined;

/**
 * @member {Boolean} hasDataChangeAgentCustomerNumber
 */
QuoteRequestInsured.prototype['hasDataChangeAgentCustomerNumber'] = undefined;

/**
 * @member {Boolean} hasDataChangeName
 */
QuoteRequestInsured.prototype['hasDataChangeName'] = undefined;

/**
 * @member {Boolean} hasDataChangeAddress1
 */
QuoteRequestInsured.prototype['hasDataChangeAddress1'] = undefined;

/**
 * @member {Boolean} hasDataChangeAddress2
 */
QuoteRequestInsured.prototype['hasDataChangeAddress2'] = undefined;

/**
 * @member {Boolean} hasDataChangeCity
 */
QuoteRequestInsured.prototype['hasDataChangeCity'] = undefined;

/**
 * @member {Boolean} hasDataChangeState
 */
QuoteRequestInsured.prototype['hasDataChangeState'] = undefined;

/**
 * @member {Boolean} hasDataChangeZip
 */
QuoteRequestInsured.prototype['hasDataChangeZip'] = undefined;

/**
 * @member {Boolean} hasDataChangePhone
 */
QuoteRequestInsured.prototype['hasDataChangePhone'] = undefined;

/**
 * @member {Boolean} hasDataChangeEmail
 */
QuoteRequestInsured.prototype['hasDataChangeEmail'] = undefined;

/**
 * @member {Boolean} hasDataChangeCareOf
 */
QuoteRequestInsured.prototype['hasDataChangeCareOf'] = undefined;

/**
 * @member {Boolean} hasDataChangeInsured
 */
QuoteRequestInsured.prototype['hasDataChangeInsured'] = undefined;






export default QuoteRequestInsured;

