/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QuoteRequestDetails model module.
 * @module model/QuoteRequestDetails
 * @version 2.3
 */
class QuoteRequestDetails {
    /**
     * Constructs a new <code>QuoteRequestDetails</code>.
     * @alias module:model/QuoteRequestDetails
     */
    constructor() { 
        
        QuoteRequestDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>QuoteRequestDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuoteRequestDetails} obj Optional instance to populate.
     * @return {module:model/QuoteRequestDetails} The populated <code>QuoteRequestDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuoteRequestDetails();

            if (data.hasOwnProperty('couponInvoicePrinted')) {
                obj['couponInvoicePrinted'] = ApiClient.convertToType(data['couponInvoicePrinted'], 'Boolean');
            }
            if (data.hasOwnProperty('installments')) {
                obj['installments'] = ApiClient.convertToType(data['installments'], 'Number');
            }
            if (data.hasOwnProperty('programIDs')) {
                obj['programIDs'] = ApiClient.convertToType(data['programIDs'], ['Number']);
            }
            if (data.hasOwnProperty('batchID')) {
                obj['batchID'] = ApiClient.convertToType(data['batchID'], 'String');
            }
            if (data.hasOwnProperty('commercial')) {
                obj['commercial'] = ApiClient.convertToType(data['commercial'], 'String');
            }
            if (data.hasOwnProperty('coupon')) {
                obj['coupon'] = ApiClient.convertToType(data['coupon'], 'String');
            }
            if (data.hasOwnProperty('interval')) {
                obj['interval'] = ApiClient.convertToType(data['interval'], 'String');
            }
            if (data.hasOwnProperty('downPaymentMethod')) {
                obj['downPaymentMethod'] = ApiClient.convertToType(data['downPaymentMethod'], 'String');
            }
            if (data.hasOwnProperty('downPaymentPaidBy')) {
                obj['downPaymentPaidBy'] = ApiClient.convertToType(data['downPaymentPaidBy'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuoteRequestDetails</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuoteRequestDetails</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['programIDs'])) {
            throw new Error("Expected the field `programIDs` to be an array in the JSON data but got " + data['programIDs']);
        }
        // ensure the json data is a string
        if (data['batchID'] && !(typeof data['batchID'] === 'string' || data['batchID'] instanceof String)) {
            throw new Error("Expected the field `batchID` to be a primitive type in the JSON string but got " + data['batchID']);
        }
        // ensure the json data is a string
        if (data['commercial'] && !(typeof data['commercial'] === 'string' || data['commercial'] instanceof String)) {
            throw new Error("Expected the field `commercial` to be a primitive type in the JSON string but got " + data['commercial']);
        }
        // ensure the json data is a string
        if (data['coupon'] && !(typeof data['coupon'] === 'string' || data['coupon'] instanceof String)) {
            throw new Error("Expected the field `coupon` to be a primitive type in the JSON string but got " + data['coupon']);
        }
        // ensure the json data is a string
        if (data['interval'] && !(typeof data['interval'] === 'string' || data['interval'] instanceof String)) {
            throw new Error("Expected the field `interval` to be a primitive type in the JSON string but got " + data['interval']);
        }
        // ensure the json data is a string
        if (data['downPaymentMethod'] && !(typeof data['downPaymentMethod'] === 'string' || data['downPaymentMethod'] instanceof String)) {
            throw new Error("Expected the field `downPaymentMethod` to be a primitive type in the JSON string but got " + data['downPaymentMethod']);
        }
        // ensure the json data is a string
        if (data['downPaymentPaidBy'] && !(typeof data['downPaymentPaidBy'] === 'string' || data['downPaymentPaidBy'] instanceof String)) {
            throw new Error("Expected the field `downPaymentPaidBy` to be a primitive type in the JSON string but got " + data['downPaymentPaidBy']);
        }

        return true;
    }


}



/**
 * @member {Boolean} couponInvoicePrinted
 */
QuoteRequestDetails.prototype['couponInvoicePrinted'] = undefined;

/**
 * @member {Number} installments
 */
QuoteRequestDetails.prototype['installments'] = undefined;

/**
 * @member {Array.<Number>} programIDs
 */
QuoteRequestDetails.prototype['programIDs'] = undefined;

/**
 * @member {String} batchID
 */
QuoteRequestDetails.prototype['batchID'] = undefined;

/**
 * @member {module:model/QuoteRequestDetails.CommercialEnum} commercial
 */
QuoteRequestDetails.prototype['commercial'] = undefined;

/**
 * @member {module:model/QuoteRequestDetails.CouponEnum} coupon
 */
QuoteRequestDetails.prototype['coupon'] = undefined;

/**
 * @member {module:model/QuoteRequestDetails.IntervalEnum} interval
 */
QuoteRequestDetails.prototype['interval'] = undefined;

/**
 * @member {module:model/QuoteRequestDetails.DownPaymentMethodEnum} downPaymentMethod
 */
QuoteRequestDetails.prototype['downPaymentMethod'] = undefined;

/**
 * @member {module:model/QuoteRequestDetails.DownPaymentPaidByEnum} downPaymentPaidBy
 */
QuoteRequestDetails.prototype['downPaymentPaidBy'] = undefined;





/**
 * Allowed values for the <code>commercial</code> property.
 * @enum {String}
 * @readonly
 */
QuoteRequestDetails['CommercialEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Commercial"
     * @const
     */
    "Commercial": "Commercial",

    /**
     * value: "Personal"
     * @const
     */
    "Personal": "Personal"
};


/**
 * Allowed values for the <code>coupon</code> property.
 * @enum {String}
 * @readonly
 */
QuoteRequestDetails['CouponEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "PaymentsInvoices"
     * @const
     */
    "PaymentsInvoices": "PaymentsInvoices",

    /**
     * value: "CouponsBook"
     * @const
     */
    "CouponsBook": "CouponsBook"
};


/**
 * Allowed values for the <code>interval</code> property.
 * @enum {String}
 * @readonly
 */
QuoteRequestDetails['IntervalEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Monthly"
     * @const
     */
    "Monthly": "Monthly",

    /**
     * value: "Bimonthly"
     * @const
     */
    "Bimonthly": "Bimonthly",

    /**
     * value: "Quarterly"
     * @const
     */
    "Quarterly": "Quarterly",

    /**
     * value: "SemiAnnual"
     * @const
     */
    "SemiAnnual": "SemiAnnual",

    /**
     * value: "Annual"
     * @const
     */
    "Annual": "Annual",

    /**
     * value: "Z"
     * @const
     */
    "Z": "Z",

    /**
     * value: "Y"
     * @const
     */
    "Y": "Y",

    /**
     * value: "X"
     * @const
     */
    "X": "X",

    /**
     * value: "W"
     * @const
     */
    "W": "W"
};


/**
 * Allowed values for the <code>downPaymentMethod</code> property.
 * @enum {String}
 * @readonly
 */
QuoteRequestDetails['DownPaymentMethodEnum'] = {

    /**
     * value: "ACH"
     * @const
     */
    "ACH": "ACH",

    /**
     * value: "CC"
     * @const
     */
    "CC": "CC",

    /**
     * value: "BOTH"
     * @const
     */
    "BOTH": "BOTH"
};


/**
 * Allowed values for the <code>downPaymentPaidBy</code> property.
 * @enum {String}
 * @readonly
 */
QuoteRequestDetails['DownPaymentPaidByEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Agent"
     * @const
     */
    "Agent": "Agent",

    /**
     * value: "Insured"
     * @const
     */
    "Insured": "Insured"
};



export default QuoteRequestDetails;

