/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentIntentRequestSplitsInner from './PaymentIntentRequestSplitsInner';

/**
 * The SecureTransactionRefundRequest model module.
 * @module model/SecureTransactionRefundRequest
 * @version 2.3
 */
class SecureTransactionRefundRequest {
    /**
     * Constructs a new <code>SecureTransactionRefundRequest</code>.
     * @alias module:model/SecureTransactionRefundRequest
     * @param refundAmount {Number} 
     * @param transactionId {String} 
     * @param refundReason {String} 
     * @param refundDetail {String} 
     * @param refundType {module:model/SecureTransactionRefundRequest.RefundTypeEnum} 
     */
    constructor(refundAmount, transactionId, refundReason, refundDetail, refundType) { 
        
        SecureTransactionRefundRequest.initialize(this, refundAmount, transactionId, refundReason, refundDetail, refundType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, refundAmount, transactionId, refundReason, refundDetail, refundType) { 
        obj['refundAmount'] = refundAmount;
        obj['transactionId'] = transactionId;
        obj['refundReason'] = refundReason;
        obj['refundDetail'] = refundDetail;
        obj['refundType'] = refundType;
    }

    /**
     * Constructs a <code>SecureTransactionRefundRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecureTransactionRefundRequest} obj Optional instance to populate.
     * @return {module:model/SecureTransactionRefundRequest} The populated <code>SecureTransactionRefundRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecureTransactionRefundRequest();

            if (data.hasOwnProperty('invoiceNumber')) {
                obj['invoiceNumber'] = ApiClient.convertToType(data['invoiceNumber'], 'String');
            }
            if (data.hasOwnProperty('pONumber')) {
                obj['pONumber'] = ApiClient.convertToType(data['pONumber'], 'String');
            }
            if (data.hasOwnProperty('refundAmount')) {
                obj['refundAmount'] = ApiClient.convertToType(data['refundAmount'], 'Number');
            }
            if (data.hasOwnProperty('transactionId')) {
                obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
            }
            if (data.hasOwnProperty('remarks')) {
                obj['remarks'] = ApiClient.convertToType(data['remarks'], 'String');
            }
            if (data.hasOwnProperty('refundReason')) {
                obj['refundReason'] = ApiClient.convertToType(data['refundReason'], 'String');
            }
            if (data.hasOwnProperty('refundDetail')) {
                obj['refundDetail'] = ApiClient.convertToType(data['refundDetail'], 'String');
            }
            if (data.hasOwnProperty('refundType')) {
                obj['refundType'] = ApiClient.convertToType(data['refundType'], 'String');
            }
            if (data.hasOwnProperty('splits')) {
                obj['splits'] = ApiClient.convertToType(data['splits'], [PaymentIntentRequestSplitsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SecureTransactionRefundRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SecureTransactionRefundRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SecureTransactionRefundRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['invoiceNumber'] && !(typeof data['invoiceNumber'] === 'string' || data['invoiceNumber'] instanceof String)) {
            throw new Error("Expected the field `invoiceNumber` to be a primitive type in the JSON string but got " + data['invoiceNumber']);
        }
        // ensure the json data is a string
        if (data['pONumber'] && !(typeof data['pONumber'] === 'string' || data['pONumber'] instanceof String)) {
            throw new Error("Expected the field `pONumber` to be a primitive type in the JSON string but got " + data['pONumber']);
        }
        // ensure the json data is a string
        if (data['transactionId'] && !(typeof data['transactionId'] === 'string' || data['transactionId'] instanceof String)) {
            throw new Error("Expected the field `transactionId` to be a primitive type in the JSON string but got " + data['transactionId']);
        }
        // ensure the json data is a string
        if (data['remarks'] && !(typeof data['remarks'] === 'string' || data['remarks'] instanceof String)) {
            throw new Error("Expected the field `remarks` to be a primitive type in the JSON string but got " + data['remarks']);
        }
        // ensure the json data is a string
        if (data['refundReason'] && !(typeof data['refundReason'] === 'string' || data['refundReason'] instanceof String)) {
            throw new Error("Expected the field `refundReason` to be a primitive type in the JSON string but got " + data['refundReason']);
        }
        // ensure the json data is a string
        if (data['refundDetail'] && !(typeof data['refundDetail'] === 'string' || data['refundDetail'] instanceof String)) {
            throw new Error("Expected the field `refundDetail` to be a primitive type in the JSON string but got " + data['refundDetail']);
        }
        // ensure the json data is a string
        if (data['refundType'] && !(typeof data['refundType'] === 'string' || data['refundType'] instanceof String)) {
            throw new Error("Expected the field `refundType` to be a primitive type in the JSON string but got " + data['refundType']);
        }
        if (data['splits']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['splits'])) {
                throw new Error("Expected the field `splits` to be an array in the JSON data but got " + data['splits']);
            }
            // validate the optional field `splits` (array)
            for (const item of data['splits']) {
                PaymentIntentRequestSplitsInner.validateJSON(item);
            };
        }

        return true;
    }


}

SecureTransactionRefundRequest.RequiredProperties = ["refundAmount", "transactionId", "refundReason", "refundDetail", "refundType"];

/**
 * @member {String} invoiceNumber
 */
SecureTransactionRefundRequest.prototype['invoiceNumber'] = undefined;

/**
 * @member {String} pONumber
 */
SecureTransactionRefundRequest.prototype['pONumber'] = undefined;

/**
 * @member {Number} refundAmount
 */
SecureTransactionRefundRequest.prototype['refundAmount'] = undefined;

/**
 * @member {String} transactionId
 */
SecureTransactionRefundRequest.prototype['transactionId'] = undefined;

/**
 * @member {String} remarks
 */
SecureTransactionRefundRequest.prototype['remarks'] = undefined;

/**
 * @member {String} refundReason
 */
SecureTransactionRefundRequest.prototype['refundReason'] = undefined;

/**
 * @member {String} refundDetail
 */
SecureTransactionRefundRequest.prototype['refundDetail'] = undefined;

/**
 * @member {module:model/SecureTransactionRefundRequest.RefundTypeEnum} refundType
 */
SecureTransactionRefundRequest.prototype['refundType'] = undefined;

/**
 * @member {Array.<module:model/PaymentIntentRequestSplitsInner>} splits
 */
SecureTransactionRefundRequest.prototype['splits'] = undefined;





/**
 * Allowed values for the <code>refundType</code> property.
 * @enum {String}
 * @readonly
 */
SecureTransactionRefundRequest['RefundTypeEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Total"
     * @const
     */
    "Total": "Total",

    /**
     * value: "Subtotal"
     * @const
     */
    "Subtotal": "Subtotal",

    /**
     * value: "Remaining"
     * @const
     */
    "Remaining": "Remaining",

    /**
     * value: "Partial"
     * @const
     */
    "Partial": "Partial"
};



export default SecureTransactionRefundRequest;

