/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentLinkResponseCallbackParameters from './PaymentLinkResponseCallbackParameters';
import SecureTokenLinkResponseCustomersInner from './SecureTokenLinkResponseCustomersInner';
import SecureTokenLinkResponseIntent from './SecureTokenLinkResponseIntent';

/**
 * The SecureTokenLinkResponse model module.
 * @module model/SecureTokenLinkResponse
 * @version 2.3
 */
class SecureTokenLinkResponse {
    /**
     * Constructs a new <code>SecureTokenLinkResponse</code>.
     * @alias module:model/SecureTokenLinkResponse
     */
    constructor() { 
        
        SecureTokenLinkResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SecureTokenLinkResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecureTokenLinkResponse} obj Optional instance to populate.
     * @return {module:model/SecureTokenLinkResponse} The populated <code>SecureTokenLinkResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecureTokenLinkResponse();

            if (data.hasOwnProperty('merchantId')) {
                obj['merchantId'] = ApiClient.convertToType(data['merchantId'], 'String');
            }
            if (data.hasOwnProperty('tokenLinkId')) {
                obj['tokenLinkId'] = ApiClient.convertToType(data['tokenLinkId'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('expireOn')) {
                obj['expireOn'] = ApiClient.convertToType(data['expireOn'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'String');
            }
            if (data.hasOwnProperty('modifiedOn')) {
                obj['modifiedOn'] = ApiClient.convertToType(data['modifiedOn'], 'String');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'String');
            }
            if (data.hasOwnProperty('modifiedBy')) {
                obj['modifiedBy'] = ApiClient.convertToType(data['modifiedBy'], 'String');
            }
            if (data.hasOwnProperty('tokenLinkStatus')) {
                obj['tokenLinkStatus'] = ApiClient.convertToType(data['tokenLinkStatus'], 'String');
            }
            if (data.hasOwnProperty('responseType')) {
                obj['responseType'] = ApiClient.convertToType(data['responseType'], 'String');
            }
            if (data.hasOwnProperty('callBackParameters')) {
                obj['callBackParameters'] = PaymentLinkResponseCallbackParameters.constructFromObject(data['callBackParameters']);
            }
            if (data.hasOwnProperty('intent')) {
                obj['intent'] = SecureTokenLinkResponseIntent.constructFromObject(data['intent']);
            }
            if (data.hasOwnProperty('customers')) {
                obj['customers'] = ApiClient.convertToType(data['customers'], [SecureTokenLinkResponseCustomersInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SecureTokenLinkResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SecureTokenLinkResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['merchantId'] && !(typeof data['merchantId'] === 'string' || data['merchantId'] instanceof String)) {
            throw new Error("Expected the field `merchantId` to be a primitive type in the JSON string but got " + data['merchantId']);
        }
        // ensure the json data is a string
        if (data['tokenLinkId'] && !(typeof data['tokenLinkId'] === 'string' || data['tokenLinkId'] instanceof String)) {
            throw new Error("Expected the field `tokenLinkId` to be a primitive type in the JSON string but got " + data['tokenLinkId']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['expireOn'] && !(typeof data['expireOn'] === 'string' || data['expireOn'] instanceof String)) {
            throw new Error("Expected the field `expireOn` to be a primitive type in the JSON string but got " + data['expireOn']);
        }
        // ensure the json data is a string
        if (data['createdOn'] && !(typeof data['createdOn'] === 'string' || data['createdOn'] instanceof String)) {
            throw new Error("Expected the field `createdOn` to be a primitive type in the JSON string but got " + data['createdOn']);
        }
        // ensure the json data is a string
        if (data['modifiedOn'] && !(typeof data['modifiedOn'] === 'string' || data['modifiedOn'] instanceof String)) {
            throw new Error("Expected the field `modifiedOn` to be a primitive type in the JSON string but got " + data['modifiedOn']);
        }
        // ensure the json data is a string
        if (data['createdBy'] && !(typeof data['createdBy'] === 'string' || data['createdBy'] instanceof String)) {
            throw new Error("Expected the field `createdBy` to be a primitive type in the JSON string but got " + data['createdBy']);
        }
        // ensure the json data is a string
        if (data['modifiedBy'] && !(typeof data['modifiedBy'] === 'string' || data['modifiedBy'] instanceof String)) {
            throw new Error("Expected the field `modifiedBy` to be a primitive type in the JSON string but got " + data['modifiedBy']);
        }
        // ensure the json data is a string
        if (data['tokenLinkStatus'] && !(typeof data['tokenLinkStatus'] === 'string' || data['tokenLinkStatus'] instanceof String)) {
            throw new Error("Expected the field `tokenLinkStatus` to be a primitive type in the JSON string but got " + data['tokenLinkStatus']);
        }
        // ensure the json data is a string
        if (data['responseType'] && !(typeof data['responseType'] === 'string' || data['responseType'] instanceof String)) {
            throw new Error("Expected the field `responseType` to be a primitive type in the JSON string but got " + data['responseType']);
        }
        // validate the optional field `callBackParameters`
        if (data['callBackParameters']) { // data not null
          PaymentLinkResponseCallbackParameters.validateJSON(data['callBackParameters']);
        }
        // validate the optional field `intent`
        if (data['intent']) { // data not null
          SecureTokenLinkResponseIntent.validateJSON(data['intent']);
        }
        if (data['customers']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['customers'])) {
                throw new Error("Expected the field `customers` to be an array in the JSON data but got " + data['customers']);
            }
            // validate the optional field `customers` (array)
            for (const item of data['customers']) {
                SecureTokenLinkResponseCustomersInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} merchantId
 */
SecureTokenLinkResponse.prototype['merchantId'] = undefined;

/**
 * @member {String} tokenLinkId
 */
SecureTokenLinkResponse.prototype['tokenLinkId'] = undefined;

/**
 * @member {String} title
 */
SecureTokenLinkResponse.prototype['title'] = undefined;

/**
 * @member {String} url
 */
SecureTokenLinkResponse.prototype['url'] = undefined;

/**
 * @member {String} expireOn
 */
SecureTokenLinkResponse.prototype['expireOn'] = undefined;

/**
 * @member {String} createdOn
 */
SecureTokenLinkResponse.prototype['createdOn'] = undefined;

/**
 * @member {String} modifiedOn
 */
SecureTokenLinkResponse.prototype['modifiedOn'] = undefined;

/**
 * @member {String} createdBy
 */
SecureTokenLinkResponse.prototype['createdBy'] = undefined;

/**
 * @member {String} modifiedBy
 */
SecureTokenLinkResponse.prototype['modifiedBy'] = undefined;

/**
 * @member {module:model/SecureTokenLinkResponse.TokenLinkStatusEnum} tokenLinkStatus
 */
SecureTokenLinkResponse.prototype['tokenLinkStatus'] = undefined;

/**
 * @member {module:model/SecureTokenLinkResponse.ResponseTypeEnum} responseType
 */
SecureTokenLinkResponse.prototype['responseType'] = undefined;

/**
 * @member {module:model/PaymentLinkResponseCallbackParameters} callBackParameters
 */
SecureTokenLinkResponse.prototype['callBackParameters'] = undefined;

/**
 * @member {module:model/SecureTokenLinkResponseIntent} intent
 */
SecureTokenLinkResponse.prototype['intent'] = undefined;

/**
 * @member {Array.<module:model/SecureTokenLinkResponseCustomersInner>} customers
 */
SecureTokenLinkResponse.prototype['customers'] = undefined;





/**
 * Allowed values for the <code>tokenLinkStatus</code> property.
 * @enum {String}
 * @readonly
 */
SecureTokenLinkResponse['TokenLinkStatusEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Created"
     * @const
     */
    "Created": "Created",

    /**
     * value: "Completed"
     * @const
     */
    "Completed": "Completed",

    /**
     * value: "Expired"
     * @const
     */
    "Expired": "Expired",

    /**
     * value: "Invalidated"
     * @const
     */
    "Invalidated": "Invalidated",

    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed"
};


/**
 * Allowed values for the <code>responseType</code> property.
 * @enum {String}
 * @readonly
 */
SecureTokenLinkResponse['ResponseTypeEnum'] = {

    /**
     * value: "OnScreen"
     * @const
     */
    "OnScreen": "OnScreen",

    /**
     * value: "CallBack"
     * @const
     */
    "CallBack": "CallBack"
};



export default SecureTokenLinkResponse;

