/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SecureTransactionDetailDTOTenderInfo from './SecureTransactionDetailDTOTenderInfo';
import TransactionPaymentResponseBillingContact from './TransactionPaymentResponseBillingContact';
import TransactionPaymentResponseRefundOrigin from './TransactionPaymentResponseRefundOrigin';
import TransactionPaymentResponseTransactionResult from './TransactionPaymentResponseTransactionResult';

/**
 * The SecureTransactionDetailDTO model module.
 * @module model/SecureTransactionDetailDTO
 * @version 2.3
 */
class SecureTransactionDetailDTO {
    /**
     * Constructs a new <code>SecureTransactionDetailDTO</code>.
     * @alias module:model/SecureTransactionDetailDTO
     */
    constructor() { 
        
        SecureTransactionDetailDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SecureTransactionDetailDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecureTransactionDetailDTO} obj Optional instance to populate.
     * @return {module:model/SecureTransactionDetailDTO} The populated <code>SecureTransactionDetailDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecureTransactionDetailDTO();

            if (data.hasOwnProperty('transactionId')) {
                obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
            }
            if (data.hasOwnProperty('traceNumber')) {
                obj['traceNumber'] = ApiClient.convertToType(data['traceNumber'], 'String');
            }
            if (data.hasOwnProperty('transactionCode')) {
                obj['transactionCode'] = ApiClient.convertToType(data['transactionCode'], 'String');
            }
            if (data.hasOwnProperty('transactionOrigin')) {
                obj['transactionOrigin'] = ApiClient.convertToType(data['transactionOrigin'], 'String');
            }
            if (data.hasOwnProperty('refundOrigin')) {
                obj['refundOrigin'] = TransactionPaymentResponseRefundOrigin.constructFromObject(data['refundOrigin']);
            }
            if (data.hasOwnProperty('billingContact')) {
                obj['billingContact'] = TransactionPaymentResponseBillingContact.constructFromObject(data['billingContact']);
            }
            if (data.hasOwnProperty('shippingContact')) {
                obj['shippingContact'] = TransactionPaymentResponseBillingContact.constructFromObject(data['shippingContact']);
            }
            if (data.hasOwnProperty('referenceTransactionId')) {
                obj['referenceTransactionId'] = ApiClient.convertToType(data['referenceTransactionId'], 'String');
            }
            if (data.hasOwnProperty('transactionDate')) {
                obj['transactionDate'] = ApiClient.convertToType(data['transactionDate'], 'String');
            }
            if (data.hasOwnProperty('merchantId')) {
                obj['merchantId'] = ApiClient.convertToType(data['merchantId'], 'String');
            }
            if (data.hasOwnProperty('ipAddress')) {
                obj['ipAddress'] = ApiClient.convertToType(data['ipAddress'], 'String');
            }
            if (data.hasOwnProperty('operationType')) {
                obj['operationType'] = ApiClient.convertToType(data['operationType'], 'String');
            }
            if (data.hasOwnProperty('channelType')) {
                obj['channelType'] = ApiClient.convertToType(data['channelType'], 'String');
            }
            if (data.hasOwnProperty('processMethod')) {
                obj['processMethod'] = ApiClient.convertToType(data['processMethod'], 'String');
            }
            if (data.hasOwnProperty('processorName')) {
                obj['processorName'] = ApiClient.convertToType(data['processorName'], 'String');
            }
            if (data.hasOwnProperty('isDebit')) {
                obj['isDebit'] = ApiClient.convertToType(data['isDebit'], 'Boolean');
            }
            if (data.hasOwnProperty('tenderInfo')) {
                obj['tenderInfo'] = SecureTransactionDetailDTOTenderInfo.constructFromObject(data['tenderInfo']);
            }
            if (data.hasOwnProperty('referenceCustomerId')) {
                obj['referenceCustomerId'] = ApiClient.convertToType(data['referenceCustomerId'], 'String');
            }
            if (data.hasOwnProperty('invoiceNo')) {
                obj['invoiceNo'] = ApiClient.convertToType(data['invoiceNo'], 'String');
            }
            if (data.hasOwnProperty('referenceNo')) {
                obj['referenceNo'] = ApiClient.convertToType(data['referenceNo'], 'String');
            }
            if (data.hasOwnProperty('remarks')) {
                obj['remarks'] = ApiClient.convertToType(data['remarks'], 'String');
            }
            if (data.hasOwnProperty('recurringType')) {
                obj['recurringType'] = ApiClient.convertToType(data['recurringType'], 'String');
            }
            if (data.hasOwnProperty('recurringId')) {
                obj['recurringId'] = ApiClient.convertToType(data['recurringId'], 'String');
            }
            if (data.hasOwnProperty('installmentNumber')) {
                obj['installmentNumber'] = ApiClient.convertToType(data['installmentNumber'], 'Number');
            }
            if (data.hasOwnProperty('installmentCount')) {
                obj['installmentCount'] = ApiClient.convertToType(data['installmentCount'], 'Number');
            }
            if (data.hasOwnProperty('allowDuplicates')) {
                obj['allowDuplicates'] = ApiClient.convertToType(data['allowDuplicates'], 'Boolean');
            }
            if (data.hasOwnProperty('verificationEnabled')) {
                obj['verificationEnabled'] = ApiClient.convertToType(data['verificationEnabled'], 'Boolean');
            }
            if (data.hasOwnProperty('sentSuccessNotification')) {
                obj['sentSuccessNotification'] = ApiClient.convertToType(data['sentSuccessNotification'], 'Boolean');
            }
            if (data.hasOwnProperty('sentFailedNotification')) {
                obj['sentFailedNotification'] = ApiClient.convertToType(data['sentFailedNotification'], 'Boolean');
            }
            if (data.hasOwnProperty('trainingMode')) {
                obj['trainingMode'] = ApiClient.convertToType(data['trainingMode'], 'Boolean');
            }
            if (data.hasOwnProperty('terminalId')) {
                obj['terminalId'] = ApiClient.convertToType(data['terminalId'], 'String');
            }
            if (data.hasOwnProperty('isOffline')) {
                obj['isOffline'] = ApiClient.convertToType(data['isOffline'], 'Boolean');
            }
            if (data.hasOwnProperty('transactionStatus')) {
                obj['transactionStatus'] = ApiClient.convertToType(data['transactionStatus'], 'String');
            }
            if (data.hasOwnProperty('previousTransactionStatus')) {
                obj['previousTransactionStatus'] = ApiClient.convertToType(data['previousTransactionStatus'], 'String');
            }
            if (data.hasOwnProperty('transactionResult')) {
                obj['transactionResult'] = TransactionPaymentResponseTransactionResult.constructFromObject(data['transactionResult']);
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
            if (data.hasOwnProperty('partnerId')) {
                obj['partnerId'] = ApiClient.convertToType(data['partnerId'], 'String');
            }
            if (data.hasOwnProperty('orderId')) {
                obj['orderId'] = ApiClient.convertToType(data['orderId'], 'String');
            }
            if (data.hasOwnProperty('invoiceId')) {
                obj['invoiceId'] = ApiClient.convertToType(data['invoiceId'], 'String');
            }
            if (data.hasOwnProperty('paymentLinkId')) {
                obj['paymentLinkId'] = ApiClient.convertToType(data['paymentLinkId'], 'String');
            }
            if (data.hasOwnProperty('additionalFields')) {
                obj['additionalFields'] = ApiClient.convertToType(data['additionalFields'], 'String');
            }
            if (data.hasOwnProperty('settlementDate')) {
                obj['settlementDate'] = ApiClient.convertToType(data['settlementDate'], 'String');
            }
            if (data.hasOwnProperty('issuer')) {
                obj['issuer'] = ApiClient.convertToType(data['issuer'], 'String');
            }
            if (data.hasOwnProperty('paymentReference')) {
                obj['paymentReference'] = ApiClient.convertToType(data['paymentReference'], 'String');
            }
            if (data.hasOwnProperty('refundReference')) {
                obj['refundReference'] = ApiClient.convertToType(data['refundReference'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SecureTransactionDetailDTO</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SecureTransactionDetailDTO</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['transactionId'] && !(typeof data['transactionId'] === 'string' || data['transactionId'] instanceof String)) {
            throw new Error("Expected the field `transactionId` to be a primitive type in the JSON string but got " + data['transactionId']);
        }
        // ensure the json data is a string
        if (data['traceNumber'] && !(typeof data['traceNumber'] === 'string' || data['traceNumber'] instanceof String)) {
            throw new Error("Expected the field `traceNumber` to be a primitive type in the JSON string but got " + data['traceNumber']);
        }
        // ensure the json data is a string
        if (data['transactionCode'] && !(typeof data['transactionCode'] === 'string' || data['transactionCode'] instanceof String)) {
            throw new Error("Expected the field `transactionCode` to be a primitive type in the JSON string but got " + data['transactionCode']);
        }
        // ensure the json data is a string
        if (data['transactionOrigin'] && !(typeof data['transactionOrigin'] === 'string' || data['transactionOrigin'] instanceof String)) {
            throw new Error("Expected the field `transactionOrigin` to be a primitive type in the JSON string but got " + data['transactionOrigin']);
        }
        // validate the optional field `refundOrigin`
        if (data['refundOrigin']) { // data not null
          TransactionPaymentResponseRefundOrigin.validateJSON(data['refundOrigin']);
        }
        // validate the optional field `billingContact`
        if (data['billingContact']) { // data not null
          TransactionPaymentResponseBillingContact.validateJSON(data['billingContact']);
        }
        // validate the optional field `shippingContact`
        if (data['shippingContact']) { // data not null
          TransactionPaymentResponseBillingContact.validateJSON(data['shippingContact']);
        }
        // ensure the json data is a string
        if (data['referenceTransactionId'] && !(typeof data['referenceTransactionId'] === 'string' || data['referenceTransactionId'] instanceof String)) {
            throw new Error("Expected the field `referenceTransactionId` to be a primitive type in the JSON string but got " + data['referenceTransactionId']);
        }
        // ensure the json data is a string
        if (data['transactionDate'] && !(typeof data['transactionDate'] === 'string' || data['transactionDate'] instanceof String)) {
            throw new Error("Expected the field `transactionDate` to be a primitive type in the JSON string but got " + data['transactionDate']);
        }
        // ensure the json data is a string
        if (data['merchantId'] && !(typeof data['merchantId'] === 'string' || data['merchantId'] instanceof String)) {
            throw new Error("Expected the field `merchantId` to be a primitive type in the JSON string but got " + data['merchantId']);
        }
        // ensure the json data is a string
        if (data['ipAddress'] && !(typeof data['ipAddress'] === 'string' || data['ipAddress'] instanceof String)) {
            throw new Error("Expected the field `ipAddress` to be a primitive type in the JSON string but got " + data['ipAddress']);
        }
        // ensure the json data is a string
        if (data['operationType'] && !(typeof data['operationType'] === 'string' || data['operationType'] instanceof String)) {
            throw new Error("Expected the field `operationType` to be a primitive type in the JSON string but got " + data['operationType']);
        }
        // ensure the json data is a string
        if (data['channelType'] && !(typeof data['channelType'] === 'string' || data['channelType'] instanceof String)) {
            throw new Error("Expected the field `channelType` to be a primitive type in the JSON string but got " + data['channelType']);
        }
        // ensure the json data is a string
        if (data['processMethod'] && !(typeof data['processMethod'] === 'string' || data['processMethod'] instanceof String)) {
            throw new Error("Expected the field `processMethod` to be a primitive type in the JSON string but got " + data['processMethod']);
        }
        // ensure the json data is a string
        if (data['processorName'] && !(typeof data['processorName'] === 'string' || data['processorName'] instanceof String)) {
            throw new Error("Expected the field `processorName` to be a primitive type in the JSON string but got " + data['processorName']);
        }
        // validate the optional field `tenderInfo`
        if (data['tenderInfo']) { // data not null
          SecureTransactionDetailDTOTenderInfo.validateJSON(data['tenderInfo']);
        }
        // ensure the json data is a string
        if (data['referenceCustomerId'] && !(typeof data['referenceCustomerId'] === 'string' || data['referenceCustomerId'] instanceof String)) {
            throw new Error("Expected the field `referenceCustomerId` to be a primitive type in the JSON string but got " + data['referenceCustomerId']);
        }
        // ensure the json data is a string
        if (data['invoiceNo'] && !(typeof data['invoiceNo'] === 'string' || data['invoiceNo'] instanceof String)) {
            throw new Error("Expected the field `invoiceNo` to be a primitive type in the JSON string but got " + data['invoiceNo']);
        }
        // ensure the json data is a string
        if (data['referenceNo'] && !(typeof data['referenceNo'] === 'string' || data['referenceNo'] instanceof String)) {
            throw new Error("Expected the field `referenceNo` to be a primitive type in the JSON string but got " + data['referenceNo']);
        }
        // ensure the json data is a string
        if (data['remarks'] && !(typeof data['remarks'] === 'string' || data['remarks'] instanceof String)) {
            throw new Error("Expected the field `remarks` to be a primitive type in the JSON string but got " + data['remarks']);
        }
        // ensure the json data is a string
        if (data['recurringType'] && !(typeof data['recurringType'] === 'string' || data['recurringType'] instanceof String)) {
            throw new Error("Expected the field `recurringType` to be a primitive type in the JSON string but got " + data['recurringType']);
        }
        // ensure the json data is a string
        if (data['recurringId'] && !(typeof data['recurringId'] === 'string' || data['recurringId'] instanceof String)) {
            throw new Error("Expected the field `recurringId` to be a primitive type in the JSON string but got " + data['recurringId']);
        }
        // ensure the json data is a string
        if (data['terminalId'] && !(typeof data['terminalId'] === 'string' || data['terminalId'] instanceof String)) {
            throw new Error("Expected the field `terminalId` to be a primitive type in the JSON string but got " + data['terminalId']);
        }
        // ensure the json data is a string
        if (data['transactionStatus'] && !(typeof data['transactionStatus'] === 'string' || data['transactionStatus'] instanceof String)) {
            throw new Error("Expected the field `transactionStatus` to be a primitive type in the JSON string but got " + data['transactionStatus']);
        }
        // ensure the json data is a string
        if (data['previousTransactionStatus'] && !(typeof data['previousTransactionStatus'] === 'string' || data['previousTransactionStatus'] instanceof String)) {
            throw new Error("Expected the field `previousTransactionStatus` to be a primitive type in the JSON string but got " + data['previousTransactionStatus']);
        }
        // validate the optional field `transactionResult`
        if (data['transactionResult']) { // data not null
          TransactionPaymentResponseTransactionResult.validateJSON(data['transactionResult']);
        }
        // ensure the json data is a string
        if (data['partnerId'] && !(typeof data['partnerId'] === 'string' || data['partnerId'] instanceof String)) {
            throw new Error("Expected the field `partnerId` to be a primitive type in the JSON string but got " + data['partnerId']);
        }
        // ensure the json data is a string
        if (data['orderId'] && !(typeof data['orderId'] === 'string' || data['orderId'] instanceof String)) {
            throw new Error("Expected the field `orderId` to be a primitive type in the JSON string but got " + data['orderId']);
        }
        // ensure the json data is a string
        if (data['invoiceId'] && !(typeof data['invoiceId'] === 'string' || data['invoiceId'] instanceof String)) {
            throw new Error("Expected the field `invoiceId` to be a primitive type in the JSON string but got " + data['invoiceId']);
        }
        // ensure the json data is a string
        if (data['paymentLinkId'] && !(typeof data['paymentLinkId'] === 'string' || data['paymentLinkId'] instanceof String)) {
            throw new Error("Expected the field `paymentLinkId` to be a primitive type in the JSON string but got " + data['paymentLinkId']);
        }
        // ensure the json data is a string
        if (data['additionalFields'] && !(typeof data['additionalFields'] === 'string' || data['additionalFields'] instanceof String)) {
            throw new Error("Expected the field `additionalFields` to be a primitive type in the JSON string but got " + data['additionalFields']);
        }
        // ensure the json data is a string
        if (data['settlementDate'] && !(typeof data['settlementDate'] === 'string' || data['settlementDate'] instanceof String)) {
            throw new Error("Expected the field `settlementDate` to be a primitive type in the JSON string but got " + data['settlementDate']);
        }
        // ensure the json data is a string
        if (data['issuer'] && !(typeof data['issuer'] === 'string' || data['issuer'] instanceof String)) {
            throw new Error("Expected the field `issuer` to be a primitive type in the JSON string but got " + data['issuer']);
        }
        // ensure the json data is a string
        if (data['paymentReference'] && !(typeof data['paymentReference'] === 'string' || data['paymentReference'] instanceof String)) {
            throw new Error("Expected the field `paymentReference` to be a primitive type in the JSON string but got " + data['paymentReference']);
        }
        // ensure the json data is a string
        if (data['refundReference'] && !(typeof data['refundReference'] === 'string' || data['refundReference'] instanceof String)) {
            throw new Error("Expected the field `refundReference` to be a primitive type in the JSON string but got " + data['refundReference']);
        }

        return true;
    }


}



/**
 * @member {String} transactionId
 */
SecureTransactionDetailDTO.prototype['transactionId'] = undefined;

/**
 * @member {String} traceNumber
 */
SecureTransactionDetailDTO.prototype['traceNumber'] = undefined;

/**
 * @member {String} transactionCode
 */
SecureTransactionDetailDTO.prototype['transactionCode'] = undefined;

/**
 * @member {module:model/SecureTransactionDetailDTO.TransactionOriginEnum} transactionOrigin
 */
SecureTransactionDetailDTO.prototype['transactionOrigin'] = undefined;

/**
 * @member {module:model/TransactionPaymentResponseRefundOrigin} refundOrigin
 */
SecureTransactionDetailDTO.prototype['refundOrigin'] = undefined;

/**
 * @member {module:model/TransactionPaymentResponseBillingContact} billingContact
 */
SecureTransactionDetailDTO.prototype['billingContact'] = undefined;

/**
 * @member {module:model/TransactionPaymentResponseBillingContact} shippingContact
 */
SecureTransactionDetailDTO.prototype['shippingContact'] = undefined;

/**
 * @member {String} referenceTransactionId
 */
SecureTransactionDetailDTO.prototype['referenceTransactionId'] = undefined;

/**
 * @member {String} transactionDate
 */
SecureTransactionDetailDTO.prototype['transactionDate'] = undefined;

/**
 * @member {String} merchantId
 */
SecureTransactionDetailDTO.prototype['merchantId'] = undefined;

/**
 * @member {String} ipAddress
 */
SecureTransactionDetailDTO.prototype['ipAddress'] = undefined;

/**
 * @member {module:model/SecureTransactionDetailDTO.OperationTypeEnum} operationType
 */
SecureTransactionDetailDTO.prototype['operationType'] = undefined;

/**
 * @member {module:model/SecureTransactionDetailDTO.ChannelTypeEnum} channelType
 */
SecureTransactionDetailDTO.prototype['channelType'] = undefined;

/**
 * @member {module:model/SecureTransactionDetailDTO.ProcessMethodEnum} processMethod
 */
SecureTransactionDetailDTO.prototype['processMethod'] = undefined;

/**
 * @member {String} processorName
 */
SecureTransactionDetailDTO.prototype['processorName'] = undefined;

/**
 * @member {Boolean} isDebit
 */
SecureTransactionDetailDTO.prototype['isDebit'] = undefined;

/**
 * @member {module:model/SecureTransactionDetailDTOTenderInfo} tenderInfo
 */
SecureTransactionDetailDTO.prototype['tenderInfo'] = undefined;

/**
 * @member {String} referenceCustomerId
 */
SecureTransactionDetailDTO.prototype['referenceCustomerId'] = undefined;

/**
 * @member {String} invoiceNo
 */
SecureTransactionDetailDTO.prototype['invoiceNo'] = undefined;

/**
 * @member {String} referenceNo
 */
SecureTransactionDetailDTO.prototype['referenceNo'] = undefined;

/**
 * @member {String} remarks
 */
SecureTransactionDetailDTO.prototype['remarks'] = undefined;

/**
 * @member {module:model/SecureTransactionDetailDTO.RecurringTypeEnum} recurringType
 */
SecureTransactionDetailDTO.prototype['recurringType'] = undefined;

/**
 * @member {String} recurringId
 */
SecureTransactionDetailDTO.prototype['recurringId'] = undefined;

/**
 * @member {Number} installmentNumber
 */
SecureTransactionDetailDTO.prototype['installmentNumber'] = undefined;

/**
 * @member {Number} installmentCount
 */
SecureTransactionDetailDTO.prototype['installmentCount'] = undefined;

/**
 * @member {Boolean} allowDuplicates
 */
SecureTransactionDetailDTO.prototype['allowDuplicates'] = undefined;

/**
 * @member {Boolean} verificationEnabled
 */
SecureTransactionDetailDTO.prototype['verificationEnabled'] = undefined;

/**
 * @member {Boolean} sentSuccessNotification
 */
SecureTransactionDetailDTO.prototype['sentSuccessNotification'] = undefined;

/**
 * @member {Boolean} sentFailedNotification
 */
SecureTransactionDetailDTO.prototype['sentFailedNotification'] = undefined;

/**
 * @member {Boolean} trainingMode
 */
SecureTransactionDetailDTO.prototype['trainingMode'] = undefined;

/**
 * @member {String} terminalId
 */
SecureTransactionDetailDTO.prototype['terminalId'] = undefined;

/**
 * @member {Boolean} isOffline
 */
SecureTransactionDetailDTO.prototype['isOffline'] = undefined;

/**
 * @member {module:model/SecureTransactionDetailDTO.TransactionStatusEnum} transactionStatus
 */
SecureTransactionDetailDTO.prototype['transactionStatus'] = undefined;

/**
 * @member {module:model/SecureTransactionDetailDTO.PreviousTransactionStatusEnum} previousTransactionStatus
 */
SecureTransactionDetailDTO.prototype['previousTransactionStatus'] = undefined;

/**
 * @member {module:model/TransactionPaymentResponseTransactionResult} transactionResult
 */
SecureTransactionDetailDTO.prototype['transactionResult'] = undefined;

/**
 * @member {Number} level
 */
SecureTransactionDetailDTO.prototype['level'] = undefined;

/**
 * @member {String} partnerId
 */
SecureTransactionDetailDTO.prototype['partnerId'] = undefined;

/**
 * @member {String} orderId
 */
SecureTransactionDetailDTO.prototype['orderId'] = undefined;

/**
 * @member {String} invoiceId
 */
SecureTransactionDetailDTO.prototype['invoiceId'] = undefined;

/**
 * @member {String} paymentLinkId
 */
SecureTransactionDetailDTO.prototype['paymentLinkId'] = undefined;

/**
 * @member {String} additionalFields
 */
SecureTransactionDetailDTO.prototype['additionalFields'] = undefined;

/**
 * @member {String} settlementDate
 */
SecureTransactionDetailDTO.prototype['settlementDate'] = undefined;

/**
 * @member {String} issuer
 */
SecureTransactionDetailDTO.prototype['issuer'] = undefined;

/**
 * @member {String} paymentReference
 */
SecureTransactionDetailDTO.prototype['paymentReference'] = undefined;

/**
 * @member {String} refundReference
 */
SecureTransactionDetailDTO.prototype['refundReference'] = undefined;





/**
 * Allowed values for the <code>transactionOrigin</code> property.
 * @enum {String}
 * @readonly
 */
SecureTransactionDetailDTO['TransactionOriginEnum'] = {

    /**
     * value: "Terminal"
     * @const
     */
    "Terminal": "Terminal",

    /**
     * value: "VirtualTerminal"
     * @const
     */
    "VirtualTerminal": "VirtualTerminal",

    /**
     * value: "WebForm"
     * @const
     */
    "WebForm": "WebForm",

    /**
     * value: "API"
     * @const
     */
    "API": "API",

    /**
     * value: "Schedule"
     * @const
     */
    "Schedule": "Schedule",

    /**
     * value: "Batch"
     * @const
     */
    "Batch": "Batch",

    /**
     * value: "PaymentIntent"
     * @const
     */
    "PaymentIntent": "PaymentIntent"
};


/**
 * Allowed values for the <code>operationType</code> property.
 * @enum {String}
 * @readonly
 */
SecureTransactionDetailDTO['OperationTypeEnum'] = {

    /**
     * value: "Sale"
     * @const
     */
    "Sale": "Sale",

    /**
     * value: "VerifyOnly"
     * @const
     */
    "VerifyOnly": "VerifyOnly",

    /**
     * value: "ForceSale"
     * @const
     */
    "ForceSale": "ForceSale",

    /**
     * value: "Adjust"
     * @const
     */
    "Adjust": "Adjust",

    /**
     * value: "Activate"
     * @const
     */
    "Activate": "Activate",

    /**
     * value: "Deactivate"
     * @const
     */
    "Deactivate": "Deactivate",

    /**
     * value: "Reload"
     * @const
     */
    "Reload": "Reload",

    /**
     * value: "Refund"
     * @const
     */
    "Refund": "Refund",

    /**
     * value: "Inquire"
     * @const
     */
    "Inquire": "Inquire",

    /**
     * value: "ReverseAuth"
     * @const
     */
    "ReverseAuth": "ReverseAuth"
};


/**
 * Allowed values for the <code>channelType</code> property.
 * @enum {String}
 * @readonly
 */
SecureTransactionDetailDTO['ChannelTypeEnum'] = {

    /**
     * value: "NotDefined"
     * @const
     */
    "NotDefined": "NotDefined",

    /**
     * value: "ACH"
     * @const
     */
    "ACH": "ACH",

    /**
     * value: "CreditCard"
     * @const
     */
    "CreditCard": "CreditCard",

    /**
     * value: "DebitCard"
     * @const
     */
    "DebitCard": "DebitCard"
};


/**
 * Allowed values for the <code>processMethod</code> property.
 * @enum {String}
 * @readonly
 */
SecureTransactionDetailDTO['ProcessMethodEnum'] = {

    /**
     * value: "NotDefined"
     * @const
     */
    "NotDefined": "NotDefined",

    /**
     * value: "ACH"
     * @const
     */
    "ACH": "ACH",

    /**
     * value: "CardNotPresent"
     * @const
     */
    "CardNotPresent": "CardNotPresent"
};


/**
 * Allowed values for the <code>recurringType</code> property.
 * @enum {String}
 * @readonly
 */
SecureTransactionDetailDTO['RecurringTypeEnum'] = {

    /**
     * value: "Installment"
     * @const
     */
    "Installment": "Installment",

    /**
     * value: "Billing"
     * @const
     */
    "Billing": "Billing",

    /**
     * value: "Custom"
     * @const
     */
    "Custom": "Custom"
};


/**
 * Allowed values for the <code>transactionStatus</code> property.
 * @enum {String}
 * @readonly
 */
SecureTransactionDetailDTO['TransactionStatusEnum'] = {

    /**
     * value: "Created"
     * @const
     */
    "Created": "Created",

    /**
     * value: "PendingForAuthorized"
     * @const
     */
    "PendingForAuthorized": "PendingForAuthorized",

    /**
     * value: "Authorized"
     * @const
     */
    "Authorized": "Authorized",

    /**
     * value: "Posted"
     * @const
     */
    "Posted": "Posted",

    /**
     * value: "Captured"
     * @const
     */
    "Captured": "Captured",

    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed",

    /**
     * value: "Returned"
     * @const
     */
    "Returned": "Returned",

    /**
     * value: "Chargeback"
     * @const
     */
    "Chargeback": "Chargeback",

    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled",

    /**
     * value: "Refunded"
     * @const
     */
    "Refunded": "Refunded",

    /**
     * value: "Approved"
     * @const
     */
    "Approved": "Approved",

    /**
     * value: "CancelAttempt"
     * @const
     */
    "CancelAttempt": "CancelAttempt",

    /**
     * value: "RefundAttempt"
     * @const
     */
    "RefundAttempt": "RefundAttempt",

    /**
     * value: "Hold"
     * @const
     */
    "Hold": "Hold",

    /**
     * value: "Denied"
     * @const
     */
    "Denied": "Denied",

    /**
     * value: "SettlementHold"
     * @const
     */
    "SettlementHold": "SettlementHold",

    /**
     * value: "Success"
     * @const
     */
    "Success": "Success",

    /**
     * value: "Retried"
     * @const
     */
    "Retried": "Retried",

    /**
     * value: "ReprocessAttempt"
     * @const
     */
    "ReprocessAttempt": "ReprocessAttempt",

    /**
     * value: "Reprocessed"
     * @const
     */
    "Reprocessed": "Reprocessed",

    /**
     * value: "ChargebackReversed"
     * @const
     */
    "ChargebackReversed": "ChargebackReversed",

    /**
     * value: "RefundedReversed"
     * @const
     */
    "RefundedReversed": "RefundedReversed",

    /**
     * value: "Paid"
     * @const
     */
    "Paid": "Paid",

    /**
     * value: "PaidChargeback"
     * @const
     */
    "PaidChargeback": "PaidChargeback",

    /**
     * value: "PaidChargebackReversed"
     * @const
     */
    "PaidChargebackReversed": "PaidChargebackReversed",

    /**
     * value: "PaidRefunded"
     * @const
     */
    "PaidRefunded": "PaidRefunded",

    /**
     * value: "PaidRefundedReversed"
     * @const
     */
    "PaidRefundedReversed": "PaidRefundedReversed",

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "Unknown"
     * @const
     */
    "Unknown": "Unknown"
};


/**
 * Allowed values for the <code>previousTransactionStatus</code> property.
 * @enum {String}
 * @readonly
 */
SecureTransactionDetailDTO['PreviousTransactionStatusEnum'] = {

    /**
     * value: "Created"
     * @const
     */
    "Created": "Created",

    /**
     * value: "PendingForAuthorized"
     * @const
     */
    "PendingForAuthorized": "PendingForAuthorized",

    /**
     * value: "Authorized"
     * @const
     */
    "Authorized": "Authorized",

    /**
     * value: "Posted"
     * @const
     */
    "Posted": "Posted",

    /**
     * value: "Captured"
     * @const
     */
    "Captured": "Captured",

    /**
     * value: "Failed"
     * @const
     */
    "Failed": "Failed",

    /**
     * value: "Returned"
     * @const
     */
    "Returned": "Returned",

    /**
     * value: "Chargeback"
     * @const
     */
    "Chargeback": "Chargeback",

    /**
     * value: "Cancelled"
     * @const
     */
    "Cancelled": "Cancelled",

    /**
     * value: "Refunded"
     * @const
     */
    "Refunded": "Refunded",

    /**
     * value: "Approved"
     * @const
     */
    "Approved": "Approved",

    /**
     * value: "CancelAttempt"
     * @const
     */
    "CancelAttempt": "CancelAttempt",

    /**
     * value: "RefundAttempt"
     * @const
     */
    "RefundAttempt": "RefundAttempt",

    /**
     * value: "Hold"
     * @const
     */
    "Hold": "Hold",

    /**
     * value: "Denied"
     * @const
     */
    "Denied": "Denied",

    /**
     * value: "SettlementHold"
     * @const
     */
    "SettlementHold": "SettlementHold",

    /**
     * value: "Success"
     * @const
     */
    "Success": "Success",

    /**
     * value: "Retried"
     * @const
     */
    "Retried": "Retried",

    /**
     * value: "ReprocessAttempt"
     * @const
     */
    "ReprocessAttempt": "ReprocessAttempt",

    /**
     * value: "Reprocessed"
     * @const
     */
    "Reprocessed": "Reprocessed",

    /**
     * value: "ChargebackReversed"
     * @const
     */
    "ChargebackReversed": "ChargebackReversed",

    /**
     * value: "RefundedReversed"
     * @const
     */
    "RefundedReversed": "RefundedReversed",

    /**
     * value: "Paid"
     * @const
     */
    "Paid": "Paid",

    /**
     * value: "PaidChargeback"
     * @const
     */
    "PaidChargeback": "PaidChargeback",

    /**
     * value: "PaidChargebackReversed"
     * @const
     */
    "PaidChargebackReversed": "PaidChargebackReversed",

    /**
     * value: "PaidRefunded"
     * @const
     */
    "PaidRefunded": "PaidRefunded",

    /**
     * value: "PaidRefundedReversed"
     * @const
     */
    "PaidRefundedReversed": "PaidRefundedReversed",

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "Unknown"
     * @const
     */
    "Unknown": "Unknown"
};



export default SecureTransactionDetailDTO;

