/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SecureVendorResponseDTORemittanceAddress model module.
 * @module model/SecureVendorResponseDTORemittanceAddress
 * @version 2.3
 */
class SecureVendorResponseDTORemittanceAddress {
    /**
     * Constructs a new <code>SecureVendorResponseDTORemittanceAddress</code>.
     * @alias module:model/SecureVendorResponseDTORemittanceAddress
     */
    constructor() { 
        
        SecureVendorResponseDTORemittanceAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SecureVendorResponseDTORemittanceAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecureVendorResponseDTORemittanceAddress} obj Optional instance to populate.
     * @return {module:model/SecureVendorResponseDTORemittanceAddress} The populated <code>SecureVendorResponseDTORemittanceAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecureVendorResponseDTORemittanceAddress();

            if (data.hasOwnProperty('attention')) {
                obj['attention'] = ApiClient.convertToType(data['attention'], 'String');
            }
            if (data.hasOwnProperty('addressLine1')) {
                obj['addressLine1'] = ApiClient.convertToType(data['addressLine1'], 'String');
            }
            if (data.hasOwnProperty('addressLine2')) {
                obj['addressLine2'] = ApiClient.convertToType(data['addressLine2'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
            if (data.hasOwnProperty('postalCode')) {
                obj['postalCode'] = ApiClient.convertToType(data['postalCode'], 'String');
            }
            if (data.hasOwnProperty('addressType')) {
                obj['addressType'] = ApiClient.convertToType(data['addressType'], 'String');
            }
            if (data.hasOwnProperty('addressSource')) {
                obj['addressSource'] = ApiClient.convertToType(data['addressSource'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SecureVendorResponseDTORemittanceAddress</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SecureVendorResponseDTORemittanceAddress</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['attention'] && !(typeof data['attention'] === 'string' || data['attention'] instanceof String)) {
            throw new Error("Expected the field `attention` to be a primitive type in the JSON string but got " + data['attention']);
        }
        // ensure the json data is a string
        if (data['addressLine1'] && !(typeof data['addressLine1'] === 'string' || data['addressLine1'] instanceof String)) {
            throw new Error("Expected the field `addressLine1` to be a primitive type in the JSON string but got " + data['addressLine1']);
        }
        // ensure the json data is a string
        if (data['addressLine2'] && !(typeof data['addressLine2'] === 'string' || data['addressLine2'] instanceof String)) {
            throw new Error("Expected the field `addressLine2` to be a primitive type in the JSON string but got " + data['addressLine2']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['country'] && !(typeof data['country'] === 'string' || data['country'] instanceof String)) {
            throw new Error("Expected the field `country` to be a primitive type in the JSON string but got " + data['country']);
        }
        // ensure the json data is a string
        if (data['postalCode'] && !(typeof data['postalCode'] === 'string' || data['postalCode'] instanceof String)) {
            throw new Error("Expected the field `postalCode` to be a primitive type in the JSON string but got " + data['postalCode']);
        }
        // ensure the json data is a string
        if (data['addressType'] && !(typeof data['addressType'] === 'string' || data['addressType'] instanceof String)) {
            throw new Error("Expected the field `addressType` to be a primitive type in the JSON string but got " + data['addressType']);
        }
        // ensure the json data is a string
        if (data['addressSource'] && !(typeof data['addressSource'] === 'string' || data['addressSource'] instanceof String)) {
            throw new Error("Expected the field `addressSource` to be a primitive type in the JSON string but got " + data['addressSource']);
        }

        return true;
    }


}



/**
 * Attention to (optional)
 * @member {String} attention
 */
SecureVendorResponseDTORemittanceAddress.prototype['attention'] = undefined;

/**
 * Address line 1
 * @member {String} addressLine1
 */
SecureVendorResponseDTORemittanceAddress.prototype['addressLine1'] = undefined;

/**
 * Address line 2 (optional)
 * @member {String} addressLine2
 */
SecureVendorResponseDTORemittanceAddress.prototype['addressLine2'] = undefined;

/**
 * City
 * @member {String} city
 */
SecureVendorResponseDTORemittanceAddress.prototype['city'] = undefined;

/**
 * State
 * @member {String} state
 */
SecureVendorResponseDTORemittanceAddress.prototype['state'] = undefined;

/**
 * Country
 * @member {String} country
 */
SecureVendorResponseDTORemittanceAddress.prototype['country'] = undefined;

/**
 * Postal code
 * @member {String} postalCode
 */
SecureVendorResponseDTORemittanceAddress.prototype['postalCode'] = undefined;

/**
 * @member {module:model/SecureVendorResponseDTORemittanceAddress.AddressTypeEnum} addressType
 */
SecureVendorResponseDTORemittanceAddress.prototype['addressType'] = undefined;

/**
 * @member {module:model/SecureVendorResponseDTORemittanceAddress.AddressSourceEnum} addressSource
 */
SecureVendorResponseDTORemittanceAddress.prototype['addressSource'] = undefined;





/**
 * Allowed values for the <code>addressType</code> property.
 * @enum {String}
 * @readonly
 */
SecureVendorResponseDTORemittanceAddress['AddressTypeEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Remittance"
     * @const
     */
    "Remittance": "Remittance",

    /**
     * value: "Correspondence"
     * @const
     */
    "Correspondence": "Correspondence",

    /**
     * value: "Physical"
     * @const
     */
    "Physical": "Physical"
};


/**
 * Allowed values for the <code>addressSource</code> property.
 * @enum {String}
 * @readonly
 */
SecureVendorResponseDTORemittanceAddress['AddressSourceEnum'] = {

    /**
     * value: "NA"
     * @const
     */
    "NA": "NA",

    /**
     * value: "Manual"
     * @const
     */
    "Manual": "Manual",

    /**
     * value: "Smarty_lookup"
     * @const
     */
    "Smarty_lookup": "Smarty_lookup"
};



export default SecureVendorResponseDTORemittanceAddress;

