/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SecureTokenLinkExpiredResponse model module.
 * @module model/SecureTokenLinkExpiredResponse
 * @version 2.3
 */
class SecureTokenLinkExpiredResponse {
    /**
     * Constructs a new <code>SecureTokenLinkExpiredResponse</code>.
     * @alias module:model/SecureTokenLinkExpiredResponse
     */
    constructor() { 
        
        SecureTokenLinkExpiredResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SecureTokenLinkExpiredResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecureTokenLinkExpiredResponse} obj Optional instance to populate.
     * @return {module:model/SecureTokenLinkExpiredResponse} The populated <code>SecureTokenLinkExpiredResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecureTokenLinkExpiredResponse();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SecureTokenLinkExpiredResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SecureTokenLinkExpiredResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}



/**
 * @member {String} message
 */
SecureTokenLinkExpiredResponse.prototype['message'] = undefined;






export default SecureTokenLinkExpiredResponse;

