/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SecurePaymentLinkRequest model module.
 * @module model/SecurePaymentLinkRequest
 * @version 2.3
 */
class SecurePaymentLinkRequest {
    /**
     * Constructs a new <code>SecurePaymentLinkRequest</code>.
     * @alias module:model/SecurePaymentLinkRequest
     * @param paymentLinkId {String} 
     */
    constructor(paymentLinkId) { 
        
        SecurePaymentLinkRequest.initialize(this, paymentLinkId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, paymentLinkId) { 
        obj['paymentLinkId'] = paymentLinkId;
    }

    /**
     * Constructs a <code>SecurePaymentLinkRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecurePaymentLinkRequest} obj Optional instance to populate.
     * @return {module:model/SecurePaymentLinkRequest} The populated <code>SecurePaymentLinkRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecurePaymentLinkRequest();

            if (data.hasOwnProperty('paymentLinkId')) {
                obj['paymentLinkId'] = ApiClient.convertToType(data['paymentLinkId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SecurePaymentLinkRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SecurePaymentLinkRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SecurePaymentLinkRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['paymentLinkId'] && !(typeof data['paymentLinkId'] === 'string' || data['paymentLinkId'] instanceof String)) {
            throw new Error("Expected the field `paymentLinkId` to be a primitive type in the JSON string but got " + data['paymentLinkId']);
        }

        return true;
    }


}

SecurePaymentLinkRequest.RequiredProperties = ["paymentLinkId"];

/**
 * @member {String} paymentLinkId
 */
SecurePaymentLinkRequest.prototype['paymentLinkId'] = undefined;






export default SecurePaymentLinkRequest;

