/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TokenLinkSecureRequestIntent model module.
 * @module model/TokenLinkSecureRequestIntent
 * @version 2.3
 */
class TokenLinkSecureRequestIntent {
    /**
     * Constructs a new <code>TokenLinkSecureRequestIntent</code>.
     * @alias module:model/TokenLinkSecureRequestIntent
     * @param paymentTypes {Array.<module:model/TokenLinkSecureRequestIntent.PaymentTypesEnum>} 
     */
    constructor(paymentTypes) { 
        
        TokenLinkSecureRequestIntent.initialize(this, paymentTypes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, paymentTypes) { 
        obj['paymentTypes'] = paymentTypes;
    }

    /**
     * Constructs a <code>TokenLinkSecureRequestIntent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenLinkSecureRequestIntent} obj Optional instance to populate.
     * @return {module:model/TokenLinkSecureRequestIntent} The populated <code>TokenLinkSecureRequestIntent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenLinkSecureRequestIntent();

            if (data.hasOwnProperty('paymentTypes')) {
                obj['paymentTypes'] = ApiClient.convertToType(data['paymentTypes'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TokenLinkSecureRequestIntent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TokenLinkSecureRequestIntent</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TokenLinkSecureRequestIntent.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['paymentTypes'])) {
            throw new Error("Expected the field `paymentTypes` to be an array in the JSON data but got " + data['paymentTypes']);
        }

        return true;
    }


}

TokenLinkSecureRequestIntent.RequiredProperties = ["paymentTypes"];

/**
 * @member {Array.<module:model/TokenLinkSecureRequestIntent.PaymentTypesEnum>} paymentTypes
 */
TokenLinkSecureRequestIntent.prototype['paymentTypes'] = undefined;





/**
 * Allowed values for the <code>paymentTypes</code> property.
 * @enum {String}
 * @readonly
 */
TokenLinkSecureRequestIntent['PaymentTypesEnum'] = {

    /**
     * value: "CreditCard"
     * @const
     */
    "CreditCard": "CreditCard",

    /**
     * value: "DebitCard"
     * @const
     */
    "DebitCard": "DebitCard",

    /**
     * value: "ACH"
     * @const
     */
    "ACH": "ACH"
};



export default TokenLinkSecureRequestIntent;

