/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TokenLinkSecureRequestCustomersInnerAddress model module.
 * @module model/TokenLinkSecureRequestCustomersInnerAddress
 * @version 2.3
 */
class TokenLinkSecureRequestCustomersInnerAddress {
    /**
     * Constructs a new <code>TokenLinkSecureRequestCustomersInnerAddress</code>.
     * @alias module:model/TokenLinkSecureRequestCustomersInnerAddress
     */
    constructor() { 
        
        TokenLinkSecureRequestCustomersInnerAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TokenLinkSecureRequestCustomersInnerAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenLinkSecureRequestCustomersInnerAddress} obj Optional instance to populate.
     * @return {module:model/TokenLinkSecureRequestCustomersInnerAddress} The populated <code>TokenLinkSecureRequestCustomersInnerAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenLinkSecureRequestCustomersInnerAddress();

            if (data.hasOwnProperty('AddressLine1')) {
                obj['AddressLine1'] = ApiClient.convertToType(data['AddressLine1'], 'String');
            }
            if (data.hasOwnProperty('AddressLine2')) {
                obj['AddressLine2'] = ApiClient.convertToType(data['AddressLine2'], 'String');
            }
            if (data.hasOwnProperty('City')) {
                obj['City'] = ApiClient.convertToType(data['City'], 'String');
            }
            if (data.hasOwnProperty('State')) {
                obj['State'] = ApiClient.convertToType(data['State'], 'String');
            }
            if (data.hasOwnProperty('Country')) {
                obj['Country'] = ApiClient.convertToType(data['Country'], 'Number');
            }
            if (data.hasOwnProperty('PostalCode')) {
                obj['PostalCode'] = ApiClient.convertToType(data['PostalCode'], 'String');
            }
            if (data.hasOwnProperty('TimeZone')) {
                obj['TimeZone'] = ApiClient.convertToType(data['TimeZone'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TokenLinkSecureRequestCustomersInnerAddress</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TokenLinkSecureRequestCustomersInnerAddress</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['AddressLine1'] && !(typeof data['AddressLine1'] === 'string' || data['AddressLine1'] instanceof String)) {
            throw new Error("Expected the field `AddressLine1` to be a primitive type in the JSON string but got " + data['AddressLine1']);
        }
        // ensure the json data is a string
        if (data['AddressLine2'] && !(typeof data['AddressLine2'] === 'string' || data['AddressLine2'] instanceof String)) {
            throw new Error("Expected the field `AddressLine2` to be a primitive type in the JSON string but got " + data['AddressLine2']);
        }
        // ensure the json data is a string
        if (data['City'] && !(typeof data['City'] === 'string' || data['City'] instanceof String)) {
            throw new Error("Expected the field `City` to be a primitive type in the JSON string but got " + data['City']);
        }
        // ensure the json data is a string
        if (data['State'] && !(typeof data['State'] === 'string' || data['State'] instanceof String)) {
            throw new Error("Expected the field `State` to be a primitive type in the JSON string but got " + data['State']);
        }
        // ensure the json data is a string
        if (data['PostalCode'] && !(typeof data['PostalCode'] === 'string' || data['PostalCode'] instanceof String)) {
            throw new Error("Expected the field `PostalCode` to be a primitive type in the JSON string but got " + data['PostalCode']);
        }
        // ensure the json data is a string
        if (data['TimeZone'] && !(typeof data['TimeZone'] === 'string' || data['TimeZone'] instanceof String)) {
            throw new Error("Expected the field `TimeZone` to be a primitive type in the JSON string but got " + data['TimeZone']);
        }

        return true;
    }


}



/**
 * @member {String} AddressLine1
 */
TokenLinkSecureRequestCustomersInnerAddress.prototype['AddressLine1'] = undefined;

/**
 * @member {String} AddressLine2
 */
TokenLinkSecureRequestCustomersInnerAddress.prototype['AddressLine2'] = undefined;

/**
 * @member {String} City
 */
TokenLinkSecureRequestCustomersInnerAddress.prototype['City'] = undefined;

/**
 * @member {String} State
 */
TokenLinkSecureRequestCustomersInnerAddress.prototype['State'] = undefined;

/**
 * @member {Number} Country
 */
TokenLinkSecureRequestCustomersInnerAddress.prototype['Country'] = undefined;

/**
 * @member {String} PostalCode
 */
TokenLinkSecureRequestCustomersInnerAddress.prototype['PostalCode'] = undefined;

/**
 * @member {String} TimeZone
 */
TokenLinkSecureRequestCustomersInnerAddress.prototype['TimeZone'] = undefined;






export default TokenLinkSecureRequestCustomersInnerAddress;

