/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TransactionPaymentResponseBillingContactName model module.
 * @module model/TransactionPaymentResponseBillingContactName
 * @version 2.3
 */
class TransactionPaymentResponseBillingContactName {
    /**
     * Constructs a new <code>TransactionPaymentResponseBillingContactName</code>.
     * @alias module:model/TransactionPaymentResponseBillingContactName
     */
    constructor() { 
        
        TransactionPaymentResponseBillingContactName.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionPaymentResponseBillingContactName</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionPaymentResponseBillingContactName} obj Optional instance to populate.
     * @return {module:model/TransactionPaymentResponseBillingContactName} The populated <code>TransactionPaymentResponseBillingContactName</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionPaymentResponseBillingContactName();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('middleName')) {
                obj['middleName'] = ApiClient.convertToType(data['middleName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransactionPaymentResponseBillingContactName</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransactionPaymentResponseBillingContactName</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['middleName'] && !(typeof data['middleName'] === 'string' || data['middleName'] instanceof String)) {
            throw new Error("Expected the field `middleName` to be a primitive type in the JSON string but got " + data['middleName']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }

        return true;
    }


}



/**
 * @member {String} title
 */
TransactionPaymentResponseBillingContactName.prototype['title'] = undefined;

/**
 * @member {String} firstName
 */
TransactionPaymentResponseBillingContactName.prototype['firstName'] = undefined;

/**
 * @member {String} middleName
 */
TransactionPaymentResponseBillingContactName.prototype['middleName'] = undefined;

/**
 * @member {String} lastName
 */
TransactionPaymentResponseBillingContactName.prototype['lastName'] = undefined;






export default TransactionPaymentResponseBillingContactName;

