/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TransactionPaymentResponseTransactionResult model module.
 * @module model/TransactionPaymentResponseTransactionResult
 * @version 2.3
 */
class TransactionPaymentResponseTransactionResult {
    /**
     * Constructs a new <code>TransactionPaymentResponseTransactionResult</code>.
     * @alias module:model/TransactionPaymentResponseTransactionResult
     */
    constructor() { 
        
        TransactionPaymentResponseTransactionResult.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionPaymentResponseTransactionResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionPaymentResponseTransactionResult} obj Optional instance to populate.
     * @return {module:model/TransactionPaymentResponseTransactionResult} The populated <code>TransactionPaymentResponseTransactionResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionPaymentResponseTransactionResult();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('processorAuthCode')) {
                obj['processorAuthCode'] = ApiClient.convertToType(data['processorAuthCode'], 'String');
            }
            if (data.hasOwnProperty('traceNumber')) {
                obj['traceNumber'] = ApiClient.convertToType(data['traceNumber'], 'String');
            }
            if (data.hasOwnProperty('reasonCode')) {
                obj['reasonCode'] = ApiClient.convertToType(data['reasonCode'], 'String');
            }
            if (data.hasOwnProperty('reasonMessage')) {
                obj['reasonMessage'] = ApiClient.convertToType(data['reasonMessage'], 'String');
            }
            if (data.hasOwnProperty('additionResultData')) {
                obj['additionResultData'] = ApiClient.convertToType(data['additionResultData'], 'String');
            }
            if (data.hasOwnProperty('additionResultData2')) {
                obj['additionResultData2'] = ApiClient.convertToType(data['additionResultData2'], 'String');
            }
            if (data.hasOwnProperty('verificationStatus')) {
                obj['verificationStatus'] = ApiClient.convertToType(data['verificationStatus'], 'Boolean');
            }
            if (data.hasOwnProperty('verification1Code')) {
                obj['verification1Code'] = ApiClient.convertToType(data['verification1Code'], 'String');
            }
            if (data.hasOwnProperty('verification2Code')) {
                obj['verification2Code'] = ApiClient.convertToType(data['verification2Code'], 'String');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
            }
            if (data.hasOwnProperty('errorMessage')) {
                obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
            }
            if (data.hasOwnProperty('merchantReference')) {
                obj['merchantReference'] = ApiClient.convertToType(data['merchantReference'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransactionPaymentResponseTransactionResult</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransactionPaymentResponseTransactionResult</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['processorAuthCode'] && !(typeof data['processorAuthCode'] === 'string' || data['processorAuthCode'] instanceof String)) {
            throw new Error("Expected the field `processorAuthCode` to be a primitive type in the JSON string but got " + data['processorAuthCode']);
        }
        // ensure the json data is a string
        if (data['traceNumber'] && !(typeof data['traceNumber'] === 'string' || data['traceNumber'] instanceof String)) {
            throw new Error("Expected the field `traceNumber` to be a primitive type in the JSON string but got " + data['traceNumber']);
        }
        // ensure the json data is a string
        if (data['reasonCode'] && !(typeof data['reasonCode'] === 'string' || data['reasonCode'] instanceof String)) {
            throw new Error("Expected the field `reasonCode` to be a primitive type in the JSON string but got " + data['reasonCode']);
        }
        // ensure the json data is a string
        if (data['reasonMessage'] && !(typeof data['reasonMessage'] === 'string' || data['reasonMessage'] instanceof String)) {
            throw new Error("Expected the field `reasonMessage` to be a primitive type in the JSON string but got " + data['reasonMessage']);
        }
        // ensure the json data is a string
        if (data['additionResultData'] && !(typeof data['additionResultData'] === 'string' || data['additionResultData'] instanceof String)) {
            throw new Error("Expected the field `additionResultData` to be a primitive type in the JSON string but got " + data['additionResultData']);
        }
        // ensure the json data is a string
        if (data['additionResultData2'] && !(typeof data['additionResultData2'] === 'string' || data['additionResultData2'] instanceof String)) {
            throw new Error("Expected the field `additionResultData2` to be a primitive type in the JSON string but got " + data['additionResultData2']);
        }
        // ensure the json data is a string
        if (data['verification1Code'] && !(typeof data['verification1Code'] === 'string' || data['verification1Code'] instanceof String)) {
            throw new Error("Expected the field `verification1Code` to be a primitive type in the JSON string but got " + data['verification1Code']);
        }
        // ensure the json data is a string
        if (data['verification2Code'] && !(typeof data['verification2Code'] === 'string' || data['verification2Code'] instanceof String)) {
            throw new Error("Expected the field `verification2Code` to be a primitive type in the JSON string but got " + data['verification2Code']);
        }
        // ensure the json data is a string
        if (data['errorCode'] && !(typeof data['errorCode'] === 'string' || data['errorCode'] instanceof String)) {
            throw new Error("Expected the field `errorCode` to be a primitive type in the JSON string but got " + data['errorCode']);
        }
        // ensure the json data is a string
        if (data['errorMessage'] && !(typeof data['errorMessage'] === 'string' || data['errorMessage'] instanceof String)) {
            throw new Error("Expected the field `errorMessage` to be a primitive type in the JSON string but got " + data['errorMessage']);
        }
        // ensure the json data is a string
        if (data['merchantReference'] && !(typeof data['merchantReference'] === 'string' || data['merchantReference'] instanceof String)) {
            throw new Error("Expected the field `merchantReference` to be a primitive type in the JSON string but got " + data['merchantReference']);
        }

        return true;
    }


}



/**
 * @member {Boolean} success
 */
TransactionPaymentResponseTransactionResult.prototype['success'] = undefined;

/**
 * @member {String} processorAuthCode
 */
TransactionPaymentResponseTransactionResult.prototype['processorAuthCode'] = undefined;

/**
 * @member {String} traceNumber
 */
TransactionPaymentResponseTransactionResult.prototype['traceNumber'] = undefined;

/**
 * @member {String} reasonCode
 */
TransactionPaymentResponseTransactionResult.prototype['reasonCode'] = undefined;

/**
 * @member {String} reasonMessage
 */
TransactionPaymentResponseTransactionResult.prototype['reasonMessage'] = undefined;

/**
 * @member {String} additionResultData
 */
TransactionPaymentResponseTransactionResult.prototype['additionResultData'] = undefined;

/**
 * @member {String} additionResultData2
 */
TransactionPaymentResponseTransactionResult.prototype['additionResultData2'] = undefined;

/**
 * @member {Boolean} verificationStatus
 */
TransactionPaymentResponseTransactionResult.prototype['verificationStatus'] = undefined;

/**
 * @member {String} verification1Code
 */
TransactionPaymentResponseTransactionResult.prototype['verification1Code'] = undefined;

/**
 * @member {String} verification2Code
 */
TransactionPaymentResponseTransactionResult.prototype['verification2Code'] = undefined;

/**
 * @member {String} errorCode
 */
TransactionPaymentResponseTransactionResult.prototype['errorCode'] = undefined;

/**
 * @member {String} errorMessage
 */
TransactionPaymentResponseTransactionResult.prototype['errorMessage'] = undefined;

/**
 * @member {String} merchantReference
 */
TransactionPaymentResponseTransactionResult.prototype['merchantReference'] = undefined;






export default TransactionPaymentResponseTransactionResult;

