/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TransactionPaymentResponseAchTenderInfoCommissionType from './TransactionPaymentResponseAchTenderInfoCommissionType';

/**
 * The TransactionPaymentResponseAchTenderInfo model module.
 * @module model/TransactionPaymentResponseAchTenderInfo
 * @version 2.3
 */
class TransactionPaymentResponseAchTenderInfo {
    /**
     * Constructs a new <code>TransactionPaymentResponseAchTenderInfo</code>.
     * @alias module:model/TransactionPaymentResponseAchTenderInfo
     */
    constructor() { 
        
        TransactionPaymentResponseAchTenderInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionPaymentResponseAchTenderInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionPaymentResponseAchTenderInfo} obj Optional instance to populate.
     * @return {module:model/TransactionPaymentResponseAchTenderInfo} The populated <code>TransactionPaymentResponseAchTenderInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionPaymentResponseAchTenderInfo();

            if (data.hasOwnProperty('bankName')) {
                obj['bankName'] = ApiClient.convertToType(data['bankName'], 'String');
            }
            if (data.hasOwnProperty('routingNumber')) {
                obj['routingNumber'] = ApiClient.convertToType(data['routingNumber'], 'String');
            }
            if (data.hasOwnProperty('accountType')) {
                obj['accountType'] = ApiClient.convertToType(data['accountType'], 'String');
            }
            if (data.hasOwnProperty('checkType')) {
                obj['checkType'] = ApiClient.convertToType(data['checkType'], 'String');
            }
            if (data.hasOwnProperty('checkNumber')) {
                obj['checkNumber'] = ApiClient.convertToType(data['checkNumber'], 'String');
            }
            if (data.hasOwnProperty('nameOnCheck')) {
                obj['nameOnCheck'] = ApiClient.convertToType(data['nameOnCheck'], 'String');
            }
            if (data.hasOwnProperty('accountHolderName')) {
                obj['accountHolderName'] = ApiClient.convertToType(data['accountHolderName'], 'String');
            }
            if (data.hasOwnProperty('accountCategory')) {
                obj['accountCategory'] = ApiClient.convertToType(data['accountCategory'], 'String');
            }
            if (data.hasOwnProperty('captureAmount')) {
                obj['captureAmount'] = ApiClient.convertToType(data['captureAmount'], 'Number');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('convenienceAmount')) {
                obj['convenienceAmount'] = ApiClient.convertToType(data['convenienceAmount'], 'Number');
            }
            if (data.hasOwnProperty('binNumber')) {
                obj['binNumber'] = ApiClient.convertToType(data['binNumber'], 'String');
            }
            if (data.hasOwnProperty('adjustmentPercentValue')) {
                obj['adjustmentPercentValue'] = ApiClient.convertToType(data['adjustmentPercentValue'], 'Number');
            }
            if (data.hasOwnProperty('adjustmentFixedValue')) {
                obj['adjustmentFixedValue'] = ApiClient.convertToType(data['adjustmentFixedValue'], 'Number');
            }
            if (data.hasOwnProperty('adjustmentAmount')) {
                obj['adjustmentAmount'] = ApiClient.convertToType(data['adjustmentAmount'], 'Number');
            }
            if (data.hasOwnProperty('adjustmentDisplayName')) {
                obj['adjustmentDisplayName'] = ApiClient.convertToType(data['adjustmentDisplayName'], 'String');
            }
            if (data.hasOwnProperty('adjustmentDescriptorMessage')) {
                obj['adjustmentDescriptorMessage'] = ApiClient.convertToType(data['adjustmentDescriptorMessage'], 'String');
            }
            if (data.hasOwnProperty('paymentAdjustmentType')) {
                obj['paymentAdjustmentType'] = ApiClient.convertToType(data['paymentAdjustmentType'], 'String');
            }
            if (data.hasOwnProperty('preAuthCode')) {
                obj['preAuthCode'] = ApiClient.convertToType(data['preAuthCode'], 'String');
            }
            if (data.hasOwnProperty('maskAccount')) {
                obj['maskAccount'] = ApiClient.convertToType(data['maskAccount'], 'String');
            }
            if (data.hasOwnProperty('accountToken')) {
                obj['accountToken'] = ApiClient.convertToType(data['accountToken'], 'String');
            }
            if (data.hasOwnProperty('accountTokenMessage')) {
                obj['accountTokenMessage'] = ApiClient.convertToType(data['accountTokenMessage'], 'String');
            }
            if (data.hasOwnProperty('createAccountToken')) {
                obj['createAccountToken'] = ApiClient.convertToType(data['createAccountToken'], 'Boolean');
            }
            if (data.hasOwnProperty('commissionType')) {
                obj['commissionType'] = TransactionPaymentResponseAchTenderInfoCommissionType.constructFromObject(data['commissionType']);
            }
            if (data.hasOwnProperty('commissionValue')) {
                obj['commissionValue'] = ApiClient.convertToType(data['commissionValue'], 'Number');
            }
            if (data.hasOwnProperty('commissionFixedValue')) {
                obj['commissionFixedValue'] = ApiClient.convertToType(data['commissionFixedValue'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TransactionPaymentResponseAchTenderInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TransactionPaymentResponseAchTenderInfo</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['bankName'] && !(typeof data['bankName'] === 'string' || data['bankName'] instanceof String)) {
            throw new Error("Expected the field `bankName` to be a primitive type in the JSON string but got " + data['bankName']);
        }
        // ensure the json data is a string
        if (data['routingNumber'] && !(typeof data['routingNumber'] === 'string' || data['routingNumber'] instanceof String)) {
            throw new Error("Expected the field `routingNumber` to be a primitive type in the JSON string but got " + data['routingNumber']);
        }
        // ensure the json data is a string
        if (data['accountType'] && !(typeof data['accountType'] === 'string' || data['accountType'] instanceof String)) {
            throw new Error("Expected the field `accountType` to be a primitive type in the JSON string but got " + data['accountType']);
        }
        // ensure the json data is a string
        if (data['checkType'] && !(typeof data['checkType'] === 'string' || data['checkType'] instanceof String)) {
            throw new Error("Expected the field `checkType` to be a primitive type in the JSON string but got " + data['checkType']);
        }
        // ensure the json data is a string
        if (data['checkNumber'] && !(typeof data['checkNumber'] === 'string' || data['checkNumber'] instanceof String)) {
            throw new Error("Expected the field `checkNumber` to be a primitive type in the JSON string but got " + data['checkNumber']);
        }
        // ensure the json data is a string
        if (data['nameOnCheck'] && !(typeof data['nameOnCheck'] === 'string' || data['nameOnCheck'] instanceof String)) {
            throw new Error("Expected the field `nameOnCheck` to be a primitive type in the JSON string but got " + data['nameOnCheck']);
        }
        // ensure the json data is a string
        if (data['accountHolderName'] && !(typeof data['accountHolderName'] === 'string' || data['accountHolderName'] instanceof String)) {
            throw new Error("Expected the field `accountHolderName` to be a primitive type in the JSON string but got " + data['accountHolderName']);
        }
        // ensure the json data is a string
        if (data['accountCategory'] && !(typeof data['accountCategory'] === 'string' || data['accountCategory'] instanceof String)) {
            throw new Error("Expected the field `accountCategory` to be a primitive type in the JSON string but got " + data['accountCategory']);
        }
        // ensure the json data is a string
        if (data['binNumber'] && !(typeof data['binNumber'] === 'string' || data['binNumber'] instanceof String)) {
            throw new Error("Expected the field `binNumber` to be a primitive type in the JSON string but got " + data['binNumber']);
        }
        // ensure the json data is a string
        if (data['adjustmentDisplayName'] && !(typeof data['adjustmentDisplayName'] === 'string' || data['adjustmentDisplayName'] instanceof String)) {
            throw new Error("Expected the field `adjustmentDisplayName` to be a primitive type in the JSON string but got " + data['adjustmentDisplayName']);
        }
        // ensure the json data is a string
        if (data['adjustmentDescriptorMessage'] && !(typeof data['adjustmentDescriptorMessage'] === 'string' || data['adjustmentDescriptorMessage'] instanceof String)) {
            throw new Error("Expected the field `adjustmentDescriptorMessage` to be a primitive type in the JSON string but got " + data['adjustmentDescriptorMessage']);
        }
        // ensure the json data is a string
        if (data['paymentAdjustmentType'] && !(typeof data['paymentAdjustmentType'] === 'string' || data['paymentAdjustmentType'] instanceof String)) {
            throw new Error("Expected the field `paymentAdjustmentType` to be a primitive type in the JSON string but got " + data['paymentAdjustmentType']);
        }
        // ensure the json data is a string
        if (data['preAuthCode'] && !(typeof data['preAuthCode'] === 'string' || data['preAuthCode'] instanceof String)) {
            throw new Error("Expected the field `preAuthCode` to be a primitive type in the JSON string but got " + data['preAuthCode']);
        }
        // ensure the json data is a string
        if (data['maskAccount'] && !(typeof data['maskAccount'] === 'string' || data['maskAccount'] instanceof String)) {
            throw new Error("Expected the field `maskAccount` to be a primitive type in the JSON string but got " + data['maskAccount']);
        }
        // ensure the json data is a string
        if (data['accountToken'] && !(typeof data['accountToken'] === 'string' || data['accountToken'] instanceof String)) {
            throw new Error("Expected the field `accountToken` to be a primitive type in the JSON string but got " + data['accountToken']);
        }
        // ensure the json data is a string
        if (data['accountTokenMessage'] && !(typeof data['accountTokenMessage'] === 'string' || data['accountTokenMessage'] instanceof String)) {
            throw new Error("Expected the field `accountTokenMessage` to be a primitive type in the JSON string but got " + data['accountTokenMessage']);
        }
        // validate the optional field `commissionType`
        if (data['commissionType']) { // data not null
          TransactionPaymentResponseAchTenderInfoCommissionType.validateJSON(data['commissionType']);
        }

        return true;
    }


}



/**
 * @member {String} bankName
 */
TransactionPaymentResponseAchTenderInfo.prototype['bankName'] = undefined;

/**
 * @member {String} routingNumber
 */
TransactionPaymentResponseAchTenderInfo.prototype['routingNumber'] = undefined;

/**
 * @member {String} accountType
 */
TransactionPaymentResponseAchTenderInfo.prototype['accountType'] = undefined;

/**
 * @member {String} checkType
 */
TransactionPaymentResponseAchTenderInfo.prototype['checkType'] = undefined;

/**
 * @member {String} checkNumber
 */
TransactionPaymentResponseAchTenderInfo.prototype['checkNumber'] = undefined;

/**
 * @member {String} nameOnCheck
 */
TransactionPaymentResponseAchTenderInfo.prototype['nameOnCheck'] = undefined;

/**
 * @member {String} accountHolderName
 */
TransactionPaymentResponseAchTenderInfo.prototype['accountHolderName'] = undefined;

/**
 * @member {module:model/TransactionPaymentResponseAchTenderInfo.AccountCategoryEnum} accountCategory
 */
TransactionPaymentResponseAchTenderInfo.prototype['accountCategory'] = undefined;

/**
 * @member {Number} captureAmount
 */
TransactionPaymentResponseAchTenderInfo.prototype['captureAmount'] = undefined;

/**
 * @member {Number} amount
 */
TransactionPaymentResponseAchTenderInfo.prototype['amount'] = undefined;

/**
 * @member {Number} convenienceAmount
 */
TransactionPaymentResponseAchTenderInfo.prototype['convenienceAmount'] = undefined;

/**
 * @member {String} binNumber
 */
TransactionPaymentResponseAchTenderInfo.prototype['binNumber'] = undefined;

/**
 * @member {Number} adjustmentPercentValue
 */
TransactionPaymentResponseAchTenderInfo.prototype['adjustmentPercentValue'] = undefined;

/**
 * @member {Number} adjustmentFixedValue
 */
TransactionPaymentResponseAchTenderInfo.prototype['adjustmentFixedValue'] = undefined;

/**
 * @member {Number} adjustmentAmount
 */
TransactionPaymentResponseAchTenderInfo.prototype['adjustmentAmount'] = undefined;

/**
 * @member {String} adjustmentDisplayName
 */
TransactionPaymentResponseAchTenderInfo.prototype['adjustmentDisplayName'] = undefined;

/**
 * @member {String} adjustmentDescriptorMessage
 */
TransactionPaymentResponseAchTenderInfo.prototype['adjustmentDescriptorMessage'] = undefined;

/**
 * @member {module:model/TransactionPaymentResponseAchTenderInfo.PaymentAdjustmentTypeEnum} paymentAdjustmentType
 */
TransactionPaymentResponseAchTenderInfo.prototype['paymentAdjustmentType'] = undefined;

/**
 * @member {String} preAuthCode
 */
TransactionPaymentResponseAchTenderInfo.prototype['preAuthCode'] = undefined;

/**
 * @member {String} maskAccount
 */
TransactionPaymentResponseAchTenderInfo.prototype['maskAccount'] = undefined;

/**
 * @member {String} accountToken
 */
TransactionPaymentResponseAchTenderInfo.prototype['accountToken'] = undefined;

/**
 * @member {String} accountTokenMessage
 */
TransactionPaymentResponseAchTenderInfo.prototype['accountTokenMessage'] = undefined;

/**
 * @member {Boolean} createAccountToken
 */
TransactionPaymentResponseAchTenderInfo.prototype['createAccountToken'] = undefined;

/**
 * @member {module:model/TransactionPaymentResponseAchTenderInfoCommissionType} commissionType
 */
TransactionPaymentResponseAchTenderInfo.prototype['commissionType'] = undefined;

/**
 * @member {Number} commissionValue
 */
TransactionPaymentResponseAchTenderInfo.prototype['commissionValue'] = undefined;

/**
 * @member {Number} commissionFixedValue
 */
TransactionPaymentResponseAchTenderInfo.prototype['commissionFixedValue'] = undefined;





/**
 * Allowed values for the <code>accountCategory</code> property.
 * @enum {String}
 * @readonly
 */
TransactionPaymentResponseAchTenderInfo['AccountCategoryEnum'] = {

    /**
     * value: "Personal"
     * @const
     */
    "Personal": "Personal",

    /**
     * value: "Business"
     * @const
     */
    "Business": "Business"
};


/**
 * Allowed values for the <code>paymentAdjustmentType</code> property.
 * @enum {String}
 * @readonly
 */
TransactionPaymentResponseAchTenderInfo['PaymentAdjustmentTypeEnum'] = {

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "CashIncentive"
     * @const
     */
    "CashIncentive": "CashIncentive",

    /**
     * value: "Surcharge"
     * @const
     */
    "Surcharge": "Surcharge",

    /**
     * value: "ConvenienceFee"
     * @const
     */
    "ConvenienceFee": "ConvenienceFee",

    /**
     * value: "CashDiscount"
     * @const
     */
    "CashDiscount": "CashDiscount"
};



export default TransactionPaymentResponseAchTenderInfo;

