/**
 * Secure API
 * Secure API's
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.AdminTransactionEntityResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AdminTransactionEntityResponse', function() {
    it('should create an instance of AdminTransactionEntityResponse', function() {
      // uncomment below and update the code to test AdminTransactionEntityResponse
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be.a(SecureApi.AdminTransactionEntityResponse);
    });

    it('should have the property transactionId (base name: "transactionId")', function() {
      // uncomment below and update the code to test the property transactionId
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property merchantId (base name: "merchantId")', function() {
      // uncomment below and update the code to test the property merchantId
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property merchantName (base name: "merchantName")', function() {
      // uncomment below and update the code to test the property merchantName
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property transactionDate (base name: "transactionDate")', function() {
      // uncomment below and update the code to test the property transactionDate
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property operationType (base name: "operationType")', function() {
      // uncomment below and update the code to test the property operationType
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property channelType (base name: "channelType")', function() {
      // uncomment below and update the code to test the property channelType
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property processMethod (base name: "processMethod")', function() {
      // uncomment below and update the code to test the property processMethod
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property isDebit (base name: "isDebit")', function() {
      // uncomment below and update the code to test the property isDebit
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property referenceTransactionId (base name: "referenceTransactionId")', function() {
      // uncomment below and update the code to test the property referenceTransactionId
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property referenceCustomerId (base name: "referenceCustomerId")', function() {
      // uncomment below and update the code to test the property referenceCustomerId
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property customerAccountId (base name: "customerAccountId")', function() {
      // uncomment below and update the code to test the property customerAccountId
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property recurringId (base name: "recurringId")', function() {
      // uncomment below and update the code to test the property recurringId
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property batchId (base name: "batchId")', function() {
      // uncomment below and update the code to test the property batchId
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property transactionStatus (base name: "transactionStatus")', function() {
      // uncomment below and update the code to test the property transactionStatus
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property settlementDate (base name: "settlementDate")', function() {
      // uncomment below and update the code to test the property settlementDate
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property authCode (base name: "authCode")', function() {
      // uncomment below and update the code to test the property authCode
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property cardNumber (base name: "cardNumber")', function() {
      // uncomment below and update the code to test the property cardNumber
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property accountNumber (base name: "accountNumber")', function() {
      // uncomment below and update the code to test the property accountNumber
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property chequeNumber (base name: "chequeNumber")', function() {
      // uncomment below and update the code to test the property chequeNumber
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property routingNumber (base name: "routingNumber")', function() {
      // uncomment below and update the code to test the property routingNumber
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property nameOnCheckOrCard (base name: "nameOnCheckOrCard")', function() {
      // uncomment below and update the code to test the property nameOnCheckOrCard
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property accountHolderName (base name: "accountHolderName")', function() {
      // uncomment below and update the code to test the property accountHolderName
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property accountCategory (base name: "accountCategory")', function() {
      // uncomment below and update the code to test the property accountCategory
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property convenienceAmount (base name: "convenienceAmount")', function() {
      // uncomment below and update the code to test the property convenienceAmount
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property captureAmount (base name: "captureAmount")', function() {
      // uncomment below and update the code to test the property captureAmount
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property taxPercent (base name: "taxPercent")', function() {
      // uncomment below and update the code to test the property taxPercent
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property taxAmount (base name: "taxAmount")', function() {
      // uncomment below and update the code to test the property taxAmount
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property cardType (base name: "cardType")', function() {
      // uncomment below and update the code to test the property cardType
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property customerName (base name: "customerName")', function() {
      // uncomment below and update the code to test the property customerName
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property maskedInvoiceId (base name: "maskedInvoiceId")', function() {
      // uncomment below and update the code to test the property maskedInvoiceId
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property maskedPaymentLinkId (base name: "maskedPaymentLinkId")', function() {
      // uncomment below and update the code to test the property maskedPaymentLinkId
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property referenceNo (base name: "referenceNo")', function() {
      // uncomment below and update the code to test the property referenceNo
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property processorName (base name: "processorName")', function() {
      // uncomment below and update the code to test the property processorName
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property processorDisplayName (base name: "processorDisplayName")', function() {
      // uncomment below and update the code to test the property processorDisplayName
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property processorCode (base name: "processorCode")', function() {
      // uncomment below and update the code to test the property processorCode
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property verification2Code (base name: "verification2Code")', function() {
      // uncomment below and update the code to test the property verification2Code
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property transactionOrigin (base name: "transactionOrigin")', function() {
      // uncomment below and update the code to test the property transactionOrigin
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property commissionType (base name: "commissionType")', function() {
      // uncomment below and update the code to test the property commissionType
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property commissionValue (base name: "commissionValue")', function() {
      // uncomment below and update the code to test the property commissionValue
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property commissionFixedValue (base name: "commissionFixedValue")', function() {
      // uncomment below and update the code to test the property commissionFixedValue
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentFixedValue (base name: "adjustmentFixedValue")', function() {
      // uncomment below and update the code to test the property adjustmentFixedValue
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentValue (base name: "adjustmentValue")', function() {
      // uncomment below and update the code to test the property adjustmentValue
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentValueType (base name: "adjustmentValueType")', function() {
      // uncomment below and update the code to test the property adjustmentValueType
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentAmount (base name: "adjustmentAmount")', function() {
      // uncomment below and update the code to test the property adjustmentAmount
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentDisplayName (base name: "adjustmentDisplayName")', function() {
      // uncomment below and update the code to test the property adjustmentDisplayName
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentDescriptorMessage (base name: "adjustmentDescriptorMessage")', function() {
      // uncomment below and update the code to test the property adjustmentDescriptorMessage
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property paymentAdjustmentType (base name: "paymentAdjustmentType")', function() {
      // uncomment below and update the code to test the property paymentAdjustmentType
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property traceNumber (base name: "traceNumber")', function() {
      // uncomment below and update the code to test the property traceNumber
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "createdOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property modifiedOn (base name: "modifiedOn")', function() {
      // uncomment below and update the code to test the property modifiedOn
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property modifiedBy (base name: "modifiedBy")', function() {
      // uncomment below and update the code to test the property modifiedBy
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property merchantReference (base name: "merchantReference")', function() {
      // uncomment below and update the code to test the property merchantReference
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property additionaFields (base name: "additionaFields")', function() {
      // uncomment below and update the code to test the property additionaFields
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property paymentType (base name: "paymentType")', function() {
      // uncomment below and update the code to test the property paymentType
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property paymentCategory (base name: "paymentCategory")', function() {
      // uncomment below and update the code to test the property paymentCategory
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property merchantDBAName (base name: "merchantDBAName")', function() {
      // uncomment below and update the code to test the property merchantDBAName
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

    it('should have the property fullAccountNumber (base name: "fullAccountNumber")', function() {
      // uncomment below and update the code to test the property fullAccountNumber
      //var instance = new SecureApi.AdminTransactionEntityResponse();
      //expect(instance).to.be();
    });

  });

}));
