/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.PagePaymentListResponseDTODataInner();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PagePaymentListResponseDTODataInner', function() {
    it('should create an instance of PagePaymentListResponseDTODataInner', function() {
      // uncomment below and update the code to test PagePaymentListResponseDTODataInner
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be.a(SecureApi.PagePaymentListResponseDTODataInner);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be();
    });

    it('should have the property merchantId (base name: "merchantId")', function() {
      // uncomment below and update the code to test the property merchantId
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be();
    });

    it('should have the property merchantDBAName (base name: "merchantDBAName")', function() {
      // uncomment below and update the code to test the property merchantDBAName
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethodType (base name: "paymentMethodType")', function() {
      // uncomment below and update the code to test the property paymentMethodType
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be();
    });

    it('should have the property paymentBasedId (base name: "paymentBasedId")', function() {
      // uncomment below and update the code to test the property paymentBasedId
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be();
    });

    it('should have the property vendorId (base name: "vendorId")', function() {
      // uncomment below and update the code to test the property vendorId
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be();
    });

    it('should have the property vendorName (base name: "vendorName")', function() {
      // uncomment below and update the code to test the property vendorName
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be();
    });

    it('should have the property paymentId (base name: "paymentId")', function() {
      // uncomment below and update the code to test the property paymentId
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethodStatus (base name: "paymentMethodStatus")', function() {
      // uncomment below and update the code to test the property paymentMethodStatus
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be();
    });

    it('should have the property requestedDate (base name: "requestedDate")', function() {
      // uncomment below and update the code to test the property requestedDate
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new SecureApi.PagePaymentListResponseDTODataInner();
      //expect(instance).to.be();
    });

  });

}));
