/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.PaymentBatchEventLogResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentBatchEventLogResponse', function() {
    it('should create an instance of PaymentBatchEventLogResponse', function() {
      // uncomment below and update the code to test PaymentBatchEventLogResponse
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be.a(SecureApi.PaymentBatchEventLogResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property batchId (base name: "batchId")', function() {
      // uncomment below and update the code to test the property batchId
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property merchantId (base name: "merchantId")', function() {
      // uncomment below and update the code to test the property merchantId
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property previousEventStatus (base name: "previousEventStatus")', function() {
      // uncomment below and update the code to test the property previousEventStatus
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property eventStatus (base name: "eventStatus")', function() {
      // uncomment below and update the code to test the property eventStatus
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property voidedCount (base name: "voidedCount")', function() {
      // uncomment below and update the code to test the property voidedCount
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property voidedAmount (base name: "voidedAmount")', function() {
      // uncomment below and update the code to test the property voidedAmount
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property closedOn (base name: "closedOn")', function() {
      // uncomment below and update the code to test the property closedOn
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property eventDate (base name: "eventDate")', function() {
      // uncomment below and update the code to test the property eventDate
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property closingAmount (base name: "closingAmount")', function() {
      // uncomment below and update the code to test the property closingAmount
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "createdOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property modifiedOn (base name: "modifiedOn")', function() {
      // uncomment below and update the code to test the property modifiedOn
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

    it('should have the property modifiedBy (base name: "modifiedBy")', function() {
      // uncomment below and update the code to test the property modifiedBy
      //var instance = new SecureApi.PaymentBatchEventLogResponse();
      //expect(instance).to.be();
    });

  });

}));
