/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.PFEndorsementResponseItemPaymentIntent();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PFEndorsementResponseItemPaymentIntent', function() {
    it('should create an instance of PFEndorsementResponseItemPaymentIntent', function() {
      // uncomment below and update the code to test PFEndorsementResponseItemPaymentIntent
      //var instance = new SecureApi.PFEndorsementResponseItemPaymentIntent();
      //expect(instance).to.be.a(SecureApi.PFEndorsementResponseItemPaymentIntent);
    });

    it('should have the property paymentToken (base name: "paymentToken")', function() {
      // uncomment below and update the code to test the property paymentToken
      //var instance = new SecureApi.PFEndorsementResponseItemPaymentIntent();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new SecureApi.PFEndorsementResponseItemPaymentIntent();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new SecureApi.PFEndorsementResponseItemPaymentIntent();
      //expect(instance).to.be();
    });

    it('should have the property invoiceNumber (base name: "invoiceNumber")', function() {
      // uncomment below and update the code to test the property invoiceNumber
      //var instance = new SecureApi.PFEndorsementResponseItemPaymentIntent();
      //expect(instance).to.be();
    });

    it('should have the property expireOn (base name: "expireOn")', function() {
      // uncomment below and update the code to test the property expireOn
      //var instance = new SecureApi.PFEndorsementResponseItemPaymentIntent();
      //expect(instance).to.be();
    });

    it('should have the property shortDescription (base name: "shortDescription")', function() {
      // uncomment below and update the code to test the property shortDescription
      //var instance = new SecureApi.PFEndorsementResponseItemPaymentIntent();
      //expect(instance).to.be();
    });

    it('should have the property paymentDescription (base name: "paymentDescription")', function() {
      // uncomment below and update the code to test the property paymentDescription
      //var instance = new SecureApi.PFEndorsementResponseItemPaymentIntent();
      //expect(instance).to.be();
    });

    it('should have the property intent (base name: "intent")', function() {
      // uncomment below and update the code to test the property intent
      //var instance = new SecureApi.PFEndorsementResponseItemPaymentIntent();
      //expect(instance).to.be();
    });

  });

}));
