/**
 * Secure API
 * Secure API's
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.PFEndorsementResponseItemQuoteESignResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PFEndorsementResponseItemQuoteESignResult', function() {
    it('should create an instance of PFEndorsementResponseItemQuoteESignResult', function() {
      // uncomment below and update the code to test PFEndorsementResponseItemQuoteESignResult
      //var instance = new SecureApi.PFEndorsementResponseItemQuoteESignResult();
      //expect(instance).to.be.a(SecureApi.PFEndorsementResponseItemQuoteESignResult);
    });

    it('should have the property processed (base name: "processed")', function() {
      // uncomment below and update the code to test the property processed
      //var instance = new SecureApi.PFEndorsementResponseItemQuoteESignResult();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instance = new SecureApi.PFEndorsementResponseItemQuoteESignResult();
      //expect(instance).to.be();
    });

    it('should have the property batchID (base name: "batchID")', function() {
      // uncomment below and update the code to test the property batchID
      //var instance = new SecureApi.PFEndorsementResponseItemQuoteESignResult();
      //expect(instance).to.be();
    });

    it('should have the property agentURL (base name: "agentURL")', function() {
      // uncomment below and update the code to test the property agentURL
      //var instance = new SecureApi.PFEndorsementResponseItemQuoteESignResult();
      //expect(instance).to.be();
    });

    it('should have the property insuredURL (base name: "insuredURL")', function() {
      // uncomment below and update the code to test the property insuredURL
      //var instance = new SecureApi.PFEndorsementResponseItemQuoteESignResult();
      //expect(instance).to.be();
    });

    it('should have the property eSignOption (base name: "eSignOption")', function() {
      // uncomment below and update the code to test the property eSignOption
      //var instance = new SecureApi.PFEndorsementResponseItemQuoteESignResult();
      //expect(instance).to.be();
    });

  });

}));
