/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.PFLiteSecureQuoteRequestAgent();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PFLiteSecureQuoteRequestAgent', function() {
    it('should create an instance of PFLiteSecureQuoteRequestAgent', function() {
      // uncomment below and update the code to test PFLiteSecureQuoteRequestAgent
      //var instance = new SecureApi.PFLiteSecureQuoteRequestAgent();
      //expect(instance).to.be.a(SecureApi.PFLiteSecureQuoteRequestAgent);
    });

    it('should have the property uniqueID (base name: "uniqueID")', function() {
      // uncomment below and update the code to test the property uniqueID
      //var instance = new SecureApi.PFLiteSecureQuoteRequestAgent();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new SecureApi.PFLiteSecureQuoteRequestAgent();
      //expect(instance).to.be();
    });

    it('should have the property careOf (base name: "careOf")', function() {
      // uncomment below and update the code to test the property careOf
      //var instance = new SecureApi.PFLiteSecureQuoteRequestAgent();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new SecureApi.PFLiteSecureQuoteRequestAgent();
      //expect(instance).to.be();
    });

  });

}));
