/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.PFQuoteEsignRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PFQuoteEsignRequest', function() {
    it('should create an instance of PFQuoteEsignRequest', function() {
      // uncomment below and update the code to test PFQuoteEsignRequest
      //var instance = new SecureApi.PFQuoteEsignRequest();
      //expect(instance).to.be.a(SecureApi.PFQuoteEsignRequest);
    });

    it('should have the property merchantToken (base name: "merchantToken")', function() {
      // uncomment below and update the code to test the property merchantToken
      //var instance = new SecureApi.PFQuoteEsignRequest();
      //expect(instance).to.be();
    });

    it('should have the property quoteKey (base name: "quoteKey")', function() {
      // uncomment below and update the code to test the property quoteKey
      //var instance = new SecureApi.PFQuoteEsignRequest();
      //expect(instance).to.be();
    });

    it('should have the property insuredName (base name: "insuredName")', function() {
      // uncomment below and update the code to test the property insuredName
      //var instance = new SecureApi.PFQuoteEsignRequest();
      //expect(instance).to.be();
    });

    it('should have the property ipAddress (base name: "ipAddress")', function() {
      // uncomment below and update the code to test the property ipAddress
      //var instance = new SecureApi.PFQuoteEsignRequest();
      //expect(instance).to.be();
    });

    it('should have the property macAddress (base name: "macAddress")', function() {
      // uncomment below and update the code to test the property macAddress
      //var instance = new SecureApi.PFQuoteEsignRequest();
      //expect(instance).to.be();
    });

    it('should have the property captchaToken (base name: "captchaToken")', function() {
      // uncomment below and update the code to test the property captchaToken
      //var instance = new SecureApi.PFQuoteEsignRequest();
      //expect(instance).to.be();
    });

    it('should have the property actionName (base name: "actionName")', function() {
      // uncomment below and update the code to test the property actionName
      //var instance = new SecureApi.PFQuoteEsignRequest();
      //expect(instance).to.be();
    });

  });

}));
