/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.QuoteRequestDetails();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('QuoteRequestDetails', function() {
    it('should create an instance of QuoteRequestDetails', function() {
      // uncomment below and update the code to test QuoteRequestDetails
      //var instance = new SecureApi.QuoteRequestDetails();
      //expect(instance).to.be.a(SecureApi.QuoteRequestDetails);
    });

    it('should have the property couponInvoicePrinted (base name: "couponInvoicePrinted")', function() {
      // uncomment below and update the code to test the property couponInvoicePrinted
      //var instance = new SecureApi.QuoteRequestDetails();
      //expect(instance).to.be();
    });

    it('should have the property installments (base name: "installments")', function() {
      // uncomment below and update the code to test the property installments
      //var instance = new SecureApi.QuoteRequestDetails();
      //expect(instance).to.be();
    });

    it('should have the property programIDs (base name: "programIDs")', function() {
      // uncomment below and update the code to test the property programIDs
      //var instance = new SecureApi.QuoteRequestDetails();
      //expect(instance).to.be();
    });

    it('should have the property batchID (base name: "batchID")', function() {
      // uncomment below and update the code to test the property batchID
      //var instance = new SecureApi.QuoteRequestDetails();
      //expect(instance).to.be();
    });

    it('should have the property commercial (base name: "commercial")', function() {
      // uncomment below and update the code to test the property commercial
      //var instance = new SecureApi.QuoteRequestDetails();
      //expect(instance).to.be();
    });

    it('should have the property coupon (base name: "coupon")', function() {
      // uncomment below and update the code to test the property coupon
      //var instance = new SecureApi.QuoteRequestDetails();
      //expect(instance).to.be();
    });

    it('should have the property interval (base name: "interval")', function() {
      // uncomment below and update the code to test the property interval
      //var instance = new SecureApi.QuoteRequestDetails();
      //expect(instance).to.be();
    });

    it('should have the property downPaymentMethod (base name: "downPaymentMethod")', function() {
      // uncomment below and update the code to test the property downPaymentMethod
      //var instance = new SecureApi.QuoteRequestDetails();
      //expect(instance).to.be();
    });

    it('should have the property downPaymentPaidBy (base name: "downPaymentPaidBy")', function() {
      // uncomment below and update the code to test the property downPaymentPaidBy
      //var instance = new SecureApi.QuoteRequestDetails();
      //expect(instance).to.be();
    });

  });

}));
