/**
 * Secure API
 * Secure API's
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.ReportDownloadRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReportDownloadRequest', function() {
    it('should create an instance of ReportDownloadRequest', function() {
      // uncomment below and update the code to test ReportDownloadRequest
      //var instance = new SecureApi.ReportDownloadRequest();
      //expect(instance).to.be.a(SecureApi.ReportDownloadRequest);
    });

    it('should have the property reportId (base name: "reportId")', function() {
      // uncomment below and update the code to test the property reportId
      //var instance = new SecureApi.ReportDownloadRequest();
      //expect(instance).to.be();
    });

    it('should have the property reportGenerationLogId (base name: "reportGenerationLogId")', function() {
      // uncomment below and update the code to test the property reportGenerationLogId
      //var instance = new SecureApi.ReportDownloadRequest();
      //expect(instance).to.be();
    });

    it('should have the property fileCompress (base name: "fileCompress")', function() {
      // uncomment below and update the code to test the property fileCompress
      //var instance = new SecureApi.ReportDownloadRequest();
      //expect(instance).to.be();
    });

    it('should have the property date (base name: "date")', function() {
      // uncomment below and update the code to test the property date
      //var instance = new SecureApi.ReportDownloadRequest();
      //expect(instance).to.be();
    });

  });

}));
