/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.SecureUpdatePaymentLinkRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SecureUpdatePaymentLinkRequest', function() {
    it('should create an instance of SecureUpdatePaymentLinkRequest', function() {
      // uncomment below and update the code to test SecureUpdatePaymentLinkRequest
      //var instance = new SecureApi.SecureUpdatePaymentLinkRequest();
      //expect(instance).to.be.a(SecureApi.SecureUpdatePaymentLinkRequest);
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new SecureApi.SecureUpdatePaymentLinkRequest();
      //expect(instance).to.be();
    });

    it('should have the property enablePartialPayment (base name: "enablePartialPayment")', function() {
      // uncomment below and update the code to test the property enablePartialPayment
      //var instance = new SecureApi.SecureUpdatePaymentLinkRequest();
      //expect(instance).to.be();
    });

    it('should have the property enableMultiplePayment (base name: "enableMultiplePayment")', function() {
      // uncomment below and update the code to test the property enableMultiplePayment
      //var instance = new SecureApi.SecureUpdatePaymentLinkRequest();
      //expect(instance).to.be();
    });

    it('should have the property enableProtection (base name: "enableProtection")', function() {
      // uncomment below and update the code to test the property enableProtection
      //var instance = new SecureApi.SecureUpdatePaymentLinkRequest();
      //expect(instance).to.be();
    });

    it('should have the property enablePremiumFinance (base name: "enablePremiumFinance")', function() {
      // uncomment below and update the code to test the property enablePremiumFinance
      //var instance = new SecureApi.SecureUpdatePaymentLinkRequest();
      //expect(instance).to.be();
    });

    it('should have the property expireIn (base name: "expireIn")', function() {
      // uncomment below and update the code to test the property expireIn
      //var instance = new SecureApi.SecureUpdatePaymentLinkRequest();
      //expect(instance).to.be();
    });

    it('should have the property expireInUnit (base name: "expireInUnit")', function() {
      // uncomment below and update the code to test the property expireInUnit
      //var instance = new SecureApi.SecureUpdatePaymentLinkRequest();
      //expect(instance).to.be();
    });

    it('should have the property settings (base name: "settings")', function() {
      // uncomment below and update the code to test the property settings
      //var instance = new SecureApi.SecureUpdatePaymentLinkRequest();
      //expect(instance).to.be();
    });

    it('should have the property suppressTechnologyFee (base name: "suppressTechnologyFee")', function() {
      // uncomment below and update the code to test the property suppressTechnologyFee
      //var instance = new SecureApi.SecureUpdatePaymentLinkRequest();
      //expect(instance).to.be();
    });

    it('should have the property overrideTechnologyFee (base name: "overrideTechnologyFee")', function() {
      // uncomment below and update the code to test the property overrideTechnologyFee
      //var instance = new SecureApi.SecureUpdatePaymentLinkRequest();
      //expect(instance).to.be();
    });

  });

}));
