/**
 * Secure API
 * Secure API's
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SecurePaymentDetailsResponseCcTenderInfo', function() {
    it('should create an instance of SecurePaymentDetailsResponseCcTenderInfo', function() {
      // uncomment below and update the code to test SecurePaymentDetailsResponseCcTenderInfo
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be.a(SecureApi.SecurePaymentDetailsResponseCcTenderInfo);
    });

    it('should have the property cardHolderName (base name: "cardHolderName")', function() {
      // uncomment below and update the code to test the property cardHolderName
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property maskCardNumber (base name: "maskCardNumber")', function() {
      // uncomment below and update the code to test the property maskCardNumber
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property cardExpiry (base name: "cardExpiry")', function() {
      // uncomment below and update the code to test the property cardExpiry
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property captureAmount (base name: "captureAmount")', function() {
      // uncomment below and update the code to test the property captureAmount
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property binNumber (base name: "binNumber")', function() {
      // uncomment below and update the code to test the property binNumber
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property taxAmount (base name: "taxAmount")', function() {
      // uncomment below and update the code to test the property taxAmount
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property taxAfterDiscount (base name: "taxAfterDiscount")', function() {
      // uncomment below and update the code to test the property taxAfterDiscount
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property taxPercent (base name: "taxPercent")', function() {
      // uncomment below and update the code to test the property taxPercent
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentPercentValue (base name: "adjustmentPercentValue")', function() {
      // uncomment below and update the code to test the property adjustmentPercentValue
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentFixedValue (base name: "adjustmentFixedValue")', function() {
      // uncomment below and update the code to test the property adjustmentFixedValue
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentAmount (base name: "adjustmentAmount")', function() {
      // uncomment below and update the code to test the property adjustmentAmount
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentDisplayName (base name: "adjustmentDisplayName")', function() {
      // uncomment below and update the code to test the property adjustmentDisplayName
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property adjustmentDescriptorMessage (base name: "adjustmentDescriptorMessage")', function() {
      // uncomment below and update the code to test the property adjustmentDescriptorMessage
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property paymentAdjustmentType (base name: "paymentAdjustmentType")', function() {
      // uncomment below and update the code to test the property paymentAdjustmentType
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property preAuthCode (base name: "preAuthCode")', function() {
      // uncomment below and update the code to test the property preAuthCode
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property maskAccount (base name: "maskAccount")', function() {
      // uncomment below and update the code to test the property maskAccount
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property accountToken (base name: "accountToken")', function() {
      // uncomment below and update the code to test the property accountToken
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property accountTokenMessage (base name: "accountTokenMessage")', function() {
      // uncomment below and update the code to test the property accountTokenMessage
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property createAccountToken (base name: "createAccountToken")', function() {
      // uncomment below and update the code to test the property createAccountToken
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property discountType (base name: "discountType")', function() {
      // uncomment below and update the code to test the property discountType
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property discountPercent (base name: "discountPercent")', function() {
      // uncomment below and update the code to test the property discountPercent
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property discountAmount (base name: "discountAmount")', function() {
      // uncomment below and update the code to test the property discountAmount
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property convenienceAmount (base name: "convenienceAmount")', function() {
      // uncomment below and update the code to test the property convenienceAmount
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property commissionType (base name: "commissionType")', function() {
      // uncomment below and update the code to test the property commissionType
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

    it('should have the property commissionValue (base name: "commissionValue")', function() {
      // uncomment below and update the code to test the property commissionValue
      //var instance = new SecureApi.SecurePaymentDetailsResponseCcTenderInfo();
      //expect(instance).to.be();
    });

  });

}));
