/**
 * Secure API
 * Secure API's
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.TransactionDetailResponseTransactionResult();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionDetailResponseTransactionResult', function() {
    it('should create an instance of TransactionDetailResponseTransactionResult', function() {
      // uncomment below and update the code to test TransactionDetailResponseTransactionResult
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be.a(SecureApi.TransactionDetailResponseTransactionResult);
    });

    it('should have the property success (base name: "success")', function() {
      // uncomment below and update the code to test the property success
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property processorAuthCode (base name: "processorAuthCode")', function() {
      // uncomment below and update the code to test the property processorAuthCode
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property traceNumber (base name: "traceNumber")', function() {
      // uncomment below and update the code to test the property traceNumber
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property reasonCode (base name: "reasonCode")', function() {
      // uncomment below and update the code to test the property reasonCode
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property reasonMessage (base name: "reasonMessage")', function() {
      // uncomment below and update the code to test the property reasonMessage
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property additionResultData (base name: "additionResultData")', function() {
      // uncomment below and update the code to test the property additionResultData
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property additionResultData2 (base name: "additionResultData2")', function() {
      // uncomment below and update the code to test the property additionResultData2
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property verificationStatus (base name: "verificationStatus")', function() {
      // uncomment below and update the code to test the property verificationStatus
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property verification1Code (base name: "verification1Code")', function() {
      // uncomment below and update the code to test the property verification1Code
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property verification2Code (base name: "verification2Code")', function() {
      // uncomment below and update the code to test the property verification2Code
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property errorCode (base name: "errorCode")', function() {
      // uncomment below and update the code to test the property errorCode
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property errorMessage (base name: "errorMessage")', function() {
      // uncomment below and update the code to test the property errorMessage
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

    it('should have the property merchantReference (base name: "merchantReference")', function() {
      // uncomment below and update the code to test the property merchantReference
      //var instance = new SecureApi.TransactionDetailResponseTransactionResult();
      //expect(instance).to.be();
    });

  });

}));
