/**
 * Secure API
 * Secure API
 *
 * The version of the OpenAPI document: 2.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SecureApi);
  }
}(this, function(expect, SecureApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SecureApi.VerifyBankAccountResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('VerifyBankAccountResponse', function() {
    it('should create an instance of VerifyBankAccountResponse', function() {
      // uncomment below and update the code to test VerifyBankAccountResponse
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be.a(SecureApi.VerifyBankAccountResponse);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property verificationEntityId (base name: "verificationEntityId")', function() {
      // uncomment below and update the code to test the property verificationEntityId
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property verifyingEntity (base name: "verifyingEntity")', function() {
      // uncomment below and update the code to test the property verifyingEntity
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property verificationStatus (base name: "verificationStatus")', function() {
      // uncomment below and update the code to test the property verificationStatus
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property statusReason (base name: "statusReason")', function() {
      // uncomment below and update the code to test the property statusReason
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property estimatedVerificationDate (base name: "estimatedVerificationDate")', function() {
      // uncomment below and update the code to test the property estimatedVerificationDate
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property eventId (base name: "eventId")', function() {
      // uncomment below and update the code to test the property eventId
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property eventType (base name: "eventType")', function() {
      // uncomment below and update the code to test the property eventType
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property bankAccountEntityId (base name: "bankAccountEntityId")', function() {
      // uncomment below and update the code to test the property bankAccountEntityId
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property bankAccountEntityType (base name: "bankAccountEntityType")', function() {
      // uncomment below and update the code to test the property bankAccountEntityType
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdOn (base name: "createdOn")', function() {
      // uncomment below and update the code to test the property createdOn
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "createdBy")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property modifiedOn (base name: "modifiedOn")', function() {
      // uncomment below and update the code to test the property modifiedOn
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property modifiedBy (base name: "modifiedBy")', function() {
      // uncomment below and update the code to test the property modifiedBy
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

    it('should have the property httpResponse (base name: "httpResponse")', function() {
      // uncomment below and update the code to test the property httpResponse
      //var instance = new SecureApi.VerifyBankAccountResponse();
      //expect(instance).to.be();
    });

  });

}));
